### ISSUE TITLE
Clicking Back on image preview scrolls screen down

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1016]
http://recordit.co/JCBPxUyokr

**Comment by rodrigopavezi** [comment]
@rhdelima which version of the wallet?

**Comment by rhdelima** [comment]
@rodrigopavezi I'm using the latest release build

**Comment by rhdelima** [comment]
Rejecting this one as issue still persist on the latest build (dev_2019.06.11.17)

**Comment by eduardosmoura** [comment]
@rhdelima Please wait for the latest dev branch build. It should be ready by 7/2.
