### ISSUE TITLE
Improve Wallet Update

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#1020]
Our update flow is still not good, users are confused. We need to notify about update availability immediately and show download progress.
I would also argue about making it optional, with an annoying sticky "Please update" warning. It's just a good practice to have.

![Screen Shot 2019-03-26 at 00.47.08.png](https://images.zenhubusercontent.com/5b7bd3b852bce06c3c5c53c0/98d63602-1d09-4b43-9d9e-77f4252e27d9)

**Comment by oanamangiurea** [comment]
@rodrigopavezi 
1. Where do I find the previous release of the wallet so I can see it updates (I already have latest version). If I take the last version i found from 2018 from the release build https://console.cloud.google.com/storage/browser/selfkey-builds/release/2018.08.31.18/ will it work?
2. Any limitations from Electron regarding updates?

**Comment by oanamangiurea** [comment]
We have 2 situations:

1. The user has the wallet open when an update becomes available OR it hit the remind me later button - so sticky message appears: https://projects.invisionapp.com/d/main#/console/15222689/355164658/preview

2. The user just opens the wallet and there is an update: https://projects.invisionapp.com/d/main#/console/15222689/355164657/preview

In both cases, when pressing Download  & Install - this progress modal appears: https://projects.invisionapp.com/d/main#/console/15222689/355164656/preview

**Comment by sk91** [comment]
@oanamangiurea please move it to back to backlog for dev team or create new dev specific issue for this
