### ISSUE TITLE
New layout for Exchanges

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1021]
https://projects.invisionapp.com/d/#/console/15222689/347983073/preview

**Comment by rodrigopavezi** [comment]
https://us-central1-kycchain-master.cloudfunctions.net/airtable?tableName=Exchanges

**Comment by rodrigopavezi** [comment]
https://us-central1-kycchain-master.cloudfunctions.net/airtable?tableName=ExchangesDev
