### ISSUE TITLE
Handle properly all kyc statuses

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1033]
https://confluence.kyc-chain.com/display/DEV/KYC+Application+Statuses
https://github.com/SelfKeyFoundation/selfkey-lib/blob/32e1bd4d8c54df46c02e68181595b13e1bb2e750/example/kyc-status.js

NOTE:

In the KYC instance currently running for incorporations, USER_PROCESSING_REQUIREMENTS will be shown as UPLOADED

**Comment by felipewer** [comment]
KYC-Chain related issue: https://github.com/kyc-chain/kyc-chain-monorepo/issues/571

**Comment by CortecKYC** [comment]
Not applicable anymore.
@sk91 take a look please and close if it's not relevant any more.

**Comment by sk91** [comment]
This was fixed by kyc-chain, wallet handles statuses correctly. Closing.
