### ISSUE TITLE
Wallet-v1.0.0: Cannot read property 'kdf' of undefined

### ISSUE THREAD

**Issue by vitalikda** [SelfKeyFoundation/Identity-Wallet#1037]
User cannot log in SelfKey Wallet 1.0.0-beta, because she gets the error message: `Cannot read property 'kdf' of undefined`.

**Steps to reproduce:**
1. Create a new wallet on the old MEW website: https://vintage.myetherwallet.com
2. Download Keystore file 
3. In the SelfKey Wallet add a new address using Keystore file
4. Enter your password (from step 1)

**Actual result:**
You see the error message `Cannot read property 'kdf' of undefined`.

**Expected result:**
You add a new wallet address.

**Screenshots:**
<img width="1282" alt="Screenshot 2019-04-02 at 19 31 21" src="https://user-images.githubusercontent.com/9862028/55427066-e2c83780-558e-11e9-92d0-e0f496ed772b.png">

**Comment by CortecKYC** [comment]
@rodrigopavezi Can we finish this and close it?

**Comment by rhdelima** [comment]
Issue is no longer encountered on latest release build v.1.0.1. Pass
