### ISSUE TITLE
Change old Tags

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1048]
- Change old tags to Material UI ones in Selfkey UI and Wallet.
- Remove unnecessary tags.

**Comment by CortecKYC** [comment]
@designhorf Can we close this ticket?

**Comment by designhorf** [comment]
@CortecKYC yes, we can. I close it

**Comment by rhdelima** [comment]
@rodrigopavezi @designhorf Not sure how to test this. Can you give additional details?
