### ISSUE TITLE
Wyre Technical Design

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#1053]
https://confluence.kyc-chain.com/display/SEL/Wyre+Integration

**Comment by CortecKYC** [comment]
@rodrigopavezi Is this issue on hold?

**Comment by CortecKYC** [comment]
Waiting for Wyre to reply regarding the integration with their KYC and LWS

**Comment by CortecKYC** [comment]
Not implementing for now.
