### ISSUE TITLE
Failed Tx has incorrect status on Transaction History

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1055]
Assumption: User has only 1 key with enough gas to send

Steps to replicate:
1. Open and unlock wallet
2. Send 1 key with a very low gas
3. Send 1 key again while first tx is not yet completed
4. Wait for both transactions to complete

Expected Result:
Second transaction is shown as failed on Transaction History

Actual Result:
Second transaction has status Sent with 0 key.

http://recordit.co/L1cvrpPzRh

**Comment by rhdelima** [comment]
Issue is blocked with https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1126

**Comment by rhdelima** [comment]
@eduardosmoura , Please update description when status failed. Should be 'Failed to send <ETH/KEY/token>'. See design https://projects.invisionapp.com/d/#/console/15222689/316491951/preview

![image](https://user-images.githubusercontent.com/10294014/56857239-97425700-699d-11e9-9840-8ed6433870e0.png)

**Comment by eduardosmoura** [comment]
Will do @rhdelima, good catch!

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/57069372-0b1a9180-6d07-11e9-8127-7f0216b29d08.png)
