### ISSUE TITLE
DID - Add ability to create DID in Selfkey ID

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1060]
As a user
I want to be able to create a DID from my Selfkey ID screen
So that registering for DID could be done on demand

**Comment by rhdelima** [comment]
Please see issues below:
1. Fix spelling and make description in a single line if possible
![image](https://user-images.githubusercontent.com/10294014/57356617-7cdd5a00-71a3-11e9-907d-96625145a6c6.png)

2. Get DID and I HAVE ONE button shows a blank screen - http://recordit.co/6yZUs01VFh

**Comment by rhdelima** [comment]
Looks good. Pass
