### ISSUE TITLE
Error when navigating to exchanges marketplace

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1088]
Steps to replicate:
1. Open and unlock wallet
2. Navigate to Menu > Marketplace > Exchanges

Expected Result:
Exchanges marketplace screen is displayed

Actual Result:
Error is displayed

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/3befd41a-15e7-4b6e-8881-738ce24485aa)

Build: 
https://console.cloud.google.com/storage/browser/selfkey-builds/dev/2019.04.17.07/?project=kycchain-master&pli=1

**Comment by andregoncalves** [comment]
@designhorf I believe this is caused by the warningIcon issue, is the fix merged to dev?

**Comment by designhorf** [comment]
@andregoncalves @rhdelima sorry, I missed this message. Fix was merged on Thursday.

**Comment by eduardosmoura** [comment]
@rhdelima please try to test it again with the new dev version. It should be fixed by now.

**Comment by rhdelima** [comment]
Issue is no longer encountered. Pass
