### ISSUE TITLE
Create template configuration on airtable for exchanges 

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#1090]

**Comment by rodrigopavezi** [comment]
@sk91 this is also done right?

**Comment by eduardosmoura** [comment]
@rodrigopavezi and @sk91 I just used the same settings from Cryptokart for all exchanges as we don't know at this moment which templateId each exchange will use in the future. 

Please review: https://airtable.com/tbl2pfBA34gw0F4wI/viwis9g5M0Hr043On?blocks=hide

**Comment by andregoncalves** [comment]
@sk91 @rodrigopavezi We should probably make this a common standard for all the marketplaces API (I mean the relying_party_config column). As a counter-argument, Flag Theory airtables are edited by non-technical staff, and I fear they may break the json by mistake.

**Comment by sk91** [comment]
this is fixed by the new scheduler, closing
