### ISSUE TITLE
Update exchanges details UI 

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#1093]

**Comment by rhdelima** [comment]
@designhorf Not sure what changes you made on this. Can you share it? Thanks!

**Comment by oanamangiurea** [comment]
Reopening this one as we have the following things that still need fixing: 

1. [ ] If I click on View all details large button the text above gets justified -> https://gyazo.com/36ac911d8d8fa6d0543d609c2610b6a9 vs https://gyazo.com/b80bc0ea92c294db53190cd7c5b42788 This shouldn't happen/ It should remain left aligned
2. [ ] The Exchange Hilights text should have same font size https://gyazo.com/21981c95835acf64e1d07e0f2a277b7d - what is on the left is bold, but should be same size. Even better, this can be replace with definition list, as we already have that styled nicely 
3. [ ] Button View all details -> style should be as for  Shell Secondary type https://gyazo.com/bb5ab0c6bd87475bf48430a8af19c397 meaning on hover it doesn't get a blue border

**Comment by rhdelima** [comment]
@designhorf ,

Can we hide View Details if details is short? Please see recording. 
http://recordit.co/6X3IbxJbQ2

Thanks!

**Comment by CortecKYC** [comment]
@designhorf ^^

**Comment by designhorf** [comment]
@rhdelima Yes, we can

**Comment by designhorf** [comment]
@rhdelima I'll create a separate task for it.

**Comment by rhdelima** [comment]
Closing this one. Another task is already created to address the View Details
