### ISSUE TITLE
Show KYC requirements based on single template

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#1096]

**Comment by sk91** [comment]
@rhdelima @andregoncalves @CortecKYC anyone knows what is this task about?

**Comment by CortecKYC** [comment]
@sk91 I have no idea. Including one simple line in the description could have been very helpful

**Comment by andregoncalves** [comment]
No idea, this is sprint 13, so it's probably related to exchanges.
