### ISSUE TITLE
Redirect to kyc for additional requirements

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#1099]

**Comment by andregoncalves** [comment]
renderer/marketplace/services/service-details.jsx line 238 is where the external URL should be triggered.

**Comment by rodrigopavezi** [comment]
@andregoncalves just pushed the change here https://github.com/SelfKeyFoundation/Identity-Wallet/pull/1122

**Comment by andregoncalves** [comment]
Yeah, I saw it after I commented it. :)
