### ISSUE TITLE
Redirect user to exchange login

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#1100]
https://projects.invisionapp.com/d/#/console/15222689/347983088/preview

**Comment by andregoncalves** [comment]
renderer/marketplace/services/service-details.jsx line 243 is where the external URL should be triggered.

**Comment by rhdelima** [comment]
Blocked by https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1138

**Comment by sk91** [comment]
@andregoncalves this does not seem to be done, any idea why it is in QA?

**Comment by andregoncalves** [comment]
Can't remember...I think this is related to a task to send the user to the exchange sign in page on an external browser.
