### ISSUE TITLE
Transaction in History is only displayed when it is completed. So Sending/Receiving status won't be shown.

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#1102]

**Comment by rhdelima** [comment]
Looks good. See sample screenshots.

![image](https://user-images.githubusercontent.com/10294014/59668497-325fec00-91eb-11e9-8cd9-4e66345e81c1.png)

![image](https://user-images.githubusercontent.com/10294014/59668699-836fe000-91eb-11e9-9e0c-ed3352122509.png)

![image](https://user-images.githubusercontent.com/10294014/59671125-ae5c3300-91ef-11e9-8b6a-26893c6fe749.png)
