### ISSUE TITLE
Exchanges Listing UI Fixes

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1116]
In the Exchanges Marketplace listing page (https://gyazo.com/082cd96540f728f3a0654d684dae3949?token=71bc106cfe9ac7da1eba3ac786b94063), we need to fix the following:

- [x] Change icon from unlock marketplace button with the one provided in design  
- [x] "Details" links https://gyazo.com/d2b7b67d58af489da597c57d3f993323 from table should be style as in design. Coming soon status can remain as it is
- [x] Excluded residents countries https://gyazo.com/cd092a4f943ba4baa4fb6dab42f7ab2b, style as in design (not using the tag style) - separate Countries with commas

**Comment by rhdelima** [comment]
@oanamangiurea 
Looks good on my end. Let me know if you're good with this as well.

![image](https://user-images.githubusercontent.com/10294014/56940617-1cff0780-6b42-11e9-8af5-13a738cbde72.png)

**Comment by oanamangiurea** [comment]
@rhdelima all good from me as well, can close the issue
