### ISSUE TITLE
Unable to send KEY if Gas limit has decimals

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1126]
See log.

[https://app.zenhub.com/files/105664964/d928fc83-46a4-4ca1-a2bd-1e0aea455755/download](https://app.zenhub.com/files/105664964/d928fc83-46a4-4ca1-a2bd-1e0aea455755/download)

**Comment by rodrigopavezi** [comment]
@rhdelima you should be able to test this on the release build. cheers

**Comment by rhdelima** [comment]
Looks good. Pass
