### ISSUE TITLE
Remove extra icons from KYC requirements 

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1130]
Remove upload icon from the KYC Requirements area in the marketplace applications. The one that shows on the right side of not yet filled attributes. -> https://gyazo.com/876e0937af87fefb3639f84432a782a9 

It hasn't been in the latest designs for  few months now.

**Comment by rhdelima** [comment]
Looks good. Document icon is no longer displayed.

![image](https://user-images.githubusercontent.com/10294014/57070404-de1bae00-6d09-11e9-84d7-43d74a8d0579.png)
