### ISSUE TITLE
Required field is not marked 

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1131]
When uploading a passport or national ID Selfie it's not marked as required (*) but error message says otherwise https://gyazo.com/15a480e931ad1877da335c13a739c2e7 

This happened before

**Comment by rhdelima** [comment]
@eduardosmoura Required mark (*) is still missing

![image](https://user-images.githubusercontent.com/10294014/57355696-2f5fed80-71a1-11e9-8e6c-8cde7f85f9bd.png)

**Comment by eduardosmoura** [comment]
@rhdelima I will check the UI components versions now. It looks like they are not right. Sorry about that.

**Comment by rhdelima** [comment]
This is not yet fixed so failing this one.

**Comment by eduardosmoura** [comment]
@rhdelima Please wait for the latest dev branch build. It should be ready by 7/2. Also, please use **FORCE_UPDATE_ATTRIBUTES=true** env var will update attributes on startup even if cache not timed out yet.

**Comment by rhdelima** [comment]
Selfie field is now marked as required. Pass

![image](https://user-images.githubusercontent.com/10294014/60583971-958e7880-9dbe-11e9-90ff-53c82d8914f7.png)
