### ISSUE TITLE
Fix inconsistent buttons

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1133]
We have a few buttons in the app that are inconsistent in terms of size and font-size. They should be fixed, make sure they use the already defined ones in the Selfkey UI, and follow the design.

What I found so far:

- [x] For all buttons -> Add letter-spacing: 0.6px as it was in original design (especially because on how poor Lato renders on retina displays) 
- [x] For all buttons -> change min-width to 120px instead of 200px
- [x] Transaction modal buttons https://gyazo.com/e2af75ddd8fbbb743c4dd08acb48749c - font size is incorrect -> should be 16px
- [x] Pending Key Deposit button -> https://gyazo.com/6138de1d09993f58e1c151a10ab438ad -> please style the icon as in the design https://projects.invisionapp.com/d/main#/console/15222689/347983074/preview and space it from the text 
- [x] Buttons text are not vertically aligned -> https://gyazo.com/428457e05c52c535159a1260f469f2f9 Fix: add line height on the that has the text inside the buttons. Please check all buttons for this issue

**Comment by CortecKYC** [comment]
@designhorf Can you please estimate this issue?

**Comment by designhorf** [comment]
@CortecKYC sure, I'll add an estimation soon
