### ISSUE TITLE
Transaction Modals Bugs

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1134]
1. When unlocking the exchanges marketplace -> transaction modal https://gyazo.com/ac7ac851a5437199256d0b8cb4041f13 

  - Modal is missing title. Should be "Unlock This Marketplace: Crypto Exchanges"
  - Wrong validation for checkbox, it shows with red even if I clicked it 

2. https://gyazo.com/d6aace1af3f44026d9918b4733a16f85 transaction pending modal missing title. Should be "KEY Deposit"

3.

**Comment by rhdelima** [comment]
Looks good.
