### ISSUE TITLE
Staking Issues

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1138]
1. Two transactions created after staking
2. Key balance is not updated real-time after staking and returning deposit
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/aa41af76-c6f7-49a0-b643-2133c337236f)

3. Should display KEY deposit modal when staking (https://projects.invisionapp.com/d/#/console/15222689/347983082/preview) when staking

4. Sign Up button is still disabled after staking. http://recordit.co/RVINDTKC1D

**Comment by CortecKYC** [comment]
@rodrigopavezi If we are removing staking, is this ticket necessary any more? Can we close it?

**Comment by rodrigopavezi** [comment]
@CortecKYC yeap, closing it.
