### ISSUE TITLE
Default hover state for icons

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1150]
White color for hover state

**Comment by designhorf** [comment]
@rhdelima for testing. All of the action icons need to be turn white color when mouse hover.

**Comment by rhdelima** [comment]
@designhorf , Do you mean this one?

![image](https://user-images.githubusercontent.com/10294014/57360377-8f0fc600-71ac-11e9-8ebd-a28f66fc4409.png)

**Comment by designhorf** [comment]
@rhdelima no, I mean, icons. On your screenshot, in the `ACTION` column eg. edit icon. Or in the dashboard, `gear icon`, `transfer icon`, `refresh icon`.
<img width="1167" alt="Screenshot 2019-05-14 at 10 10 02" src="https://user-images.githubusercontent.com/7461010/57681691-7d0ca800-7630-11e9-9c83-b73613e266ed.png">

**Comment by rhdelima** [comment]
Looks good. Pass
