### ISSUE TITLE
Linear gradient background to body

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1161]
Eg. if we have an empty table, background is ugly. 
Need to add `linear-gradient` background property to `body` instead of inside div.

![Screenshot 2019-05-07 at 08.43.52.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/7bc3ce72-c1e7-4443-8736-a10b2ed64798)

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/57353682-db9ed580-719b-11e9-8ddf-7ad7183cb3a7.png)
