### ISSUE TITLE
Fix Loading Screen when wallet starts

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1162]
After the refactor to React we lost the nice loading screen that we had. https://projects.invisionapp.com/d/main#/console/15222689/316491402/preview & https://projects.invisionapp.com/d/main#/console/15222689/316491403/preview t was displaying our logo and had some animated background. 

Now all we get is a white page for a few seconds, almost looks broken. You can see recording https://www.loom.com/share/7a4809360e0d467eafb9588c97db2ca8

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/58474751-9e1bdf80-817e-11e9-9dca-15170f83bd12.png)
