### ISSUE TITLE
Receive modal functions

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1165]
Some icons are missing from this modal
https://projects.invisionapp.com/d/main#/console/15222689/316491968/preview

**Comment by rhdelima** [comment]
@designhorf Can you confirm if your fix was merged correctly since I can't find it on the latest build on dev (dev_2019.06.07.16)

![image](https://user-images.githubusercontent.com/10294014/59146754-a39de300-8a24-11e9-8489-2606919c7b65.png)

**Comment by designhorf** [comment]
@rhdelima I've checked it and merged. Could you have a look at it again? Thanks

**Comment by rhdelima** [comment]
As confirmed by @designhorf , share icon is not implemented. Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/60489266-7ddbc500-9cd6-11e9-85fb-a24d4966d3d6.png)
