### ISSUE TITLE
Inconsistent input styles in error state

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1169]
Need to change all of the required inputs style in error state.

Current version:
![incosistent-inputs.jpg](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/dc883bd7-4ad7-4999-a5ae-946cda31e603)

**Comment by rhdelima** [comment]
@designhorf Missed one.

![image](https://user-images.githubusercontent.com/10294014/58020536-fd547100-7b3a-11e9-837e-6668f5d9e9ec.png)

**Comment by CortecKYC** [comment]
@designhorf This ticket was incomplete. It didn't pass QA, please take a look

**Comment by CortecKYC** [comment]
@designhorf Please, see above ^^

**Comment by designhorf** [comment]
@CortecKYC I'll fix it soon

**Comment by maycon-mello** [comment]
I've created a PR in the selfkey-ui https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1169

**Comment by maycon-mello** [comment]
I've created a PR in the react-jsonschema-form-material-theme repo https://github.com/SelfKeyFoundation/react-jsonschema-form-material-theme/pull/37

**Comment by rhdelima** [comment]
Looks good. Pass
