### ISSUE TITLE
Horizontal line position on Marketplace

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1178]
Before:
<img width="1275" alt="Screenshot 2019-05-14 at 16 52 28" src="https://user-images.githubusercontent.com/7461010/57707965-cd076100-7668-11e9-8a6d-b9b09fd8d6cc.png">

After: 
<img width="1268" alt="Screenshot 2019-05-14 at 16 42 57" src="https://user-images.githubusercontent.com/7461010/57708012-e5777b80-7668-11e9-805c-766ff91b292a.png">

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/58010297-aa6ebf80-7b22-11e9-99ea-02b602ddc919.png)
