### ISSUE TITLE
Exchanges table content consistency 

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1189]
In the exchanges listing https://gyazo.com/5eb06f3b31f7fc48790f38d6908f968b, we have 2 ways of displaying content that is not available. One is we display a line "-" for others we say "not available". Need to have consistency, and to make the table more easily to be scanned, change the not available to a line "-"

**Comment by rhdelima** [comment]
Looks good. Pass
