### ISSUE TITLE
BAM: Browse Marketplace offers

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1193]
**Feature**: Browse Bank Accounts Marketplace

**Background**: Given user has opened SelfKey wallet
And the user has opened the Bank Accounts Marketplace Screen

**Scenario**: Bank accounts data has loaded
When bank accounts data has loaded
Then user sees a table with information on each jurisdiction (Type, Interest, Min Deposit, Fiat, Remote, Fee). 

Invision: https://projects.invisionapp.com/d/main#/console/15222689/320819838/preview

- [x] develop components
- [ ] develop containers

**Comment by rhdelima** [comment]
Looks good. Minor issues will be log on separate ticket

![image](https://user-images.githubusercontent.com/10294014/59146458-f4abd800-8a20-11e9-936e-f9c93ff31795.png)
