### ISSUE TITLE
BAM: Filter Account Type in Marketplace Listing Table

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1194]
**Feature**: Browse Bank Accounts Marketplace

**Background**: Given user has opened SelfKey wallet
And the user has opened the Bank Accounts Marketplace Screen

**Scenario**: Filter programs by Type
Given bank accounts data has loaded
When user clicks one of the top tab options (Personal, Corporate, Private)
Then bank accounts list is updated showing only offers for that specific type

Invision: https://projects.invisionapp.com/d/main#/console/15222689/320819838/preview

**Comment by andregoncalves** [comment]
See #1230

**Comment by rhdelima** [comment]
Reopening this one. Based on design, there should be 3 tabs (Personal Accounts, Corporate Accounts and Private Banking). On the wallet, Corporate Accounts tab is displayed first and Private Banking is renamed to Wealth Management

![image](https://user-images.githubusercontent.com/10294014/59483854-e129c280-8ea1-11e9-9ccd-3e91adb9857d.png)

**Comment by andregoncalves** [comment]
After speaking with Marc at FT, we decided that it's best to name this tab "Wealth Management" instead of "Private Banking"

**Comment by rhdelima** [comment]
Looks good. Pass
