### ISSUE TITLE
BAM: Activate Bank Accounts option in SK Marketplace

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1195]
**Feature**: Browse Bank Accounts Marketplace

**Background**: Given user has opened SelfKey wallet
And the user has opened the SK Marketplace Screen

When the user clicks the bank accounts option
Then the bank accounts marketplace listing page should be displayed

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/59187884-04562880-8ba9-11e9-9365-3211ed5e64d2.png)
