### ISSUE TITLE
BAM: Display bank accounts jurisdiction Account Types

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1196]
**Feature**: Browse Bank Accounts Marketplace

**Background**: Given user has opened SelfKey wallet
And the user has opened the Bank Accounts Marketplace Screen

**Scenario**: Open Specific Jurisdiction Screen
When user clicks the "Details" button on the last column
Then the jurisdiction detailed screen is displayed
And information on fees, and banking option is displayed
And default "Account Types" tab is opened

Invision: https://projects.invisionapp.com/d/main#/console/15222689/320819839/preview

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/59145920-160ac500-8a1d-11e9-840d-d3af2addd9cc.png)
