### ISSUE TITLE
BAM: Display detail jurisdiction country details

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1198]
**Feature**: View bank accounts jurisdiction

**Scenario**: Browse detailed jurisdiction country details
Given Given jurisdiction detailed screen screen is opened
When "Country Details" tab is clicked
Then it should display the selected country details from airtable

Note: country details is loaded from a different API call.
UI should be similar to incorporations marketplace

**Comment by rhdelima** [comment]
Looks good. Pass
