### ISSUE TITLE
BAM: Display 1st stage KYC requirements

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1200]
**Feature**: View bank accounts jurisdiction

**Background**: Given user has opened SelfKey wallet
And the user has opened the Bank Accounts Marketplace Screen

**Scenario**: KYC requirements display
Given Given jurisdiction detailed screen screen is opened
Then a list will be displayed at the bottom with all the required 1st stage KYC documents and attributes
And visually indicate which ones are missing from the user Selfkey ID

**Comment by rhdelima** [comment]
Failing this one. KYC requirements are not displaying. Keeps on showing the loading icon

![image](https://user-images.githubusercontent.com/10294014/59186988-e4be0080-8ba6-11e9-94ba-50a8bbca8214.png)

**Comment by andregoncalves** [comment]
@rhdelima can you please confirm this is still happening and if so which build.

**Comment by rhdelima** [comment]
@andregoncalves Encountered the issue on the latest dev build (2019.06.11.17).

**Comment by andregoncalves** [comment]
Template(s) was missing on FT KYC-Chain production instance.
There is now a generic template to facilitate testing.
It's ready for QA again.

**Comment by rhdelima** [comment]
@andregoncalves Still not showing the list of requirements. See recording and log http://recordit.co/j87RT1DueR

![image](https://user-images.githubusercontent.com/10294014/59666834-35a5a880-91e8-11e9-9f70-06cc6a4f2acc.png)

**Comment by andregoncalves** [comment]
Can you try again @rhdelima ?
Latest dev build seems to work fine for me.

![Screen Shot 2019-06-25 at 09.26.10.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/5136bf5b-91a5-41e5-9f77-857aab708eec)

**Comment by rhdelima** [comment]
Looks good now. Pass

![image](https://user-images.githubusercontent.com/10294014/60136645-57e68a00-97d7-11e9-83c9-1c3dcb74622b.png)
