### ISSUE TITLE
BAM: Display 2nd stage KYC requirements in bank option expand box

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1201]
**Feature**: View bank accounts jurisdiction

**Background**: Given user has opened SelfKey wallet
And the user has opened the Bank Accounts Marketplace Screen

**Scenario**: Browse bank options
Given Given jurisdiction detailed screen screen is opened and Account Types is selected
When user clicks each bank option expand box
Then it should display each option details without the specific bank name
And should display 2nd stage KYC requirements (text from airtable)

Invision: https://projects.invisionapp.com/d/main#/console/15222689/320819839/preview

**Comment by andregoncalves** [comment]
Airtable text is still missing.

**Comment by CortecKYC** [comment]
@andregoncalves Any updates on the airtable text? Is it still missing or is this QA-ready?

**Comment by andregoncalves** [comment]
It's QA-Ready but the data is still missing, this additional requirements are bank specific and sometimes varies between users.
So the plan for now is to show this generic message:

![Screen Shot 2019-07-12 at 09 07 42](https://user-images.githubusercontent.com/1074/61112845-b58bff00-a484-11e9-903c-399dd7e0a397.png)

And if data is available on airtable for that specific bank, it will replace this message.

**Comment by CortecKYC** [comment]
@andregoncalves Looks good. Let's try and simplify everything we can simplify in order to release. I will create a doc on Confluence with anything that we need to scope out now so we can revisit it at a later time

**Comment by andregoncalves** [comment]
This is feature complete.
If data later on shows up on airtable, wallet will automatically show it.

**Comment by rhdelima** [comment]
Looks good. Pass
