### ISSUE TITLE
BAM: Display existing application Status and Actions

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1202]
**Feature**: View bank accounts jurisdiction

**Background**: Given user has opened SelfKey wallet
And the user has opened the Bank Accounts Marketplace Screen

**Scenario**: User application to the jurisdiction is in progress
Given jurisdiction detailed screen screen is opened
And user has an existing application in progress for that jurisdiction
Then "Open Bank Account" button is disabled
And an information top level bar indicates an application is in progress and displays a link to Manage Applications screen
And the selected bank options is highlighted

**Scenario**: User application to the jurisdiction was rejected
Given jurisdiction detailed screen screen is opened
And user has an existing rejected application that jurisdiction
And an information top level bar indicates a previous application was rejected and displays a link to Manage Applications screen
And the selected bank options is highlighted

**Scenario**: User application to the jurisdiction has been accepted
Given Given jurisdiction detailed screen screen is opened
And user has an existing application was accepted for that jurisdiction
Then "Open Bank Account" button is disabled
And an information top level bar indicates a previous application was accepted and displays a link to Manage Applications screen
And the selected bank options is highlighted

**Comment by andregoncalves** [comment]
Bypassing manage applications for now.

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/61240270-60493980-a773-11e9-9121-d48a83545892.png)


![image](https://user-images.githubusercontent.com/10294014/61240032-d8632f80-a772-11e9-8506-530868ad13c2.png)

![image](https://user-images.githubusercontent.com/10294014/61241105-6cce9180-a775-11e9-802a-c093952e1031.png)
