### ISSUE TITLE
BAM: Apply to Bank Account Cost Detail Screen

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1203]
**Feature**: Apply to Bank Accounts

**Background**: Given user has opened SelfKey wallet
And the user has opened the Bank Accounts Marketplace Screen
And the user has opened a specific jurisdiction option

Scenario: Start application
Given Given jurisdiction detailed screen screen is opened
And "Open Bank Account" button is not disabled
When user clicks the "Open Bank Account" button
Then a confirmation and process information screen is displayed
And cost and network fee is displayed

Invision: https://projects.invisionapp.com/d/main#/console/15222689/361135235/preview

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/60584568-30d41d80-9dc0-11e9-9600-d04f40c67898.png)
![image](https://user-images.githubusercontent.com/10294014/60584592-3d587600-9dc0-11e9-9174-6b0c8cf37ca5.png)
