### ISSUE TITLE
BAM: Apply to Bank Account choose bank option

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1206]
**Feature**: Apply to Bank Accounts

**Background**: Given user has opened SelfKey wallet
And the user has opened the Bank Accounts Marketplace Screen
And the user has opened a specific jurisdiction option

**Scenario**: Payment transaction has succeeded
Given the payment transaction for bank accounts has succeeded
Then the choose bank option screen is displayed
And a list of possible bank options with details and bank names is displayed to the user

Invision: https://projects.invisionapp.com/d/main#/console/15222689/361135236/preview

**Comment by rhdelima** [comment]
Looks good. Pass
