### ISSUE TITLE
BAM: Apply for bank account 1st stage KYC requirements

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1207]
**Feature**: Apply to Bank Accounts

**Background**: Given user has opened SelfKey wallet
And the user has opened the Bank Accounts Marketplace Screen
And the user has opened a specific jurisdiction option

**Scenario**: 1st stage KYC requirements
Given all the 1st stage KYC requirements are completed
And user has accepted the terms and services
When user completes the Payment
Then the KYC-Chain process is initiated
And the user is shown a list to select a preferred bank option

**Scenario**: Select bank option
Given the user has fullfilled 1st stage KYC Requirements
And the user has paid for the application
When user selects his preferred bank option
Then the KYC process is updated with question answer
And the bank accounts application is in progress information modal is displayed
And a link to the "Manage Applications" screen is displayed

**Comment by rhdelima** [comment]
There are issues when paying BAM applications but logged on different ticket. Closing this one.
