### ISSUE TITLE
BAM: Bank Account preferred option is missing 

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1208]
**Feature**: Apply to Bank Accounts

**Background**: Given user has opened SelfKey wallet
And the user has opened the Bank Accounts Marketplace Screen
And the user has opened a specific jurisdiction option

**Scenario**: Application was initiated, paid but no preferred bank account was selected
Given Given jurisdiction detailed screen screen is opened
And an existing pending application without payment exists
Then the "Open Bank account" button is replaced with "Continue Application"
When user clicks the "Continue Application" button
Then the choose bank option screen is displayed
And a list of possible bank options with details and bank names is displayed to the user

(the same info should also be displayed on the manage applications screen)

**Comment by rhdelima** [comment]
Failing this one. Choose bank account option is not shown and shows `Waiting for answers ` on instance.

![image](https://user-images.githubusercontent.com/10294014/61208270-95309e80-a729-11e9-9eb2-8b93ae4b21c8.png)

**Comment by andregoncalves** [comment]
This is probably related to #1426 , the select bank screen is not shown.

**Comment by sk91** [comment]
should be fixed by #1409 @rhdelima please verify

**Comment by andregoncalves** [comment]
Yes, payment contract is now being bypassed.
Can you please test again @rhdelima.

**Comment by rhdelima** [comment]
Looks good now. Pass
