### ISSUE TITLE
BAM: Bank Account Application 1st stage KYC requirements not fullfilled

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1209]
**Feature**: Apply to Bank Accounts

**Background**: Given user has opened SelfKey wallet
And the user has opened the Bank Accounts Marketplace Screen
And the user has opened a specific jurisdiction option

**Scenario**: Application was initiated, paid but 1st stage KYC requirements were not fullfilled
Given jurisdiction detailed screen screen is opened
And an existing pending application with missing 1st stage KYC requirements exist
Then the "Open Bank account" button is replaced with "Continue Application"
When user clicks the "Continue Application" button
Then the 1st stage KYC requirements screen is displayed
And a list of necessary attributes and documents is displayed

(the same info should also be displayed on the manage applications screen)

This is related to handling of the *additional documents required* status from KYC-Chain API (status 9?)
When in that status, manage applications should either:
1- Link to kyc requirements screen with *only* the additional requirement
2- Link to KYC-Chain onboarding app if the requirement cannot be met by the wallet

**Comment by rhdelima** [comment]
Looks good. Pass
