### ISSUE TITLE
BAM: Bank Account Application 2nd Stage KYC requirements

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1210]
**Feature**: Apply to Bank Accounts

**Background**: Given user has opened SelfKey wallet
And the user has opened the Bank Accounts Marketplace Screen
And the user has opened a specific jurisdiction option

**Scenario**: Additional Requirements needed
Given jurisdiction detailed screen screen is opened
And an existing pending application with **additional** KYC requirements exist
Then the "Open Bank account" button is replaced with "Complete the Application - Additional Requirements Needed" (Oana)
When user clicks the "Complete Application" button
Then the KYC requirements upload screen is displayed showing *only* the additional requirements
And if re-uploading, the same document/attribute is not accepted

The button labeled "Complete Application") should show up on both Manage Applications Screen and on the jurisdiction detail screen of BAM.

Also, the SK KYC requirements screen should only show up if the additional requirement can be fulfilled by the wallet (an Identity attribute), otherwise the button should be a link to KYC-Chain web app.

**Subtasks:**

 - [ x ] Show Additional Requirements on KYC checklist
 - [ x ] Redirect to KYCC to complete requirements with auto-login

**Comment by rhdelima** [comment]
Looks good. Pass
