### ISSUE TITLE
BAM: e2e tests

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1212]
- Test logging in to KYC-Chain via email with LWS
- Test logging in to KYC-Chain via email with JWT embedded token
- Test logging in to KYC-Chain directly from the wallet if applications status requires it.
- Test fulfilling additional KYC requirements on the wallet
- Test fulfilling additional KYC requirements on KYC-Chain onboarding app

(WIP)

**Comment by rhdelima** [comment]
@andregoncalves @CortecKYC Can we close this one? I'm not sure if I have an action required on this.

**Comment by andregoncalves** [comment]
@eduardosmoura ?

**Comment by eduardosmoura** [comment]
Yes, I think you can close it @rhdelima. These are automated e2e tests for the wallet build, considering a few BAM test scenarios, so you don't need to check them all over again.
