### ISSUE TITLE
BAM - Show Additional Requirements on KYC checklist 

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#1213]
As a wallet,
When KYC relying party informs an additional requirement is needed
Then KYC requirements screen showing only the additional requirement(s) is displayed
And when submitting the application is updated

Further details:
If an additional requirement is set for the application, a button to fullfill those requirements (labeled "Complete Application") should show up on both Manage Applications Screen and on the jurisdiction detail screen of BAM.

Also, this screen should only show up if the additional requirement can be fullfilled by the wallet (an Identity attribute), otherwise the button should be a link to KYC-Chain web app.

**Comment by andregoncalves** [comment]
@rodrigopavezi  I think this card doesn't belong to this sprint...
The idea is to tackle the submit application on the next sprint.

**Comment by andregoncalves** [comment]
Closing this issue. It was part of #1210, and is now a subtask of that issue
