### ISSUE TITLE
BAM - Redirect to KYC for fulfilling other requirements

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#1215]
As a wallet,
When KYC relying party informs an additional requirement is needed
And the requirement cannot be fulfilled directly from the wallet
Then a link to KYC-Chain onboarding app is provided with auto-login

**Comment by andregoncalves** [comment]
Closing this task, it's part of #1210 and I created a subtask for it.
