### ISSUE TITLE
BAM - icons

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1218]
Add new icons to Selfkey UI

**Comment by rhdelima** [comment]
@designhorf Can you confirm the icons you did here?

**Comment by designhorf** [comment]
@rhdelima `MoneyIcon` and `BankIcon`
<img width="204" alt="Screenshot 2019-06-13 at 06 53 21" src="https://user-images.githubusercontent.com/7461010/59404740-fde1cf80-8da7-11e9-94be-8efe7c748584.png">
<img width="200" alt="Screenshot 2019-06-13 at 06 53 33" src="https://user-images.githubusercontent.com/7461010/59404741-fe7a6600-8da7-11e9-9239-8504d15fce72.png">

**Comment by rhdelima** [comment]
Looks good. Pass
