### ISSUE TITLE
Simplify Flows

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1223]
Some steps in the wallet make little to no sense, and just adds to the interaction user has to perform to get things done. So, we are going to get rid of the following screens:

- [ ] 1: 1st screen when creating a Selfkey ID - https://gyazo.com/ac552ad3d187f738fb6a049a13b3bf54 - no need of it, after we're no longer accepting those who took part in the ICO
- [x] 2: About the Selfkey Identity Wallet https://gyazo.com/7cab939a078858e2e3c70d59a65bac9d
- [x] 3:  What are ID attributes & documents https://gyazo.com/8a395ec774fa4db1a5890c93526c121e
- [x] 4:  Are you sure you want to close modal https://gyazo.com/228483a9bd5e632dc96eccf7818b80f5 - the app should just close when the user wants to, no need for confirmation

**Comment by oanamangiurea** [comment]
Only 4 still remaining

**Comment by sk91** [comment]
@oanamangiurea step 4 done

**Comment by oanamangiurea** [comment]
@sk91 my bad, I just rechecked the other 3 as well, they are still there, and should be removed as well

**Comment by sk91** [comment]
@oanamangiurea @designhorf moved back to issues

**Comment by rhdelima** [comment]
Looks good. Pass
