### ISSUE TITLE
Error when opening Bank Accounts marketplace

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1246]
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/27bbfe1a-1ee6-4d71-9295-466b4e302ee0)

**Comment by CortecKYC** [comment]
This ticket needs estimation

**Comment by andregoncalves** [comment]
This was caused by an issue with airtable data.
It should be working now after the correction.

**Comment by rhdelima** [comment]
Looks good with latest build. Pass
