### ISSUE TITLE
Manage Marketplace Applications issues

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1265]
1. When user unlocks wallet via hardware, user needs to authenticate first before user can open Selfkey ID. Also, after authenticating, user is redirected to Marketplace Applications tab instead of SelfKey ID dashboard. http://recordit.co/iWBADJ6ilp

2. Unable to close authentication modal if not confirmed.
http://recordit.co/cq0F8qUJaa

3. Unpaid applications should still be displayed under Marketplace Applications
http://recordit.co/iWBADJ6ilp

**Comment by eduardosmoura** [comment]
Dev test evidence: http://recordit.co/YQ0lr5BdIh

**Comment by rhdelima** [comment]
@eduardosmoura Please try it using a hardware wallet

**Comment by eduardosmoura** [comment]
@rhdelima, unfortunately, I don't have a hardware wallet to test it. 

@rodrigopavezi could you check that, please? 

I changed the config settings in order the fail the RP authentication and tried to reproduce the scenario.

**Comment by rhdelima** [comment]
Failing this one due to following issues:
1. When pointing to LIVE instance, authentication error is displayed.
![image](https://user-images.githubusercontent.com/10294014/58927677-218e8f80-8782-11e9-8f83-3a09dee1415c.png)

2. When pointing to TEST instance, confirm authentication modal is shown for 1-2 sec and then replaced with authentication modal
http://recordit.co/VkmCfuT0fI

**Comment by eduardosmoura** [comment]
@rodrigopavezi Could you help me checking the hardware wallet issues? I don't have any Trezor device.

**Comment by rhdelima** [comment]
Failing this one again. Here's what I observed:
**No DID associated yet**
1. When pointing to test instance, authentication via hardware wallet works
2. When pointing to LIVE instance, error authentication is encountered

**Comment by rhdelima** [comment]
Closing this one. Original issues were already fixed. A separate ticket was logged for other issue related to authentication.
