### ISSUE TITLE
BAM: Implement Payment Contract Screens

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1277]
Based on designs yet to be agreed

**Comment by andregoncalves** [comment]
@designhorf invision screen:
https://projects.invisionapp.com/d/main#/console/15222689/366885595/preview

**Comment by designhorf** [comment]
@andregoncalves I made it. 
- Pushed changes https://github.com/SelfKeyFoundation/Identity-Wallet/commits/feat/1277-BAM-payment-contract
- You can find the popup in the Wallet Storybook
