### ISSUE TITLE
BAM: UI fixes

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1278]
@designhorf can you please review the existing UI screens for BAM (on dev) and make any adjustments you see fit?

**Comment by designhorf** [comment]
@andregoncalves sure, I'll do it today.

**Comment by rhdelima** [comment]
@designhorf Can you provide some details on what you have fixed for this ticket? Thanks!

**Comment by designhorf** [comment]
@rhdelima you can find changes here -> https://github.com/SelfKeyFoundation/Identity-Wallet/pull/1288

**Comment by rhdelima** [comment]
Looks good. Pass
