### ISSUE TITLE
BAM: fix non-wrapping credit card list breaks layout

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1283]
![Screen Shot 2019-06-04 at 12.08.00.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/ee37f09b-c901-40ad-a42a-2161a16190de)

**Comment by rhdelima** [comment]
Looks good.

![image](https://user-images.githubusercontent.com/10294014/59146528-b4992500-8a21-11e9-987e-de0dd2dc4cf0.png)
