### ISSUE TITLE
Bank account selection layout breaks on small screen sizes

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1298]
![Screen Shot 2019-06-10 at 10.15.33.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/e72e5e56-bd7f-46f7-acf1-f29f017cf9ae)

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/61873982-c410f680-af19-11e9-86ae-3152f1b3df69.png)
