### ISSUE TITLE
Incorporation Marketplace: Error message "Email is already registered to another user" is no longer displayed when using an existing email

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1299]
When user use an email associated with submitted application, the error message "Email is already registered to another user" is no longer displayed on wallet, only on log.

Note that in the recording below, after clicking Submit button, 'Far Horizon Capital Inc' disappears.
http://recordit.co/zIkP8PRX1o

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/67b16532-7dfc-4491-9377-fb5a3d965a0c)

**Comment by rodrigopavezi** [comment]
@rhdelima which build is that happening?

**Comment by rhdelima** [comment]
@rodrigopavezi it's on both dev_2019.06.07.16 and release_2019.06.04.17

**Comment by andregoncalves** [comment]
@rhdelima I believe this is caused because you have existing applications with both did and eth authentication using the same email address.
can you please delete from the KYCC dev instance, all of the applications with the same email address not using DIDs and test again?

**Comment by rhdelima** [comment]
@andregoncalves This has been fixed and merged on release build. Saw it when I tested the release build. Also, it was a feature implemented that if an email address is already in used, wallet should display such error. Thanks! 

Closing this one.
