### ISSUE TITLE
Change button label

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1317]
In the marketplaces listing, please change the "Learn more" button from live marketplaces to "Access Marketplace" 

https://projects.invisionapp.com/d/main#/console/15222689/318479882/preview

**Comment by rhdelima** [comment]
Looks good now. Pass

![image](https://user-images.githubusercontent.com/10294014/59757813-2cd3d600-92bf-11e9-84b6-f0f1a24a4aca.png)
