### ISSUE TITLE
Send Transaction not working

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1318]
1. When changing Gas Price, Gas Limit is not updated
2. Send Tx always fails

http://recordit.co/JB6DD2BRQv
http://recordit.co/5ALTgQdQIU

build: release_2019.06.13.08

**Comment by rodrigopavezi** [comment]
Fixed on dev branch

**Comment by rhdelima** [comment]
Looks good. Pass
