### ISSUE TITLE
Marketplace Applications - Incorrect Payment Details

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1319]
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/0aaa46a2-9d46-44d4-9d30-6f064d06b106)

**Comment by maycon-mello** [comment]
This issue happens just with baking account applications, looks like payments are not created yet. For incorporations this is working fine.

@andregoncalves is the payment creation for banking accounts implemented?

**Comment by andregoncalves** [comment]
Probably not,
Please wait for #1205 to be completed and merged to dev before testing any further.
Thanks.

**Comment by rhdelima** [comment]
Failing this one. Note that the issue was original raised for Incorporations even if the user has paid for the payment. Issue still exists on the latest build.

![image](https://user-images.githubusercontent.com/10294014/61209619-d24a6000-a72c-11e9-9c11-d2bb879a2778.png)

**Comment by rhdelima** [comment]
Weird. Payment details for Incorporations are reflected on Bank Accounts application. 

![image](https://user-images.githubusercontent.com/10294014/61209845-674d5900-a72d-11e9-946e-07efa7a8a3fc.png)

**Comment by eduardosmoura** [comment]
@rhdelima could you send me your database file (IdentityWalletStorage.sqlite) please? I want to analyze it because the code looks correct.

**Comment by eduardosmoura** [comment]
@rhdelima could you check my last message please regarding the wallet database? Thanks.

**Comment by rhdelima** [comment]
@eduardosmoura Failing this one again. Looks good when user is using same wallet and did not delete the db. But failed when user is using a different machine. Please try attached keystore file and DID (0x6be1c3ae1d2f8884ab6a38139b04484b34c5db3e772badee67b428fa332073f0)

[MEW - UTC--2019-04-14T14-16-59.208Z--e96a6ddd164d6f9b7096aebed279361e423b520b.zip](https://github.com/SelfKeyFoundation/Identity-Wallet/files/3416346/MEW.-.UTC--2019-04-14T14-16-59.208Z--e96a6ddd164d6f9b7096aebed279361e423b520b.zip)

![image](https://user-images.githubusercontent.com/10294014/61617265-e9450100-ac9c-11e9-819b-45fd37d0219a.png)

**Comment by eduardosmoura** [comment]
@rhdelima what's the password to unlock the provided keystore file?

**Comment by rhdelima** [comment]
@eduardosmoura Apologies. please use `MyTest01!`

**Comment by rhdelima** [comment]
Looks good now. So, if user use another machine or has deleted DB, the payment details won't show up.

**Comment by andregoncalves** [comment]
Yes, transaction detailed info is not stored on chain, only on local db.
