### ISSUE TITLE
Incorporations Marketplace Refactor to use same architecture as Bank Accounts

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1321]
Refactor components using the same architecture as Bank Accounts. Create Storybook entries and rename components and folders. Extract common components to /marketplace/common.

**Comment by CortecKYC** [comment]
@maycon-mello Have you finished this card? If so, please move it to the next pipeline

**Comment by maycon-mello** [comment]
> @maycon-mello Have you finished this card? If so, please move it to the next pipeline

This is almost done. I'm applying some banking/accounts updates the team did on past days. I will submit the PR for review by the end of the day.

**Comment by andregoncalves** [comment]
@rhdelima we refactored the incorporations application flow with improvements we did for Bank Accounts. This requires a round QA to make sure we didn't break anything.

**Comment by rhdelima** [comment]
@andregoncalves A blank screen is displayed after submitting requirements.

![image](https://user-images.githubusercontent.com/10294014/62832571-4eb85c00-bc63-11e9-8a27-a8258a057c4f.png)

![image](https://user-images.githubusercontent.com/10294014/62832587-8d4e1680-bc63-11e9-93d7-8ef50e425f8f.png)

**Comment by andregoncalves** [comment]
I was able to reproduce it, it's related to the scheduler work that's not going into this release.
I'm working on a fix.
