### ISSUE TITLE
BAM: Bank Accounts Table listing UI Fixes

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1335]
- [x] 1. Table listing - Eligibility columns should display as normal table text, not as tags - follow design https://projects.invisionapp.com/d/main#/console/15222689/320819838/preview 
- [x] 2. Table listing - padding is too big for table cells, reduce to 0 20px
- [x] 3. Take out max-width: 200px from Good for column
- [x] 4. Personal Visit table header is missing tooltip as in design https://gyazo.com/06b116aba919c55106c51487da6fc4e2 

- [x] 5. Text under each tab is too big, correct style is Explanatory, not Explanatory Large - 13 px https://gyazo.com/756305d562fb73a9276856d5139d67fa

**Comment by rhdelima** [comment]
Looks good. Pass
