### ISSUE TITLE
BAM: Bank Account detailed page UI issues

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1338]
- [x] 1. Cards headers - line under title should not touch the borders of the card - follow same style we use everywhere https://gyazo.com/89cbcec586f2dbff2fa0b36680e81a38 
- [x] 2. Definitions lists spacing - we have margin-bottom 24px (correct) and then also margin-bottom from `<li>` https://gyazo.com/511d509934edf660853cd5781378dddd . Also why are we using lists and paragraphs for it, instead of the proper HTML tags `<dl>, <dt>, <dd>`?  This should be standard styling across wallet 
- [x] 3. Explanatory large text - correct is 18px with 28px line-height (should be same across wallet) - see Ui guidelines https://gyazo.com/b849e61144f07d8fa2328558a820afa9 
- [x] 4. Line height for this paragraph is wrong https://gyazo.com/49e50798073d95ed46dbfdc7ba16daa5 - not sure why it was overwritten in css
- [x] 5. Please use warning message styling as it is in the design for https://gyazo.com/da9752b9fa1a50ff33b47668820f4b21

**Comment by rhdelima** [comment]
Looks good. Pass
