### ISSUE TITLE
DID Buttons

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1339]
In User Profile:

1. Space between buttons is too big, should be same as we have in the entire app
2. Buttons should be larger - use normal size from Selfkey UI (same size as add information for example)

**Comment by rhdelima** [comment]
Looks good. Verified the following:
1. Distance between buttons are now closer similar with other buttons on the app
2. The size of the DID buttons are now correct with 44x height

![image](https://user-images.githubusercontent.com/10294014/60466003-10537880-9c85-11e9-98d2-2d763d886456.png)
