### ISSUE TITLE
Marketplace - connect data loaded with scheduler jobs to ui

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1345]
- [x] connect incorporations marketplace
- [x] connect bank accounts marketplace
- [x] connect exchanges marketplace

**Comment by rhdelima** [comment]
Waiting for the Exchanges.

**Comment by sk91** [comment]
@andregoncalves ^^

**Comment by andregoncalves** [comment]
@sk91 waiting for this refactor to be merged: https://github.com/SelfKeyFoundation/Identity-Wallet/pull/1695

**Comment by rhdelima** [comment]
Looks good. Pass
