### ISSUE TITLE
Connection error popup

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1349]
current version: 

correct one:
https://projects.invisionapp.com/d/main#/console/15222689/319048193/preview

**Comment by rhdelima** [comment]
@designhorf , Can you confirm if the OK button was intentionally removed? There is an OK button on the design.

![image](https://user-images.githubusercontent.com/10294014/60490214-aebcf980-9cd8-11e9-8ca4-bd402c90e958.png)

**Comment by designhorf** [comment]
@rhdelima This is a bug. We need the OK button. I'll check it later.

**Comment by rhdelima** [comment]
Thanks @designhorf . Reopening this one.

**Comment by rhdelima** [comment]
@eduardosmoura ,

When user hasn't logged in yet while no connection, after clicking Submit, it opens the wallet showing NaN values. Might be good if we close the wallet after clicking OK while no connection. What do you think @oanamangiurea ? or are we good with this?

![image](https://user-images.githubusercontent.com/10294014/61180804-ff284580-a64e-11e9-8185-93e9b9b42282.png)

![image](https://user-images.githubusercontent.com/10294014/61180962-b8881a80-a651-11e9-97de-0175bc0d2fe4.png)

**Comment by eduardosmoura** [comment]
@rhdelima I will do that.
