### ISSUE TITLE
Table UI issues

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1364]
1. All cell information in tables should be vertically centred - this one needs fixing https://gyazo.com/b4a0cb0574e2dff980faa451fc036f0d - see good for column
2. While checking what happens for the above issue, I notice something on td heights and paddings.
 - for the large table `<td>` should have min-height not height set at 74px
 - add `box-sizing: border-box` to it, so it won't be actually 104 instead of 74px
 - `vertical-align: middle` instead of inherit
 - all `<td>` cells should have padding 15px 20px
- I think we should also remove `display:flex` from `<td>` it makes no sense, when we use real tables and not divs, and because of it then we write extra css to fix stuff.

**Comment by rhdelima** [comment]
Looks good. Pass. See screenshots below.

![image](https://user-images.githubusercontent.com/10294014/60466387-16962480-9c86-11e9-895e-2babf8fb6a53.png)

![image](https://user-images.githubusercontent.com/10294014/60467014-f36c7480-9c87-11e9-9707-f6ad74db5368.png)
![image](https://user-images.githubusercontent.com/10294014/60467215-97562000-9c88-11e9-92c3-29d6f4afd099.png)
