### ISSUE TITLE
Table tooltip style 

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1365]
Tooltip in table header in bank accounts doesn't follow our guidelines 
https://gyazo.com/a23f823b06138ce66fe0592b921c06f8  vs https://projects.invisionapp.com/d/main#/console/15222689/320819838/preview

**Comment by rhdelima** [comment]
Looks good now. See sample screenshot

![image](https://user-images.githubusercontent.com/10294014/60584166-1c435580-9dbf-11e9-9b5a-254dd44bcaee.png)
