### ISSUE TITLE
Authentication Error when user doesn't authenticate the first visit on Marketplace Applications or Incorporate Now

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1367]
See recordings:
http://recordit.co/OVVosHgxGl
http://recordit.co/MXfDUeSadz

**Comment by andregoncalves** [comment]
@rhdelima prod or dev build?

**Comment by rhdelima** [comment]
@andregoncalves release build release_2019.06.26.14

**Comment by sk91** [comment]
@rhdelima This does not seem like a bug.

Once you click cancel/confirm on the device itself, the issue goes away.

Untill then or timeout it is stack on device level.

**Comment by andregoncalves** [comment]
This seems like the correct behaviour.
The cancel/confirm needs to be clicked on the device.

**Comment by rhdelima** [comment]
@andregoncalves @sk91 Sorry, I disagree. What's the purpose of Back button if user has to decline/confirm it on device. For me, clicking back button means declining transaction.

@CortecKYC Please confirm.

**Comment by CortecKYC** [comment]
@oanamangiurea Can you provide your feedback, please?

**Comment by oanamangiurea** [comment]
@andregoncalves @sk91 @rhdelima that screen was not supposed to have a back button, as per these designs https://projects.invisionapp.com/d/main#/console/15222689/318418737/preview

**Comment by CortecKYC** [comment]
No button makes total sense.
@andregoncalves @sk91 please change it
