### ISSUE TITLE
Manage Applications - additional requirements redirect to KYCC

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1394]
The BAM flow will require additional requirements on KYC process.
It's very likely that those additional requirements are not fulfilled by the SK wallet, but are done on the KYCC customer web app.

Currently, when manage applications sees KYCC status 9, it shows a "add documents" button and that button triggers the KYC requirements flow in the wallet.

Please change that, so that the button label is "Complete Application", and it redirects to KYCC chain on an external browser window with auto-login.
Please check `redirectToKYCC` function available in the `marketplace-component` for an implementation of the redirect.

**Comment by eduardosmoura** [comment]
@andregoncalves Should we apply this new flow (redirectToKYCC) even if it's a incorporations application? Or for a incorporations application, we must continue with the current flow (Add Documents)?

**Comment by andregoncalves** [comment]
We can apply this for incorporations as well.
Later on, we will need to improve this to be able to distinguish requirements that can be fulfilled by the wallet and ones that need redirect to KYCC.

**Comment by rhdelima** [comment]
Looks good. However, Complete Application button doesn't appear when user clicks on refresh. User needs to restart wallet for it to show. Will log a separate ticket
