### ISSUE TITLE
Custom Token add/delete confirmation popup

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1401]
Necessary changes:
- [x] button color
- [x] alignment of list
- [x] popup width

Current versions:
![Screenshot 2019-07-10 at 10.19.33.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/a135214c-b3ca-4af5-9f7b-3a16e0c4df6e)
<img width="903" alt="Screenshot 2019-07-10 at 10 27 41" src="https://user-images.githubusercontent.com/7461010/60953389-5e0f5700-a2fd-11e9-9ce8-10b39bcfb141.png">

Designs:
https://projects.invisionapp.com/d/main#/console/15222689/316491961/preview
https://projects.invisionapp.com/d/main#/console/15222689/316491955/preview
https://projects.invisionapp.com/d/main#/console/15222689/317772119/preview

**Comment by rhdelima** [comment]
Looks good. Though there is an issue with the token name. Will log a separate ticket.
