### ISSUE TITLE
BAM: Blank screen is displayed after submitting application with or without DID

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1402]
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/5f789ef0-2407-49cd-8a9d-c6b297822d2d)

**Comment by CortecKYC** [comment]
@andregoncalves Can you estimate this issue, please?

**Comment by andregoncalves** [comment]
Done

**Comment by rhdelima** [comment]
Looks good. Note that DID is now required to submit application.
