### ISSUE TITLE
Windows certificate change

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1417]
- [x] document the process
- [x] find a place to store certificate sources securely
- [x] update appveyor with new certificate

**Comment by sk91** [comment]
Certificate sources will be stored in lastpass secure notes

**Comment by sk91** [comment]
Blocked by certificate, it needs to be issued.

Current status "processed by digicert"
Support is not currently accessible due to some technical issues on their part (17.07.2019)

**Comment by CortecKYC** [comment]
Adding this ticket to Sprint 21 since the Certificate has been issued already.

**Comment by andregoncalves** [comment]
Certificate is now correctly added to appveyor.
