### ISSUE TITLE
BAM Payment issues with SK Payment Contract

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1426]
- Missing link on `why?`
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/5d2ca377-4af4-4e8c-90dc-dccb30461595)

- Missing link on `Learn how`
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/57304956-cede-423d-a862-dd341dec5be7)

- Transaction Processing took a long time to complete

- Transaction Error after paying BAM application
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/8b66fdf3-25e7-4b53-86fe-13a227ab5ae4)
![image](https://user-images.githubusercontent.com/10294014/61209006-366c2480-a72b-11e9-8140-dd9d4dbc9f07.png)

**Comment by andregoncalves** [comment]
Payment contract related.

**Comment by rhdelima** [comment]
Can close this one? @andregoncalves @CortecKYC
