### ISSUE TITLE
Send ERC20 Token screen improvement

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1431]
Current screen:
https://projects.invisionapp.com/d/main#/console/15222689/317467925/preview

**Comment by designhorf** [comment]
![307 2 - Send ERC20 Tokens + Advanced - closed](https://user-images.githubusercontent.com/7461010/61466430-31e97b00-a97a-11e9-9e09-9cadf7eb7415.jpg)
![307 2 - Send ERC20 Tokens + Advanced - opened](https://user-images.githubusercontent.com/7461010/61466431-32821180-a97a-11e9-82a7-cf6b11bbce40.jpg)

**Comment by oanamangiurea** [comment]
@designhorf this need discussing. 

- Address should come after the Token Selection
- Focus should be on the Amount, which also needs to be a full width field, as more than often we have more than 6 digits to display there
- Max is not visible enough or easy to understand 
- we need to show available balance (so Max button makes sense)

**Comment by andregoncalves** [comment]
@designhorf should I update this to sprint 20?

**Comment by designhorf** [comment]
@andregoncalves if you don't mind I want to take this task back to backlog and if the `Corporate Wallet UI update` task is done I'll work on this one again.

**Comment by andregoncalves** [comment]
Ok.
