### ISSUE TITLE
Wallet sanity check procedure

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1432]
A set of constant checks to do before release.

Should be relatively short and cover basic functionality
https://confluence.kyc-chain.com/display/SEL/QA%3A+Wallet+Sanity+Check

**Comment by CortecKYC** [comment]
@rhdelima @sk91 Can I get an update on this ticket?

**Comment by sk91** [comment]
@rhdelima where you able to work on it?

**Comment by rhdelima** [comment]
This is done for DID. @CortecKYC @sk91

**Comment by CortecKYC** [comment]
General sanity check, not just for DID.

**Comment by CortecKYC** [comment]
@rhdelima Let me know when you can do this.

**Comment by sk91** [comment]
@rhdelima please finish it when you have time

**Comment by rhdelima** [comment]
Done.

**Comment by CortecKYC** [comment]
@sk91 can we close the ticket now?

**Comment by sk91** [comment]
@CortecKYC yes, thanks @rhdelima
