### ISSUE TITLE
Guide to Setup Windows DEV ENV

### ISSUE THREAD

**Issue by eduardosmoura** [SelfKeyFoundation/Identity-Wallet#1433]
https://confluence.kyc-chain.com/pages/viewpage.action?spaceKey=SEL&title=Setup+Windows+DEV+ENV

**Comment by andregoncalves** [comment]
@eduardosmoura what's the status of this task?

**Comment by eduardosmoura** [comment]
@andregoncalves it's almost done. I will try to wrap it up today.

**Comment by rhdelima** [comment]
@eduardosmoura @CortecKYC Can we close this one? This doesn't need QA.
