### ISSUE TITLE
Eslint warnings and errors in Selfkey UI

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1436]
![Screenshot 2019-07-17 at 20.00.23.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/cee1eab9-8c17-42cf-a995-289d1c522cbb)

**Comment by sk91** [comment]
@designhorf check out my comments here https://github.com/SelfKeyFoundation/selfkey-ui/pull/157

That might be the issue
