### ISSUE TITLE
When error occurs during attribute schema resolution, wallet is stuck at error state

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1437]
https://recordit.co/bLYA6dsGZ2

![Image Pasted at 2019-7-18 16-45.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/c5d1773b-30b4-482a-8ac1-186e2750214e)

**Comment by sk91** [comment]
![Image Pasted at 2019-7-18 16-46](https://user-images.githubusercontent.com/1021965/61466254-429def00-a982-11e9-8090-18b49c94b00a.png)

**Comment by eduardosmoura** [comment]
@rhdelima could you recheck this one using the latest version, please? 

I tested on my local, and it worked fine.

**Comment by rhdelima** [comment]
@eduardosmoura
I was able to replicate this again on the latest release build (1.2.3-beta) WIN. This issue is hard to replicate. 

![image](https://user-images.githubusercontent.com/10294014/63269934-b4db5980-c2c9-11e9-91f0-74d535776aac.png)

**Comment by eduardosmoura** [comment]
@rhdelima please let me know when you are available. I want to get more information on how to reproduce this issue in order to fix it. Thank you.

**Comment by eduardosmoura** [comment]
@rhdelima Could you, please run the wallet using this environment variable (FORCE_UPDATE_ATTRIBUTES=true) and check if it works? Meanwhile, I will work on a workaround for this fix until we don't have the schedulers done.

**Comment by eduardosmoura** [comment]
@rhdelima Do you have any update on this?

**Comment by rhdelima** [comment]
@eduardosmoura 
I'm no longer encountering the issue after using FORCE_UPDATE_ATTRIBUTES=true.
