### ISSUE TITLE
BAM: Display `Not Enough KEY` modal if insufficient funds

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1438]
This task was originally a bug fix, but we came to the conclusion that it needs to be changed. Please see last comment by Oana.
-----------------------

![Image Pasted at 2019-7-17 20-56.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/ffb45dc3-5b05-4b44-b1fe-3a34df58c35c)

**Comment by andregoncalves** [comment]
We should test for enough KEY tokens at the beginning of the checkout (before KYC screen).

**Comment by rhdelima** [comment]
I'm expecting to show the error message upon payment. Will you agree with the current implementation @oanamangiurea ? See recording: https://recordit.co/CkRLTkhLRq

**Comment by andregoncalves** [comment]
I don't think it makes sense to go through the entire process and only show this when paying.
IMO users should be warned before buying, and that way the KYC process is not initiated.

**Comment by oanamangiurea** [comment]
@rhdelima @andregoncalves @eduardosmoura 

I think Andre is right, we should do that test at the beginning, saving user time if he doesn't have enough Key. However I think we could arrange that modal to look better, so I designed the following:

https://projects.invisionapp.com/d/main#/console/15222689/381825690/preview 

Please let me know if you need a new task to implement this

**Comment by CortecKYC** [comment]
For reference: #1834

**Comment by CortecKYC** [comment]
@andregoncalves Is this being addressed in the ticket https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1971 ?
If so, can we close this one?
