### ISSUE TITLE
BAM: Account Types tab issue

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1440]
1. When opening a jurisdiction, Account Types tab should be highlighted by default
2. When opening Account Types tab, it shows blank

build: dev_2019.07.17.10_SelfKey Identity Wallet-1.0.1-beta-mac

https://recordit.co/FWKLT9jAch

**Comment by andregoncalves** [comment]
@rhdelima fix in dev, QA ready.

**Comment by rhdelima** [comment]
Looks good. Pass
