### ISSUE TITLE
Wallet menu always visible

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1457]
To improve wallet usability and discovery of functions we want the menu to always be visible. 

It will have a collapsible option, but in it's default state the menu moves to the left side of the app and is expanded. 

1. Expanded: https://projects.invisionapp.com/d/main#/console/15222689/375497853/preview 
2. Collapsed https://projects.invisionapp.com/d/main#/console/15222689/375497852/preview 

It will be visible on all pages.

**Comment by CortecKYC** [comment]
@rhdelima Can you test this, please?

**Comment by rhdelima** [comment]
@designhorf Failing this one. Menu sidebar is not visible when setting up SelfKey ID.

![image](https://user-images.githubusercontent.com/10294014/64620629-d76b1900-d416-11e9-9799-a3df5b89d090.png)

**Comment by designhorf** [comment]
@rhdelima @CortecKYC I discussed with @oanamangiurea about this task and she said it's not a high priority issue. We can close this task and I could create a new issue for this bug.

**Comment by CortecKYC** [comment]
Okay, @designhorf 
Closing it.
