### ISSUE TITLE
Update Application is NOT working

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1459]
User has to restart wallet for the status to be updated. 

Steps to replicate:
1. User opens wallet 
2. User submits application
3. Management resends back application
4. User clicks on refresh icon or Update Application
5. Check status

Expected Result:
Complete Application button is displayed

Actual Result:
Nothing happened.

See sample recording.
http://recordit.co/NlPrE2G3Ij

**Comment by eduardosmoura** [comment]
@rhdelima Could you send your wallet information (keystore file key and password)? So I can try to debug it.

**Comment by rhdelima** [comment]
Looks good. Pass
