### ISSUE TITLE
QA testing documentation

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#1480]
@rhdelima , we need you to write down some documentation about the tests you do when you QA for SK.
If you're not sure what to include, please ask @sk91  . He can give you some ideas

**Comment by CortecKYC** [comment]
@rhdelima What's the progress on this?

**Comment by rhdelima** [comment]
Done with the documentation. This is ready for review.

https://confluence.kyc-chain.com/x/xYCbAg

**Comment by CortecKYC** [comment]
I'll take a look.
