### ISSUE TITLE
Initial setup windows not centered

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1521]
The initial setup and configuration windows seem to have too much top space and require scrolling unnecessarily. /cc @oana , @designhorf 

![Screen Shot 2019-08-14 at 17.57.33.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/6f14cc5a-12c6-440a-982b-49bfa928905f)

**Comment by oanamangiurea** [comment]
This screen should not be displayed anymore. Closing the issue
