### ISSUE TITLE
Auto-Update fails on some macOS installations

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1522]
- [x] Fixed auto-update on old macOS installations
- [x] Upgraded to electron-builder to 20.38.3

```
2019-08-15 10:01:38.400 SelfKey Identity Wallet[80391:3282395] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
2019-08-15 10:01:38:406 MAIN autoupdater warn: Error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
```

**Comment by andregoncalves** [comment]
This affects older macOS versions <10.12.
After some research, I believe we need to update electron-builder to at least 20.38.3 (current is 20.36.2).
Details on the fix here:
https://github.com/electron-userland/electron-builder/releases/tag/v20.38.3

@sk91 Do you foresee any issue with updating electron-builder to 20.38.3 ?

**Comment by CortecKYC** [comment]
@andregoncalves Are you going to fix this soon?

**Comment by andregoncalves** [comment]
@sk91 waiting for your security input regarding update of electron-builder dependency.
If okay, I will go ahead and update electron-builder.

**Comment by sk91** [comment]
Will check it out tomorrow and let you know

**Comment by sk91** [comment]
Andre it seems like a minor version upgrade, so go ahead and do it, but make sure that in qa the build is checked on all platforms

**Comment by CortecKYC** [comment]
@rhdelima Can you QA this ticket?

**Comment by CortecKYC** [comment]
@rhdelima As discussed during standup, you cannot test the auto-update on old MacOS but **you can test the upgrade to electron-builder to 20.38.3**. Please do it.

**Comment by rhdelima** [comment]
@andregoncalves Possible issues related to this upgrade:
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1589
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1590

**Comment by andregoncalves** [comment]
I think they are not related.

**Comment by rhdelima** [comment]
Waiting for release before closing this.

**Comment by rhdelima** [comment]
@andregoncalves Can we close this now?
