### ISSUE TITLE
WIN: Duplicate records when adding address

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1536]
https://recordit.co/5Rc5jFi7Vc

**Comment by rhdelima** [comment]
@eduardosmoura Failing this one. Error is encountered when navigating to Address Book screen

http://recordit.co/PcnnU4W4Xm

**Comment by eduardosmoura** [comment]
Thank you @rhdelima. I will check that now. I let you know when it's fixed.

**Comment by rhdelima** [comment]
Looks good. Pass
