### ISSUE TITLE
CORP1: Create Identity entity in the wallet Backend

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1550]

**Comment by sk91** [comment]
For QA: 
This is a backend change only, to test this, check out if selfkey id and marketplace applications work as before

**Comment by rhdelima** [comment]
@sk91 , See issues below
- Unable to associate DID
![image](https://user-images.githubusercontent.com/10294014/64906436-236cd500-d719-11e9-8416-956bdaa3d49c.png)
- BAM: Shows missing details error even if all requirements are completed
![image](https://user-images.githubusercontent.com/10294014/64912201-72892900-d75e-11e9-998b-70a8ccdde55c.png)
- BAM: Error on some jurisdictions (ex. Curaçao, Belize under Corporate Accounts)
![image](https://user-images.githubusercontent.com/10294014/64912228-d3b0fc80-d75e-11e9-85cc-72272d3fe2b7.png)
- Incorporations: Checklist is not showing (MATOMO_SITE=2 INCORPORATIONS_PRICE_OVERRIDE=0 INCORPORATION_KYCC_INSTANCE='https://dev.instance.kyc-chain.com/api/v2/'  INCORPORATIONS_TEMPLATE_OVERRIDE='5d09cdf026f7be196c7e063c' open SelfKey\ Identity\ Wallet.app)
![image](https://user-images.githubusercontent.com/10294014/64913031-04972e80-d76b-11e9-82f0-7a783e414178.png)

**Comment by sk91** [comment]
@rhdelima thanks! Good Job!

> Unable to associate DID. Keeps on loading

fixed in https://github.com/SelfKeyFoundation/Identity-Wallet/pull/1591

> BAM: Shows missing details error even if all requirements are completed

could not reproduce. Can it be that you used an email that you tried previously with different address?

> BAM: Error on some jurisdictions (ex. Curaçao, Belize under Corporate Accounts)

fixed in https://github.com/SelfKeyFoundation/Identity-Wallet/pull/1591

> Incorporations: Checklist is not showing

Could not reproduce

**Comment by rhdelima** [comment]
blocked with https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1706

**Comment by sk91** [comment]
This functionality is already in production, and was covered by tests for other identity related staff
