### ISSUE TITLE
CORP1: update all wallet parts to use identity entity

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1551]
- [x] remove did from wallet in favor of identity
- [x] move profileImage to identity
- [x] change public key to address

**Comment by sk91** [comment]
For QA:

- test all possible wallet unlock/create flows
- test money transfer
- test marketplace application
- test did creation / association
- test profile image upload

**Comment by andregoncalves** [comment]
@rhdelima check comment above ⬆️

**Comment by rhdelima** [comment]
Looks good. Pass
