### ISSUE TITLE
CORP1: UI add entity switcher to menu

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1552]

**Comment by eduardosmoura** [comment]
@oanamangiurea do we have screens (design) for this ticket? 

@sk91 what's the scope for this ticket? Is it just the "Wallet Menu"? Or it should go all the way down to "New Corp Wizard" and "Corp Profile - Overview"? 

https://confluence.kyc-chain.com/pages/viewpage.action?spaceKey=SEL&title=CORP1%3A+Create+New+Company+Profile

**Comment by oanamangiurea** [comment]
@eduardosmoura yes we do, if think ticket refers to the following: 

https://projects.invisionapp.com/d/main#/console/15222689/375497853/preview - see top right name and dropdown

And dropdown itself https://projects.invisionapp.com/d/main#/console/15222689/380279179/preview -> where the button new corporate profile will go to https://projects.invisionapp.com/d/main#/console/15222689/316560291/preview

**Comment by eduardosmoura** [comment]
Thank you so much @oanamangiurea

**Comment by oanamangiurea** [comment]
@sk91 I meant click on the name that is in the top bar, not in the dropdown menu. For sure the dropdown menu should change accounts. Still UI needs to look like in design

**Comment by sk91** [comment]
Oh, sorry, got confused here for a sec :)

**Comment by CortecKYC** [comment]
If Ferenc still has to work on this ticket, then it's not QA ready. Can you guys confirm?
@oanamangiurea @eduardosmoura

**Comment by rhdelima** [comment]
@designhorf Failing this one due to the following issues:
1. User name is not updated after adding SelfKey ID. Still showing `New Individual`
2. `New Corporate Profile` is not working
![image](https://user-images.githubusercontent.com/10294014/65314680-5efc1900-dbc9-11e9-9cb1-2550e07de843.png)

build: dev_2019.09.19.12

**Comment by oanamangiurea** [comment]
@designhorf  also can you please to the following updates:

https://gyazo.com/7980a9b39d7730921090dff3b43d31b0

1. Button small- let's decrease the font size from 12px to 10px, with character spacing of 0.4. I've updated the style guide as well 
2. Button should have same with as separator line 
3. For the dropdown - add more spacing between the User name and The profile type . Also the font sizing is too big, one should be 14px, the other one explanatory with 13px
4. Please add a hoover background #313D49 to them (the entire element). It should look something like this https://gyazo.com/aebeabd2fea9334394aeeb4137e55ebd

**Comment by rhdelima** [comment]
@designhorf Failing this one again. Based on design, if profile is selected, it should not be displayed on the drop down. 

![image](https://user-images.githubusercontent.com/10294014/65762780-56b95600-e154-11e9-89cd-534ddfe8ef40.png)

**Comment by sk91** [comment]
@rhdelima this is a minor issue, please open a separate issue for it

**Comment by rhdelima** [comment]
ok..Closing this one now. Remaining issue is logged on https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1628
