### ISSUE TITLE
CORP1: UI add create entity button to menu

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1553]

**Comment by eduardosmoura** [comment]
@oanamangiurea Is this button related to this design (https://projects.invisionapp.com/d/main#/console/15222689/317039497/preview), or it should be placed right before/after the corporate one (https://projects.invisionapp.com/d/main#/console/15222689/380279179/preview)?

Also, after the user clicks on this new button, where should we redirect him?

**Comment by oanamangiurea** [comment]
@eduardosmoura that 1st screen is obsolete, as we are changing to having menu on the left side and dropdown in the top navbar. I'll hide it from invision so it won't create confusion anymore

**Comment by eduardosmoura** [comment]
Thanks for the clarification @oanamangiurea

**Comment by rhdelima** [comment]
@eduardosmoura Failing this one due to issues below:
1. Profile menu is not aligned with profile navbar
2. When adding SK id, name should also reflect on profile

![image](https://user-images.githubusercontent.com/10294014/64956108-6b782d00-d8bc-11e9-9bca-b3ef22b5ba2b.png)
