### ISSUE TITLE
CORP1: Corporate profile wizard 2 - add basic identity attributes

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1561]

**Comment by eduardosmoura** [comment]
@oanamangiurea do we have a design screen for this one too? Thank you.

**Comment by oanamangiurea** [comment]
@eduardosmoura are you meaning this? https://projects.invisionapp.com/d/main?origin=v7#/console/15222689/316560292/preview

**Comment by eduardosmoura** [comment]
Thank you @oanamangiurea

**Comment by eduardosmoura** [comment]
Same PR (https://github.com/SelfKeyFoundation/Identity-Wallet/pull/1583) as

**Comment by sk91** [comment]
For this ticket to be complete, backend should work as well (without members part)

**Comment by sk91** [comment]
@eduardosmoura I will define the new identity attributes while you do the ui

**Comment by eduardosmoura** [comment]
Ok @sk91, do you which ones are we going to add already?

**Comment by sk91** [comment]
at this time thous that are needed in the design:

https://projects.invisionapp.com/d/main#/console/15222689/316560291/preview

- legal jurisdiction
- legal entity name
- legal entity type
- company-creation-date


Actually, I think this ui was developed already, so we need to define the attributes and connect them

**Comment by rhdelima** [comment]
@eduardosmoura @sk91  Failing this one since Legal Jurisdiction and Legal  Entity Type drop down are missing

![image](https://user-images.githubusercontent.com/10294014/65767220-cf71df80-e15f-11e9-9f1d-95041a2a1759.png)

**Comment by sk91** [comment]
this happens because on production build, thous attributes are not loaded, @rhdelima will add a env var for you to controll this

**Comment by sk91** [comment]
@rhdelima once #1630 is merged you would be able to run the wallet with `ATTRIBUTE_TYPE_SOURCE_OVERRIDE=development` to see the new attributes

**Comment by rhdelima** [comment]
Looks good. Pass
