### ISSUE TITLE
Incorporations Marketplace: Layout issue on Tax Treaties tab

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1566]
Jurisdiction: Cayman Islands

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/8ae84bcf-6578-4fdd-b89d-f7239e15e637)

**Comment by CortecKYC** [comment]
@andregoncalves @designhorf FYI.

**Comment by CortecKYC** [comment]
@andregoncalves Have you started on this one? 
Incorporations is not a priority. Corporate Wallet is.

**Comment by andregoncalves** [comment]
Haven't started, but I think this is a quick fix, I'm tackling it today but will stop if unexpected difficulties arise.

**Comment by CortecKYC** [comment]
Ok to this one, but from now on, this kind of bugs will be tackled during the cool-down period.

**Comment by andregoncalves** [comment]
Understood, moving this to backlog

**Comment by rhdelima** [comment]
Looks good. Pass
