### ISSUE TITLE
Exchanges: Add Disclaimer to Exchanges Marketplace

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#1572]
Add this disclaimer:
_Although we use our best efforts to keep the information of this site accurate and up-to-date, we make no representations or warranties with respect to the accuracy, applicability, fitness, or completeness of the contents of this website. We disclaim any warranties expressed or implied, merchantability, or fitness for any particular purposes_

**Comment by rhdelima** [comment]
Looks good. Pass
