### ISSUE TITLE
Exchanges: Enable affiliate links to Crypto-exchanges and add affiliate disclaimer

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#1573]
- List of affiliate links: https://confluence.kyc-chain.com/display/SEL/Exchanges+Development+airtable (only 3 for now)
- [ ] Enable affiliate links to Exchanges in the list above
- [ ] Add affiliate disclaimer (users must be aware that they may click an affiliate link and we may earn commissions for it)

**Comment by andregoncalves** [comment]
@CortecKYC where do we have the affiliate links for the exchanges? 
The URLs in the airtable don't seem to be affiliate links.

**Comment by sk91** [comment]
@andregoncalves  https://confluence.kyc-chain.com/display/SEL/Exchanges+Development+airtable

**Comment by CortecKYC** [comment]
@andregoncalves It was in the ticket description ;)

**Comment by andregoncalves** [comment]
Ah correct, sorry.

**Comment by andregoncalves** [comment]
A new column (affiliateURL) in the exchanges airtable is used for loading the url target for the button. Nothing is displayed if no affliateURL exists.

![Screenshot 2019-10-10 at 20.52.49.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/f7dca2b9-f2f0-4081-9675-93fdf66e8f04)

**Comment by rhdelima** [comment]
Looks good. Pass

**Comment by CortecKYC** [comment]
@andregoncalves @rhdelima I just installed 4.1.0 and clicked on an affiliate link. I did not see any disclaimer disclosing that the link was an affiliate and what it means. 
Where is it?

**Comment by andregoncalves** [comment]
I must have missed that... the only disclaimers included are the ones described here:
https://github.com/SelfKeyFoundation/Identity-Wallet/pull/1710
(on the listing and on the detail page).

Where is the text for the affiliate specific disclaimer?

**Comment by oanamangiurea** [comment]
@andregoncalves here is the text and the screen. Placed text under the button https://projects.invisionapp.com/d/main#/console/15222689/389299195/preview

**Comment by CortecKYC** [comment]
New ticket: https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1746
