### ISSUE TITLE
Left Sidebar Menu UI Issues

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1574]
- [x] Remove horizontal scroll when sidebar is closed (Mac) https://gyazo.com/0c68dec3e76763e3f41977cae1626d98 
- [x] Add hover effect on menu icon - idea: make all lines equal width on hover 
- [x] Remove 1px line border from bottom of the menu - https://gyazo.com/07905cdb7a4757f24839e03d1e5c1c61 
- [x] Add link on entire logo, not only the symbol, so user can return to dashboard no matter where they click
- [x] Fix secondary pages backgrounds on scroll - https://gyazo.com/e6a7862ac94320237252ee2850582c35 -> background property moved to <html> instead of <body> 
- [x] Let's start the app with the menu closed. I realized it looks strange if it's open, and cam cause frustration more than looking for a way to open it

**Comment by CortecKYC** [comment]
@rhdelima Please test this.

**Comment by rhdelima** [comment]
Looks good. Pass
