### ISSUE TITLE
Make top navbar fixed

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1575]
To support new left sidebar and top dropdown to switch profiles for corp wallet, I think the top navbar should be fixed, and only the rest of the page to scroll.

**Comment by rhdelima** [comment]
@designhorf Failing this one due to issues below:
1. Profile menu is not aligned with profile top navbar

![image](https://user-images.githubusercontent.com/10294014/64956108-6b782d00-d8bc-11e9-9bca-b3ef22b5ba2b.png)

**Comment by designhorf** [comment]
@rhdelima This issue will be fix with this one. -> https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1552

**Comment by rhdelima** [comment]
Thanks @designhorf . Closing this one.
