### ISSUE TITLE
Bank Accounts - detailed modal issues

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1586]
1. In the Bank account details modal, under the description tab and services tab the text is not well spaced. It's because it uses a `<div>` only and not a `<p>` tag https://gyazo.com/4ba77ec65ecd5c6c17a94b97a1227384 

2. Same as above, under some services tab there is a list, but it doesn't get displayed as one. See United Arab Emirates for example https://gyazo.com/9c9bc8cc086da4174470cc540fa26abd 

2. When switching tabs, depending on content, the modal startt scrolling . up and down, and it's very annoying https://www.loom.com/share/e5fbd5c9175242878d518eef485f06ea

**Comment by andregoncalves** [comment]
@designhorf is this ready for QA?

**Comment by sk91** [comment]
@andregoncalves merged to dev 5 days ago, I would say yes

**Comment by CortecKYC** [comment]
@rhdelima Please test

**Comment by rhdelima** [comment]
Looks good on my end. Waiting for @oanamangiurea 's confirmation to close this.

**Comment by rhdelima** [comment]
Looks good. Pass
