### ISSUE TITLE
Unable to open trezor and ledger wallet

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1589]
Steps to replicate:
1. Open wallet
2. Connect to Ledger (make sure ledger is connected and unlocked)
3. Select an address
4. Click `Use selected Address`

Expected Result:
Wallet is opened

Actual result:
Nothing happens.

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/e43402dc-caf3-4d4d-a5f6-2dc2ada4c722)

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/901f56f8-b60f-4828-8a05-2d9876b6422d)

**Comment by CortecKYC** [comment]
@andregoncalves Take a look, please. Let me know how urgent it is to fix this.

**Comment by andregoncalves** [comment]
@CortecKYC I don't have an hardware wallet. @max can you take a look?

**Comment by sk91** [comment]
fixed on #1606

**Comment by CortecKYC** [comment]
@rhdelima Can you QA?

**Comment by rhdelima** [comment]
Looks good now. Pass
