### ISSUE TITLE
Error when clicking Continue on KYC Process Started modal

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1602]
https://recordit.co/jceLa2BWii
[https://app.zenhub.com/files/105664964/26c75c9b-f1ae-4cf6-8cb6-6a5928c01695/download](https://app.zenhub.com/files/105664964/26c75c9b-f1ae-4cf6-8cb6-6a5928c01695/download)

**Comment by andregoncalves** [comment]
Maybe caused by an issue with the kycc dev instance.
Waiting for a fix.

**Comment by andregoncalves** [comment]
@rhdelima a fix (#1624) is on PR-review, keep an eye on it on the build channel.

**Comment by rhdelima** [comment]
Looks good. Pass
