### ISSUE TITLE
Add link on document name - usability fix

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1603]
Under SelfKey profile, to view the content of a document added right now you have to click on the edit icon and then on the name of the uploaded document.

For better usability, we need to add a link straight on the document name in the listing table -> https://gyazo.com/db9c24115e271375be6f6e0ce69fe344

**Comment by CortecKYC** [comment]
@oanamangiurea Could you please QA this ticket?

**Comment by rhdelima** [comment]
Looks good. Pass

http://recordit.co/R9fL2Lrk2B
