### ISSUE TITLE
Collapsed menu - add titles for hover

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1604]
To increase usability, all links/icons in the collapsable menu should have alt titles, that way on hover you know what is the item name, without needing to open the menu.  https://gyazo.com/3f54ea763ad000fbe702295c7e62c3f5

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/65765355-9e42e080-e15a-11e9-8499-52887b4752e3.png)
