### ISSUE TITLE
Profile is still shown on drop down after being selected

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1628]
Based on [design](https://projects.invisionapp.com/d/main#/console/15222689/380279179/preview), selected profile should not be displayed on the profile drop down.
 
![image](https://user-images.githubusercontent.com/10294014/65765739-aa7b6d80-e15b-11e9-85f4-bebdb43b23a0.png)

**Comment by oanamangiurea** [comment]
Passed, all good.
