### ISSUE TITLE
Long profile name causes layout bug

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1633]
![Screenshot 2019-09-27 at 12.56.28.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/148aa795-2e4e-41b9-8bf3-29d0daf5bf0c)

**Comment by rhdelima** [comment]
Looks good. Pass
![image](https://user-images.githubusercontent.com/10294014/66034416-c4da9000-e53b-11e9-8232-69eb285e4676.png)
