### ISSUE TITLE
Unable to associate DID

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1637]
Unable to associate DID. It shows `Invalid DID` error even if DID is valid and correct
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/664956c9-acc3-4a50-81ec-5c2786768ef9)

build: dev_2019.09.27.15

**Comment by sk91** [comment]
Good catch @rhdelima, fixed in #1638, awaiting review

**Comment by rhdelima** [comment]
Looks good now. Pass
