### ISSUE TITLE
Authentication error navigating to Marketplace Applications using trezor or ledger

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1643]
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/92b816e6-377a-48e5-931a-1c665b7dbaaf)

**Comment by andregoncalves** [comment]
@max can you take a look?

**Comment by sk91** [comment]
sure

**Comment by rhdelima** [comment]
Looks good. Pass
