### ISSUE TITLE
When viewing Corporate Vault by clicking My Profile, SK Identity Wallet is flashed before showing the corporate vault

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1644]
http://recordit.co/x14vizMZFJ

**Comment by andregoncalves** [comment]
@sk91 I think this should be tackled as part of a larger selfkeyid refactor we discussed.

**Comment by sk91** [comment]
@andregoncalves it is a quick fix for the bet, then we can refactor on cool down

**Comment by andregoncalves** [comment]
Ok

**Comment by rhdelima** [comment]
Looks good. Pass
