### ISSUE TITLE
Replace API key for Airtable cloud function

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1653]
It's currently using Andre's api key.
Should be replaced with an org api key.

- [x] Check who has access to help@selfkey.org --> Done. We have access already (Max, Andre, Cristina -->Max recovered them and sent Andre and Cristina credentials via Lastpass on Oct. 28, 2019)
- [x] Get airtable login credentials for help@selfkey.org account 
- [x] Contact Zach Garman z.garman@gmail.com to change airtable ownership to help@selfkey.org --> **asked Cristiana to do it. Waiting for reply**
- [x] Generate new api key for selfkey airtable account (Andre)
- [x] Change cloud function api key (Max)
- [ ] Document in confluence

**Comment by CortecKYC** [comment]
Cristiana reached out to Zach Garman (z.garman@gmail.com) to change airtable ownership to help@selfkey.org --> Still waiting for reply. 
Last follow up today (Oct. 15)

**Comment by CortecKYC** [comment]
Zach said that when he left the Airtables were actually copied under someone else's ownership (Edmund most probably). Cristiana asked him to help anyway but he did not come back.

@andregoncalves @sk91 Could it be possible to copy the Airtables to a new account?

**Comment by andregoncalves** [comment]
@CortecKYC can you share with me the airtable login credentials for help@selfkey.org ?

**Comment by andregoncalves** [comment]
FYI: it's possible to copy airtable data to a new account, so given the implications already discussed, I propose we move ahead with the following:
- Copy airtable to new airtable under selfkey.org ownership
- Change cloud function to point to new airtable
- Delete all the data in old airtable.

**Comment by CortecKYC** [comment]
@andregoncalves Which API key are we using now? Still yours or has it been replaced already?

**Comment by sk91** [comment]
@CortecKYC it is done
