### ISSUE TITLE
Corporate Wallet Setup - missing field validations

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1659]
Corporate Wallet Setup - missing field validations - if I don’t input information in the mandatory fields nothing happens

**Comment by sk91** [comment]
For QA:
- create new corporate profile
- on company creation wizard, try submitting without filling any fields
- try to input incorrect email
- fill all fields correctly and see that the corporate profile is created

**Comment by rhdelima** [comment]
@designhorf @sk91 
Please see minor issue below:
1. `Creation Date` field is not highlighted when error message is displayed.

![image](https://user-images.githubusercontent.com/10294014/66333596-eb4c6100-e969-11e9-8a33-2e35b83a4682.png)

**Comment by sk91** [comment]
@rhdelima please open a separate issue for @designhorf 

"Fix date picker error state"

**Comment by sk91** [comment]
@rhdelima will be handled separately in #1715 

Please proceed with this ticket

**Comment by rhdelima** [comment]
Closing this now. Pass
