### ISSUE TITLE
Corporate Wallet Dashboard - chart tooltip UI

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1660]
Corporate wallet Dashboard - tooltip for chart should have same styling as the one used in the main wallet dashboard for crypto

**Comment by rhdelima** [comment]
Testing is blocked since some chart is hidden

**Comment by rhdelima** [comment]
Closing this one. Though the tooltip is working, the texts are incorrect. Already reported the issue on another this.
