### ISSUE TITLE
Create Exchanges Integration strategy DOC

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1662]
https://confluence.kyc-chain.com/display/DEV/Exchanges+Integration+Strategy

**Comment by sk91** [comment]
@CortecKYC. I think we can close this one once @Horizon88  reviews it

**Comment by CortecKYC** [comment]
@sk91 I'll create a task for him in Asana. Otherwise, he won't review it

**Comment by CortecKYC** [comment]
Reviewed by Edmund and commented in the doc.
