### ISSUE TITLE
Demo: Corporate Wallet

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#1669]
During Level 10 meeting on October 10

**Comment by andregoncalves** [comment]
@sk91 any suggestions on what I should demo (and in what order)?
Any thing I should emphasise or mention?

**Comment by sk91** [comment]
@andregoncalves not really I was thinking of doing the following:

- create a new wallet
- show that there is a new drop down for corporate
- create new corporate profile
- show field validations in the wizard 
   (explain that additional form will be presented for members)
- finish creating profile
- show corporate profile page
- add /delete / update some attributes
- go to profile selector 
- select individual profile (explain that only one individual profile is allowed, while many corporate)
- create selfkey id 
- show selfkey id attributes (explain that thay are separate and the list of types is different)
- answer questions

**Comment by andregoncalves** [comment]
Great. thanks.
