### ISSUE TITLE
CORP3: define corporate residency attribute (domicile)

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1673]
Basically a copy of the residency attribute for individuals

**Comment by sk91** [comment]
FOR QA:
please check that there is a new attribute available for corporate profile "Domicile" 

Should be similar to country of residency for individuals
Only available in "development" attribute source for now

**Comment by rhdelima** [comment]
Looks good. pass

![image](https://user-images.githubusercontent.com/10294014/68684609-bd2ef200-05a3-11ea-8558-ef33c7fa76cd.png)
