### ISSUE TITLE
CORP3: add members on corporate wizard screen

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1677]
- Develop the add company members screen 
  - it should display different member types based on company type
- implement adding a member on wizard screen (corporate identity is not created yet at this point)

- add member handling on create corporate identity

**Comment by rhdelima** [comment]
@andregoncalves @sk91 
Unable to add corp member. http://recordit.co/iC9lbbos20

[log.log](https://github.com/SelfKeyFoundation/Identity-Wallet/files/3887526/log.log)

**Comment by andregoncalves** [comment]
You tested an old build due to this #1888.

**Comment by CortecKYC** [comment]
@rhdelima Please test again

**Comment by rhdelima** [comment]
Looks good. Pass
