### ISSUE TITLE
CORP3: ui manage members tab

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1679]
- Implement ui for manage members tab

**Comment by rhdelima** [comment]
Failing this one. Please see issues below:
1. Name should be displayed on one line
2. Missing email
3. Share should be in %
4. Table is NOT shown properly. Some parts are hidden
![image](https://user-images.githubusercontent.com/10294014/69826353-b5cb4200-124d-11ea-96b2-a85d808acc65.png)

**Comment by andregoncalves** [comment]
1, 2 and 3 addressed on #1921.
@designhorf is working separately to fix 4.

**Comment by rhdelima** [comment]
`Shares` still not showing % but will log it on separate ticket. Closing this one.
