### ISSUE TITLE
CORP3: design - add sub members for corporate members

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1681]
Currently there is no screen to add a member to a corporate member

@oanamangiurea I propose to add it to `add company member` screen

and also add an `edit member` screen

That will allow to manage the following fields:

- member positions
- equity
- parent company

**Comment by oanamangiurea** [comment]
@sk91 not sure I understand what is needed exactly. What do you mean add member to coprorate member?

**Comment by sk91** [comment]
Main identity company A

Member B of company A - individual
Member C of company A - corporate


—— untill here we got everything covered


Now we need to add Member D of company C. We don’t have ui for it unless I
missed somthing

**Comment by oanamangiurea** [comment]
@sk91 I don't think we were supposed to go that deep, that was my understanding. I mean Probably the one setting up company A has no way in knowing who are the members of company C. That was supposed to happen when company C was also using the wallet and they were adding their own structure. Let me please check with Edmund first

**Comment by oanamangiurea** [comment]
@sk91 done, modal updated https://projects.invisionapp.com/d/main#/console/15222689/316560292/preview

and Edit mode is exact same modal, only title changes from Add Member to Edit Member
