### ISSUE TITLE
CORP3: ui - implement sub members for corporate members

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1682]
Implement the designs from #1681

**Comment by rhdelima** [comment]
Failed. When adding sub member, parent company saved is main company. It only works when editing member.
http://recordit.co/x3AqMeR9JF

**Comment by CortecKYC** [comment]
@andregoncalves Please fix

**Comment by andregoncalves** [comment]
Fixed on #1921

**Comment by andregoncalves** [comment]
work in progress

**Comment by andregoncalves** [comment]
Addressed on #1921

**Comment by andregoncalves** [comment]
Fixed on #1925

**Comment by rhdelima** [comment]
Looks good. Pass
