### ISSUE TITLE
CORP3: implement edit company member

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1687]

**Comment by CortecKYC** [comment]
@andregoncalves Can we remove the label "Work in Progress" and add "QA ready"?

**Comment by rhdelima** [comment]
Failing this one. See issues below:
1. Error message on `Shares Owned` when editing manager, grantor and other roles
![image](https://user-images.githubusercontent.com/10294014/69827674-5708c700-1253-11ea-80ee-2b3899240569.png)

2. Error when updating member role
http://recordit.co/ter5wuJSHA

**Comment by andregoncalves** [comment]
Issues addressed on #1921

**Comment by rhdelima** [comment]
Looks good. Pass
