### ISSUE TITLE
Refactor exchanges marketplace components

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1696]
Use the same architecture as the other marketplaces

**Comment by andregoncalves** [comment]
@rhdelima any issues testing this?

**Comment by rhdelima** [comment]
@andregoncalves I don't see any issues except for layout issue and some missing exchanges icon. Can you share the airtable for dev exchanges so I can compare? I think we can close this one.

Thanks!
