### ISSUE TITLE
Disable marketplace for corporate profile

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1704]
While corporate profile is selected, replace the marketplace screen with a coming soon screen.

I would like to replace it fully instead of showing "coming soon" on each category since not all categories are relevant for corporate

**Comment by sk91** [comment]
@oanamangiurea can you help with the design?
@andregoncalves Will be good if this can be implemented this week If you have time. Otherwise I'll do it next week when I'm back

**Comment by andregoncalves** [comment]
Will do this week.

**Comment by oanamangiurea** [comment]
@andregoncalves here's the screen for it https://projects.invisionapp.com/d/main#/console/15222689/387797823/preview

**Comment by andregoncalves** [comment]
Thanks @oanamangiurea

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/66888277-7b487580-f010-11e9-8d66-894243c29fce.png)
