### ISSUE TITLE
BAM: Error when clicking Continue on KYC Started modal 

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1706]
build: dev_2019.10.08.15

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/5ff55111-34cf-4a37-9aea-747573719080)

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/5d297f49-4e20-4b42-9386-8720d6c0d7ae)

**Comment by sk91** [comment]
<img width="1236" alt="Screen Shot 2019-10-14 at 16 57 43" src="https://user-images.githubusercontent.com/1021965/66756964-c8f39f80-eea3-11e9-8461-8004056babef.png">

@ralph Could not reproduce. Any specific use case it happens?

**Comment by rhdelima** [comment]
@sk91 my bad. The error is encountered when clicking Continue on KYC Started modal. 

http://recordit.co/shSIxjJKBy

**Comment by rhdelima** [comment]
@andregoncalves I'm still seeing the error using build dev_2019.11.04.16

http://recordit.co/TvL9wlhQsQ

**Comment by andregoncalves** [comment]
@rhdelima what ENV overrides are you using?

**Comment by rhdelima** [comment]
@andregoncalves 

MATOMO_SITE=2 KYCC_API_OVERRIDE='https://dev.instance.kyc-chain.com/api/v2/' INCORPORATIONS_TEMPLATE_OVERRIDE=5d09cdf026f7be196c7e063c INCORPORATIONS_PRICE_OVERRIDE=0 ATTRIBUTE_TYPE_SOURCE_OVERRIDE='development' FEATURE_CORPORATE=1 open SelfKey\ Identity\ Wallet.app

**Comment by rhdelima** [comment]
@andregoncalves Still getting an error using a new DID

http://recordit.co/6CYrxqUTBj

**Comment by andregoncalves** [comment]
@rhdelima related: https://github.com/kyc-chain/kyc-chain-monorepo/issues/1181

**Comment by andregoncalves** [comment]
Still blocked by KYCC issue 1181

**Comment by CortecKYC** [comment]
Issue 1181 was closed. Please QA this one

**Comment by rhdelima** [comment]
@andregoncalves @sk91 
I'm still blocked with submitting requirements. Please see env variables used and screenshots.
`MATOMO_SITE=2 KYCC_API_OVERRIDE='https://dev.instance.kyc-chain.com/api/v2/' INCORPORATIONS_TEMPLATE_OVERRIDE='5d09cdf026f7be196c7e063c' INCORPORATIONS_PRICE_OVERRIDE=0 ATTRIBUTE_TYPE_SOURCE_OVERRIDE='development' open SelfKey\ Identity\ Wallet.app`
![image](https://user-images.githubusercontent.com/10294014/71485527-65df9b00-284c-11ea-96ae-39f615fbf842.png)

![image](https://user-images.githubusercontent.com/10294014/71485516-5ceec980-284c-11ea-996f-b1e2fd3eaba3.png)

**Comment by sk91** [comment]
@andregoncalves why did you move it to QA ready? did you test and seen that it does not happen anymore?

**Comment by andregoncalves** [comment]
My mistake, I thought this was another thing (the KYCC template bug)

**Comment by andregoncalves** [comment]
@rhdelima are you still having this issue?

**Comment by rhdelima** [comment]
Looks good now. Pass
