### ISSUE TITLE
KEY disappeared and Tokens appear twice

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#1708]
Reported by CS:
**1.  A user had KEY in his wallet but after the upgrade 0 key balance showing in the wallet. He is holding around 517,670 key on address 0xbee4689d70b012dde8a577d34906cdac315e596e .**
- Operating system: waiting for user reply
- The list of transactions shows the inbound transfers but no outbounds.

**2. Polymath token shows twice in the wallet ( see screenshot below)**
In etherscan the tokens are in the address.
He access key through Nano Ledger but hold the coins in the Selfkey wallet.
![Polymath token double](https://user-images.githubusercontent.com/47594955/66554134-b4827080-eb4c-11e9-8aba-70c1c8c816c5.png)

**Comment by susananakatani** [comment]
Operating system is windows 10

**Comment by rhdelima** [comment]
I can't replicate issue on two machines (both win10).

**Comment by sk91** [comment]
Clone of #1712
