### ISSUE TITLE
Possible Identity mix-up bug - v1.3.0

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1712]
"I found a bug in the SK desktop wallet. If you have more than one wallet than you opened and closed on the same PC, when you open one of them it retains the ID of the previous one opened

So if I opened John's wallet, then open Bill's wallet, John's ID appears in top right hand corner where it says 'Personal Profile'.

It's really confusing because at first I thought I'd opened using another user's private key but I hadn't. In fact, the wallet retains all of the previous user's data

It's a real mess actually. I just found out it even keeps the coin labels of coins in other wallets.

This didn't happen in the previous version."

**Comment by andregoncalves** [comment]
@rhdelima I did a few tests but was unable to reproduce the issue.
Can you try and see if you can reproduce it?

**Comment by rhdelima** [comment]
@andregoncalves I can't replicate the issue. I did saw the tokens displayed (from other wallet) but disappeared for few seconds. See recording - http://recordit.co/ANE1GTVhhm

**Comment by sk91** [comment]
Migration failure caused deletion of all wallets, but not connected tables. 

So next time a wallet is created it would be connected to previous information

**Comment by sk91** [comment]
For QA:
#### Test1 
- delete database
- install v1.2.3-beta (https://github.com/SelfKeyFoundation/Identity-Wallet/releases/tag/v1.2.3-beta)

- create and fill up with attributes and tokens 2 wallets (save private keys)

- install v1.3.0 (https://github.com/SelfKeyFoundation/Identity-Wallet/releases/tag/v1.3.0)

- start it and see that no wallets are present

- create one wallet and fill it up (you might see attributes from preveous wallet here, use address from previous setup)
- download current build and open it
- you should see 2 wallets, first one is the one you modified on 1.3.0
- second one should have been recovered from version v1.2.3-beta


####Test2
- delete database
- install v1.2.3-beta (https://github.com/SelfKeyFoundation/Identity-Wallet/releases/tag/v1.2.3-beta)

- create and fill up with attributes and tokens 2 wallets (save private keys)
 download current build and open it
- you should see 2 wallets, the same ones created in v1.2.3-beta

**Comment by rhdelima** [comment]
@sk91 Please see results below:
**Test 1** - Fail 
- Still showed duplicate SelfKey on My Crypto. Wallet was created on 1.2.3 and re-added/created on 1.3.0
![image](https://user-images.githubusercontent.com/10294014/66833754-f8cba180-ef8e-11e9-9871-01566f4464c4.png)

**Test 2** - Pass
