### ISSUE TITLE
Fix Date Picker error state

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1715]
![66333596-eb4c6100-e969-11e9-8a33-2e35b83a4682](https://user-images.githubusercontent.com/1021965/66733822-78f7e700-ee69-11e9-8ae1-8d25ce7a9431.png)

**Comment by sk91** [comment]
<img width="1088" alt="Screen Shot 2019-10-14 at 16 49 37" src="https://user-images.githubusercontent.com/1021965/66756466-c3e22080-eea2-11e9-93f3-71b599280a51.png">

**Comment by rhdelima** [comment]
Looks good. Pass
