### ISSUE TITLE
Prepare Corporate Dashboard for release

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1717]
Disable tabs and widgets not relevant for current release

**Comment by sk91** [comment]
![Screen Shot 2019-10-14 at 16 04 39](https://user-images.githubusercontent.com/1021965/66753525-b5910600-ee9c-11e9-8552-568b0ac04c75.png)

**Comment by rhdelima** [comment]
Looks good. Pass
