### ISSUE TITLE
Token Box Address is too long

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1733]
Current: 
![Screenshot 2019-10-16 at 14.56.26.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/bfd0c63a-1477-42c1-bcf7-ba638db3fca6)

Fixed version: 
![Screenshot 2019-10-16 at 15.11.42.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/bc6e33a8-c1be-4e75-91b3-8cf2216188f0)

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/67143853-62ef8980-f2a2-11e9-9e98-f3ad2db580f1.png)

**Comment by oanamangiurea** [comment]
@designhorf this implementation is not ok. For any token address the last digits are more important than what is in the middle. Please use same solution as proposed for the long did number, meaning, hide the middle characters under 3 dots.

It will look like: 0xe37469264...82dab3892.  I think you can show 0xe[10 characters]...[last 10 characters]

**Comment by sk91** [comment]
@designhorf @oanamangiurea guys, the address is always the same size, can we make it always fully visible ?

**Comment by CortecKYC** [comment]
@sk91 For what I've read, the address is too long to be shown entirely. 
@designhorf @oanamangiurea can confirm this.

**Comment by CortecKYC** [comment]
It's always too long, @sk91

**Comment by rhdelima** [comment]
@oanamangiurea Please confirm if you're good with this. 
![image](https://user-images.githubusercontent.com/10294014/67721322-2eea3600-fa11-11e9-81a4-1e7ace1fd600.png)

thanks!

**Comment by oanamangiurea** [comment]
@rhdelima yes, all good
