### ISSUE TITLE
Issues updating Wallet to 1.4.0 after release. Windows 10

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#1737]
A. User:  _I downloaded the wallet upgrade and 1/4 through installation it turned off by itself !! when i open wallet it prompts me to download again_

B. User: _I've downloaded the new version. First time through the prompt in wallet. The wallet installed but didn't relaunch by itself. Relaunched it and got prompted to download the new wallet again. Then went to download the wallet from the website. Downloaded and launch with no problem_

**Update:**
I experienced the same problem (B) in Windows 10. Log shared below:
[log.txt](https://github.com/SelfKeyFoundation/Identity-Wallet/files/3738764/log.txt)

**Comment by sk91** [comment]
QA done by @eduardosmoura
