### ISSUE TITLE
Fix exchanges logo sizing

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1745]
Please fix the wrong logo sizing for Exchanges table and detailed page https://gyazo.com/f036a6e3f8fe680c616376f66a03f294

Use max-width:100% if needed on image, so it doesn't get squeezed

**Comment by rhdelima** [comment]
@designhorf Failing this one. `Bitcratic` logo is truncated. See screenshots below

![image](https://user-images.githubusercontent.com/10294014/67144368-49e9d700-f2a8-11e9-93e8-4f602ba9687d.png)
![image](https://user-images.githubusercontent.com/10294014/67144379-579f5c80-f2a8-11e9-929c-f98a9a6878d7.png)

**Comment by rhdelima** [comment]
Marketplaces are NOT showing any data

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/67760285-ff244800-fa7b-11e9-80bc-5f938300f98a.png)
![image](https://user-images.githubusercontent.com/10294014/67760817-f97b3200-fa7c-11e9-864d-4a6b0fa8a0f4.png)
