### ISSUE TITLE
Exchanges: Add specific affiliate disclaimer

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#1746]
Here is the text and the screen. Placed text under the button https://projects.invisionapp.com/d/main#/console/15222689/389299195/preview

**Comment by rhdelima** [comment]
@andregoncalves @oanamangiurea 
Correct me if I'm wrong but can we update the disclaimer to:
`Disclosure: The button above is an affiliate link, we may receive a commission for purchases made through this link.`

![image](https://user-images.githubusercontent.com/10294014/67385153-1e772d00-f5c5-11e9-9709-6b1dd3c43b80.png)

**Comment by andregoncalves** [comment]
Yes, agree.
#1768 is on PR-review

**Comment by CortecKYC** [comment]
@rhdelima Please review

**Comment by rhdelima** [comment]
@andregoncalves Sorry but first word `the` should be a sentence case. Should be `The` instead of `the`.

![image](https://user-images.githubusercontent.com/10294014/67446817-64270a80-f644-11e9-9cb4-6858d235cccb.png)

**Comment by rhdelima** [comment]
Looks good now. Pass

![image](https://user-images.githubusercontent.com/10294014/68194089-503dba00-ffef-11e9-9497-fc693b6499fe.png)
