### ISSUE TITLE
Errors on BAM

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1749]
Navigating to these screens will show an error. See sample recording: http://recordit.co/4j4vd0ykbj

Wealth Management > Turkey > Services 
Wealth Management > Switzerland > Services
Personal Accounts > Seychelles > Details
Personal Accounts > Saint Lucia > Details

**Comment by rhdelima** [comment]
Might be good if we cover this on e2e tests

**Comment by sk91** [comment]
Unfortunately our e2e test are disabled for now, we need to fix them in general

**Comment by sk91** [comment]
@andregoncalves ^^

**Comment by eduardosmoura** [comment]
I will try to add this scenario @rhdelima and @sk91

**Comment by rhdelima** [comment]
Looks good. Pass
