### ISSUE TITLE
Inconsistent Identity Attributes display

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1751]
In the user profile we display the label the user inputed for a given attribute, like address

In the corporate profile we display the value of the given attribute.

Ex: address. personal: https://gyazo.com/664239fb0beb2f836260ebca73d4cc1b vs corporate: https://gyazo.com/b7e9c2fd76b8ae2db566188ad97fb0ef  

We should display the label as agreed in the first place

**Comment by andregoncalves** [comment]
@oanamangiurea what screen is that corporate screenshot?

**Comment by sk91** [comment]
@andregoncalves this one https://projects.invisionapp.com/d/main#/console/15222689/316778388/preview

**Comment by rhdelima** [comment]
Looks good. Labels are now showing instead of value. Pass

![image](https://user-images.githubusercontent.com/10294014/67723391-dd44aa00-fa16-11e9-9797-6bac3f08f3a6.png)
