### ISSUE TITLE
Create a document with process to add new vendors to Marketplace

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#1772]
Create a document in Confluence:
- [ ] How to add new vendors to airtable
- [ ] How to add new vendors to Marketplace

These docs should include the process (the steps) and which information the dev team needs from the vendors or other departments.

**Comment by andregoncalves** [comment]
https://confluence.kyc-chain.com/display/SEL/SK+Marketplace+Management
