### ISSUE TITLE
BAM: Clicking Back button always shows the Corporate Accounts

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1775]
1. When user opens a jurisdiction on Personal Accounts or Wealth Management, clicking Back button always shows the Corporate Accounts tab instead of going back to the current tab.
http://recordit.co/kGA86fPL2r

2. Remove html tags on Service tab for Singapore (all tabs)
![image](https://user-images.githubusercontent.com/10294014/67447444-70ac6280-f646-11e9-80d4-914c01a7c29d.png)

**Comment by sk91** [comment]
for QA:
1 - wont fix, expected behavior.
2 - fixed

**Comment by rhdelima** [comment]
Looks good. Pass
