### ISSUE TITLE
identity mixup - multiple personal profiles

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1779]
I created a new profile by clicking in new profile ( several times, it wasn't clear I was creating new profile)
So now I have 2 profiles:
Susana Nakatani
Susana Cortes
With different details but on the top page it only says susana even thoguht they should have different names

https://www.loom.com/share/47533868d06d4f01bb6ff535b12c4782

The fix for that situation might entail the following features:

- [ ] - change profile name
- [ ] - allow deleting profiles
- [ ] - if there is a duplicate in profile name --- suffix it with a number (Susana (2)) 
- [ ] - allow to migrate profile to different wallet ? -- probably will not do that now

- [ ] - validate did related to address and make sure it is owned by the address
- [ ] - add option to delete did
- [ ] - add an option to export/import profile (allow to choose the id attributes to export)

in general there should be only one personal profile.

**Comment by andregoncalves** [comment]
@sk91 we decided to limit to only one personal profile, right? 
So, there is probably a bug upstream that caused the two pers profiles being created that needs to be fixed ("clicking the new profile several times").

**Comment by sk91** [comment]
@andregoncalves  it is limited only on ui level. 

It is related to the failed migration that we fixed already. Unfortunately we couldn't fix everything if there were already some new data in the wallet

**Comment by oanamangiurea** [comment]
@sk91 do you still need my answer, or we're fixing the part of only having one profile?

**Comment by sk91** [comment]
@oanamangiurea  yes, please

We will have only one profile right now. The 2 appeared due to a bug, but we cannot simply delete one randomly, so we need a solution

**Comment by oanamangiurea** [comment]
@sk91 let's go with the number then ... Susana (2), think might be the easiest approach

**Comment by andregoncalves** [comment]
Agree

**Comment by sk91** [comment]
FOR QA:

In profile list, profiles with the same name should be distinguished by number
test
test (2)
test (3) 
...

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/70609080-2b66e300-1c3c-11ea-9966-66cb8c2ef45d.png)
