### ISSUE TITLE
ID Wallet profile overview: update DIDs help link 

### ISSUE THREAD

**Issue by susananakatani** [SelfKeyFoundation/Identity-Wallet#1792]
@sk91 @CortecKYC @andregoncalves 

In "decentralised ID" update the link in "what is a DID?" to the below:
https://help.selfkey.org/article/147-what-is-a-did
<img width="1159" alt="Get DID" src="https://user-images.githubusercontent.com/41003450/67859938-ac4a9f00-fb14-11e9-8140-987f80845da7.png">

_currently it leads to the helpcenter main menu not the specific article_

**Comment by sk91** [comment]
In future we should have an airtable to control configuration like this. That way we will be able to change it without release

**Comment by rhdelima** [comment]
Looks good. Pass
