### ISSUE TITLE
CORP3: Implement corporate member icons 

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1807]
https://projects.invisionapp.com/d/main#/console/15222689/316560292/preview
https://projects.invisionapp.com/d/main#/console/15222689/386948868/preview

**Comment by sk91** [comment]
@designhorf ready for review?

**Comment by designhorf** [comment]
@sk91 all of the icons are added to SK UI and the Wallet is updated with it, but I don't know these icons are used or not in any Corporate Wallet related screens

**Comment by andregoncalves** [comment]
This should be tested in conjunction with the add corp member functionality.

**Comment by rhdelima** [comment]
@designhorf Please see issues below:
**LLC**:
- Incorrect description for Member
- `Authorized` should be `Authorised`
![image](https://user-images.githubusercontent.com/10294014/69548867-20247e00-0fd3-11ea-8b62-6a2afc845152.png)

**LLP**:
- Incorrect description for Other
![image](https://user-images.githubusercontent.com/10294014/69548457-56153280-0fd2-11ea-8056-04b77ca39bba.png)

**TRUST**:
- Incorrect description for `Beneficiary` and `Other`
- `Authorized` should be `Authorised`
![image](https://user-images.githubusercontent.com/10294014/69550512-15b7b380-0fd6-11ea-8ddc-c3c30074072b.png)

**FOUNDATION**:
- Incorrect description for `Beneficiary` and `Other`
- `Authorized` should be `Authorised`
![image](https://user-images.githubusercontent.com/10294014/69552376-536a0b80-0fd9-11ea-93c0-1c7ca945d88b.png)

**Other**
- Member should be `Company Member`
- Hide `Other`
![image](https://user-images.githubusercontent.com/10294014/69552920-3da91600-0fda-11ea-8108-33aadfef9e2b.png)

@oanamangiurea , Can I ask for the design for LTD? Thanks!

**Comment by designhorf** [comment]
@rhdelima I can fix these bugs, but this task about only icons.

**Comment by CortecKYC** [comment]
@designhorf can you point me to the task with the descriptions?

**Comment by andregoncalves** [comment]
Part of the selfkey platform:
https://github.com/SelfKeyFoundation/selfkey-platform/pull/25

https://app.zenhub.com/workspaces/selfkey-development-5a974701436f5f648c6e4801/issues/selfkeyfoundation/selfkey-platform/24

**Comment by designhorf** [comment]
@CortecKYC Selfkey UI library didn't contain some icons which are necessary to use in Corporate Wallet. So in this task I updated our UI library and the Wallet with new icons. 
In the main description @andregoncalves just shared screens (https://projects.invisionapp.com/d/main#/console/15222689/316560292/preview
https://projects.invisionapp.com/d/main#/console/15222689/386948868/preview) for me to know which icons I need to implement.

**Comment by CortecKYC** [comment]
Ok, then this task should be passed, @rhdelima Please open a new one to fix the wrong descriptions.
