### ISSUE TITLE
UI - Checklist screen

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1816]
Elements are not centre aligned (except checkboxes) in table header and rows as well.
https://gyazo.com/57c50bfe7428a2f6b12a17c576a634b2?token=4a2a175174c5d2dd88b0dc2d2d7628d7

**Comment by CortecKYC** [comment]
@rhdelima @oanamangiurea Please test

**Comment by rhdelima** [comment]
@designhorf I don't any changes with the checklist table. Still the same as the screenshot on the description.

![image](https://user-images.githubusercontent.com/10294014/68848681-ac998b80-070b-11ea-933e-7bdec03b01b5.png)

**Comment by oanamangiurea** [comment]
@designhorf in your fixed version the label column is not aligned with anything. vertical and horizontal

**Comment by designhorf** [comment]
@oanamangiurea @rhdelima label column is fixed

**Comment by rhdelima** [comment]
Looks good on my end. @oanamangiurea Let me know if you are okay with this now.

![image](https://user-images.githubusercontent.com/10294014/69257154-8a18de00-0bf5-11ea-97fb-e3f87dccc25b.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes all good, you can close it
