### ISSUE TITLE
UI - update new version widget

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1817]
Text is not vertically centred and need to remove border radius 
https://gyazo.com/77d3d66f8290238832e3fa5ecf61b054

Fixed:
<img width="1159" alt="Screenshot 2019-11-22 at 10 08 00" src="https://user-images.githubusercontent.com/7461010/69412899-128ba180-0d10-11ea-8bbf-a1dd2d317c22.png">

**Comment by CortecKYC** [comment]
@oanamangiurea Would you mind testing this ticket?

**Comment by oanamangiurea** [comment]
All good, pass
