### ISSUE TITLE
UI - Payment Received modal

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1818]
- [x] reduce width of the modal to 780px
- [x] alignment of title text
- [x] reduce title text size to 18px (`variant=body1`)
- [x] box-shadow

[https://gyazo.com/fb8e027080de22cef7d9337abb63e6f4](https://gyazo.com/fb8e027080de22cef7d9337abb63e6f4)

**Comment by rhdelima** [comment]
Testing is blocked due to error when submitting BAM and Incorporation application.

**Comment by rhdelima** [comment]
@oanamangiurea Can you confirm if you are okay with the fix now? Please see screenshots below.

![image](https://user-images.githubusercontent.com/10294014/72408071-999f4800-379c-11ea-9281-113e604a9afc.png)
![image](https://user-images.githubusercontent.com/10294014/72408091-b63b8000-379c-11ea-99f3-dd265ab98d9d.png)

**Comment by oanamangiurea** [comment]
@rhdelima not ok, box shadow is not standard. @designhorf let's talk about standardising this during our call.

**Comment by sk91** [comment]
@CortecKYC @oanamangiurea if the shadow issue will be handled in a different task, maybe this one should be closed?

Also @designhorf not only shadows need to be standardised, some popups do not use the common Popup component (I think the hardware wallet popups don't)

**Comment by designhorf** [comment]
We have a separate task for shadow issue https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2005
@sk91 I'll check popups and create a task for it

**Comment by designhorf** [comment]
Separate task is created for popups -> https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2021

**Comment by CortecKYC** [comment]
@designhorf Can you please let me know what's left to fix in this task (not including the issues and errors that have been reported in a separated task)

**Comment by designhorf** [comment]
@CortecKYC sure, modal is fixed but I didn't touch shadows, because we've already created a separate task for it https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2005 (fix shadows on all modals).
And as @sk91 mentioned, popup need to be standardised as well, so this task was created for it https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2021

**Comment by CortecKYC** [comment]
@designhorf So, what's left to fix in this ticket? Is there anything or can we close it?

**Comment by designhorf** [comment]
We can close it.
