### ISSUE TITLE
Collapsed menu hoover

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1827]
On the collapsed version of the menu, we were supposed to display the menu item name as html title on hover, so the user should not expand the menu to know what is there. Currently it doesn't happen

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/69384632-bd439600-0cf7-11ea-9a24-cd69844804d7.png)
