### ISSUE TITLE
Title of Selfkey ID page

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1828]
The title of the selckey profile page is wrong. It says SelfKey Identity Wallet, and correct is SelfKey Profile, as in invision https://gyazo.com/f963fcf7495db44a4ddc9d55d849b239

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/69248245-e7f1f980-0be6-11ea-95e4-c52f2745577e.png)
