### ISSUE TITLE
Fix not enough KEY modal

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1830]
Current modal form the wallet is not spaced well, and lacks some information for our users. [https://gyazo.com/2504f8a88c080af8d123932cd51c98a3](https://gyazo.com/2504f8a88c080af8d123932cd51c98a3)

It should look like the one here [https://projects.invisionapp.com/d/main#/console/15222689/381825690/preview](https://projects.invisionapp.com/d/main#/console/15222689/381825690/preview)

**Comment by rhdelima** [comment]
@designhorf Failing this one. Issue is NOT fixed. Design is NOT followed.
build: dev_2019.11.19.10

![image](https://user-images.githubusercontent.com/10294014/69250689-1b368780-0beb-11ea-8d04-5660fae6010a.png)

**Comment by rhdelima** [comment]
@designhorf Failing this one again. Please see remaining issues:
1. Amount of KEY is incorrect
2. Update `Your Address` to `Your Address to receive KEY`
3. Not sure if list of exchanges are updated. 
4. Not part of the ticket but when closing modal, it goes back to dashboard instead of the previous screen.

http://recordit.co/fber41vNKB

**Comment by CortecKYC** [comment]
@designhorf Regarding #3: List of exchanges is here https://confluence.kyc-chain.com/display/OFH/Selfkey+%28KEY%29+-+Exchange+Listings. There are 16 exchanges now where users can get KEY.

cc: @oanamangiurea

**Comment by oanamangiurea** [comment]
@designhorf because of big number of exchanges, please display them on 3 columns

**Comment by CortecKYC** [comment]
New ticket to populate the list above dynamically: https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1834

**Comment by rhdelima** [comment]
Looks good. Pass
