### ISSUE TITLE
Dynamically populate list of exchanges where users can get KEY

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#1834]
Populate the list below dynamically (since some exchanges will be added/removed over time).

- **Airtable with the list of exchanges where users can get KEY:** https://airtable.com/tblvZFOVjOXnE9Q7b/viwHHQAZp86BQdGGv
(Source of airtable data: https://confluence.kyc-chain.com/display/OFH/Selfkey+%28KEY%29+-+Exchange+Listings)

![list.png](https://images.zenhubusercontent.com/5c6a709f9d62b128eab3a3a5/0b5fd76a-b90e-48b4-bd0f-bc221c5bbfdb)

**Comment by sk91** [comment]
- [ ] airtable
- [ ] migration
- [ ] model
- [ ] service
- [ ] sync job
- [ ] redux layer
- [ ] ui

**Comment by rhdelima** [comment]
Looks good now.

![image](https://user-images.githubusercontent.com/10294014/73519872-20ab1c00-443d-11ea-8185-db1152978244.png)
