### ISSUE TITLE
Call user create on application create

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1838]
KYCC api was updated, we need to call to users endpoint now before create application

- `GET /users/me` -- fetch user
- `POST /users/` -- create user
- new endpoint for lws `/lws_users` 

@felipewer said:

Passing by to let you guys know that we made some internal changes and additions to the KYC-Chain internal API (The one the wallet uses) and they where merged to master today. This means the dev instance has the changes and it will break new application creation flow with the wallet. No production instance has the changes yet.
These changes are related to user creation. In short now the wallet will have to explicitly call POST /users to create a user before creating an application.
We talked about this during a call weeks ago, but you thought you might not recall.
We still have to redeploy the updated API docs. So meanwhile you can check them ou heading to https://editor.swagger.io/ and pasting in the content of this file: https://github.com/kyc-chain/kyc-chain-monorepo/blob/master/api/docs/internal-spec.yml

**Comment by sk91** [comment]
@CortecKYC transferred

**Comment by sk91** [comment]
FOR QA:

Test marketplace applications with dev instance and new DID

**Comment by CortecKYC** [comment]
@rhdelima Please test

**Comment by CortecKYC** [comment]
@rhdelima Please test asap.
FOR QA:

Test marketplace applications with dev instance and new DID

**Comment by rhdelima** [comment]
@sk91 
Still getting an error.
![image](https://user-images.githubusercontent.com/10294014/69231131-83717300-0bc3-11ea-9c3c-62f043df94bf.png)

**Comment by CortecKYC** [comment]
@sk91 I'm sending this back to In Progress.
