### ISSUE TITLE
Table alignement issue

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1849]
Please left align the items in the Fiat Payments column from exchanges

https://gyazo.com/02551edb7764a325f51d75faddc43f9b

**Comment by rhdelima** [comment]
Looks good now. Pass

![image](https://user-images.githubusercontent.com/10294014/69252434-f263c180-0bed-11ea-9ccc-2a02d8589f75.png)
