### ISSUE TITLE
Exchanges MP: If there isn't affiliate link, add plain link to the exchange website

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#1850]
Decided on Product call Oct. 18, 2019 (https://confluence.kyc-chain.com/display/PD/Product+Call):
"For now just add plain links to their websites"

**Comment by andregoncalves** [comment]
@CortecKYC PR in for review, please note that I kept the same button text (see screenshot below), but text can be changed for non-affiliates (or affiliates) links.

![Screenshot 2019-11-18 at 11.54.49.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/fd9ccde6-1d41-401d-94fd-82a909a9300d)

**Comment by CortecKYC** [comment]
@andregoncalves How is the affiliate text managed?
For example, if tomorrow I add a new affiliate link for one of the existing exchanges to the airtable, will the text show up automatically?

**Comment by andregoncalves** [comment]
Affiliate link has priority:
- If there is an affiliate URL, the affiliate button (+ disclaimer) will be displayed.
- Otherwise, if there is an exchange URL, it will be displayed like the screenshot above
- If no affiliate URL or exchange URL exists, nothing will be displayed.

**Comment by CortecKYC** [comment]
Awesome! Great!

**Comment by rhdelima** [comment]
@andregoncalves 
For Serenity and ADAX, affiliate disclaimer is shown when button doesn't contain an affiliate link.

![image](https://user-images.githubusercontent.com/10294014/69556372-8e6f3d80-0fdf-11ea-8d94-cbade2382d47.png)

**Comment by CortecKYC** [comment]
@rhdelima Please test again

**Comment by rhdelima** [comment]
Looks good. Pass
