### ISSUE TITLE
Dev: KEY and ETH Balance don't update after transaction

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#1856]
Reported by Ben

[https://images.zenhubusercontent.com/5c6a709f9d62b128eab3a3a5/4b10066f-7fc7-474c-9425-24a0a15b9782](https://images.zenhubusercontent.com/5c6a709f9d62b128eab3a3a5/4b10066f-7fc7-474c-9425-24a0a15b9782)

[https://user-images.githubusercontent.com/47594955/69048733-80795580-09fe-11ea-9580-4c7791a384c5.png](https://user-images.githubusercontent.com/47594955/69048733-80795580-09fe-11ea-9580-4c7791a384c5.png)

**Comment by sk91** [comment]
duplicate #2359
