### ISSUE TITLE
Last token price - update text

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1861]
In manage my tokens table, the values for the column "Last price" should display the currency, in this case USD.

So "182.69" will become "$ 182.69 USD"

[https://gyazo.com/26c6ec4277c1fde1de1b282c1c43ed2f](https://gyazo.com/26c6ec4277c1fde1de1b282c1c43ed2f)

**Comment by rhdelima** [comment]
@oanamangiurea Can you confirm if you're good with this? Your example is `$ 182.69 USD` but implementation has missing space (ex. `$182.69 USD` - missing space)


![image](https://user-images.githubusercontent.com/10294014/74649529-bc1cea80-51ba-11ea-887f-7cd58f6616a0.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, all good
