### ISSUE TITLE
Member equity validation

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1865]
User CorporateStructureSchema.getEquityForCompanyType

**Comment by rhdelima** [comment]
@andregoncalves Can you provide some instruction on how to test this? Thanks!

**Comment by andregoncalves** [comment]
Some positions require equity, some don't, that needs to be tested.
Also, we need to test that only valid equity values are allowed.

**Comment by rhdelima** [comment]
@andregoncalves Do you have list of roles require equity? Based on my testing, only `Member` role has shares. Also, I can save a member (with role = `Member`) with 0 equity. Shouldn't we require `> 0` equity? Thanks!

**Comment by sk91** [comment]
```
	'director-ltd': false,
	'director-fnd': false,
	shareholder: 'Shares',
	ubo: false,
	observer: false,
	authorizedSignatory: false,
	manager: false,
	member: 'Membership Interest',
	'member-llc': 'Membership Interest',
	grantor: false,
	'beneficiary-tst': false,
	'beneficiary-fnd': false,
	trustee: false,
	protector: false,
	founder: false,
	'general-partner': 'Percentage',
	'limited-partner': 'Percentage'
```

Every position that does not have "false" has equity

**Comment by rhdelima** [comment]
Looks good. Pass
