### ISSUE TITLE
Add support for Ledger 1.6.0 firmware

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1871]

**Comment by sk91** [comment]
For QA:
tested on 1.5.5 and 1.6.0
Dont forget to allow contract data after upgrade

**Comment by rhdelima** [comment]
QA is blocked.
![image](https://user-images.githubusercontent.com/10294014/70991865-61f0a200-2103-11ea-858e-814bed706444.png)

**Comment by CortecKYC** [comment]
Should be ready to QA after https://github.com/SelfKeyFoundation/Identity-Wallet/pull/1956 is done.

**Comment by rhdelima** [comment]
@sk91 @andregoncalves https://github.com/SelfKeyFoundation/Identity-Wallet/pull/1956 was already merged but I still can't connect to ledger. 

![image](https://user-images.githubusercontent.com/10294014/71527217-5d9f6280-2915-11ea-9e21-6e1b498e18aa.png)

**Comment by andregoncalves** [comment]
@sk91 any idea what is causing this?

**Comment by sk91** [comment]
@rhdelima when is this happening? When you try to sign in or when you try to do a transaction?

**Comment by rhdelima** [comment]
@sk91 Still not working on my end using the latest build. Unable to unlock wallet using ledger v.1.6.0
http://recordit.co/Rt7EhOv5eA

**Comment by sk91** [comment]
Can confirm it happens on dev build for me but not while running `yarn dev`
Probably something related to the new standard that ledger is using for deriving addresses.
Upgrade to web3-provider 5.3.0 should fix it, but it is a rabbithole with web3 and everything related to it needs to be upgraded as well

@andregoncalves

**Comment by CortecKYC** [comment]
@andregoncalves @sk91 What do we have to do to fix this?

**Comment by andregoncalves** [comment]
We need to plan web3 lib update.

**Comment by CortecKYC** [comment]
@andregoncalves The task has been waiting since last summer: https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1507

**Comment by sk91** [comment]
blocked by a bug in ledger web3 subprovider
tracked here: https://github.com/LedgerHQ/ledgerjs/issues/451

**Comment by CortecKYC** [comment]
@sk91 Can we close this ticket?

**Comment by sk91** [comment]
@rhdelima this can be closed right, no issues on 1.6.0 anymore?

**Comment by rhdelima** [comment]
Yes. This can be closed.
