### ISSUE TITLE
Update Corp member descriptions

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1879]
**LLC** : 
- Incorrect description for Member 
- `Authorized` should be `Authorised` [https://user-images.githubusercontent.com/10294014/69548867-20247e00-0fd3-11ea-8b62-6a2afc845152.png](https://user-images.githubusercontent.com/10294014/69548867-20247e00-0fd3-11ea-8b62-6a2afc845152.png)

**LLP** : 
- Incorrect description for Other 
[https://user-images.githubusercontent.com/10294014/69548457-56153280-0fd2-11ea-8056-04b77ca39bba.png](https://user-images.githubusercontent.com/10294014/69548457-56153280-0fd2-11ea-8056-04b77ca39bba.png)

**TRUST** : 
- Incorrect description for `Beneficiary` and `Other` 
- `Authorized` should be `Authorised` [https://user-images.githubusercontent.com/10294014/69550512-15b7b380-0fd6-11ea-8ddc-c3c30074072b.png](https://user-images.githubusercontent.com/10294014/69550512-15b7b380-0fd6-11ea-8ddc-c3c30074072b.png)

**FOUNDATION** : 
- Incorrect description for `Beneficiary` and `Other` 
- `Authorized` should be `Authorised` [https://user-images.githubusercontent.com/10294014/69552376-536a0b80-0fd9-11ea-93c0-1c7ca945d88b.png](https://user-images.githubusercontent.com/10294014/69552376-536a0b80-0fd9-11ea-93c0-1c7ca945d88b.png)

**Other** 
- Member should be `Company Member` 
- Hide `Other` [https://user-images.githubusercontent.com/10294014/69552920-3da91600-0fda-11ea-8108-33aadfef9e2b.png](https://user-images.githubusercontent.com/10294014/69552920-3da91600-0fda-11ea-8108-33aadfef9e2b.png)

**Comment by andregoncalves** [comment]
Authorized vs Authorised dilemma: https://english.stackexchange.com/questions/282621/authorization-vs-authorisation-im-in-some-real-dilemma

Should we opt for the formal EN-UK spelling?

**Comment by CortecKYC** [comment]
@andregoncalves Whichever we pick, we must be consistent.
In this case, I would go for the formal EN-UK spelling (with 's'), but like I said, it really doesn't matter as long as we are consistent and we use always the same one.

**Comment by andregoncalves** [comment]
@oanamangiurea we have an implementation problem regarding the descriptions.
The members descriptions are part of the selfkey platform schemas: https://github.com/SelfKeyFoundation/selfkey-platform/blob/master/resolved-dev-repository.json

Some of the positions are reused between entity types, for example the "other" member position is reused on LLCs, Foundations, etc. But we only have one description.
Adding type specific member descriptions is going to complicate an already complex schema, can we rephrase them to be generic and common to all entity types?

**Comment by oanamangiurea** [comment]
@andregoncalves  not really, that is where we started from and the product decision was that is not good enough, when we decided to go with current implementation. We can discuss more today

**Comment by andregoncalves** [comment]
@sk91 after some discussion today, we agreed that members positions with the same name should not be shared between company types.

**Comment by CortecKYC** [comment]
Good decision! It didn't make any sense to share the descriptions.

**Comment by andregoncalves** [comment]
@sk91 can you update the schema accordingly?

**Comment by sk91** [comment]
@andregoncalves I would like to share as much as possible and to separate on need to need basis.

Can you list the members and descriptions that I absolutely must separate?

Is it only members?

**Comment by andregoncalves** [comment]
I think it's better to separate all, so no common members in the schema between company types (even if they have the same name and/or description).

**Comment by sk91** [comment]
@andregoncalves this will bloat the schema too much, it is already complicated

**Comment by sk91** [comment]
I don't see the reason to multiply by 6 the amount of records for 
```
 { "$ref": "#/definitions/positions/ubo" },
          { "$ref": "#/definitions/positions/observer" },
          { "$ref": "#/definitions/positions/authorizedSignatory" },
          { "$ref": "#/definitions/positions/other" }
```

**Comment by rhdelima** [comment]
@andregoncalves @sk91 Please see remaining issues:

LTD:
- Incorrect description for Director
- Incorrect icon for Shareholder
![image](https://user-images.githubusercontent.com/10294014/70825933-940eb500-1e20-11ea-80e3-853e9dec6b82.png)

LLP:
- Incorrect icon for `General Partner`
- Remove `that` under General Partner
![image](https://user-images.githubusercontent.com/10294014/70827287-e0a7bf80-1e23-11ea-8f65-1f6888c924e1.png)

Other:
- Remove `that` under Company Member
![image](https://user-images.githubusercontent.com/10294014/70827497-53b13600-1e24-11ea-8ccd-5f6e5bec844c.png)

**Comment by rhdelima** [comment]
Looks good now. Pass
