### ISSUE TITLE
Mac builds not working on CI

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1888]

**Comment by andregoncalves** [comment]
@sk91 I don't see any mac builds yet... I monitoring a build for the last hour and it's still going...

**Comment by sk91** [comment]
@andregoncalves reopenning it

**Comment by andregoncalves** [comment]
https://mattermost.kyc-chain.com/kyc-chain/pl/7etdocr8oig49gz96iua5f889e

Build was deployed, I think this is fixed.

**Comment by rhdelima** [comment]
@CortecKYC Can we close this one?
