### ISSUE TITLE
Backdrop opacity

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1894]
Reduce opacity of backdrop to give more focus on popups.

Current version: 
![Screenshot 2019-11-27 at 15.41.04.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/2eb3f648-0eb0-4cf1-841c-4768eb912573)

Fixed one:
![Screenshot 2019-11-27 at 15.40.47.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/c3f302f8-dfd0-4015-9208-fb32ed33882a)

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/70619058-31b28a80-1c4f-11ea-8b5f-99e6123c543c.png)
