### ISSUE TITLE
UI - Bank Account Process Started modal

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1895]
- [x] reduce width of the modal to 780px
- [x] alignment of title text
- [x] box-shadow

![Screenshot 2019-11-28 at 10.32.19.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/f6dbf395-1483-47a5-a8a4-c485a5288599)

**Comment by rhdelima** [comment]
Testing is blocked due to https://github.com/kyc-chain/kyc-chain-monorepo/issues/1181

![image](https://user-images.githubusercontent.com/10294014/70647277-9091f700-1c83-11ea-9e49-72be459a6681.png)
![image](https://user-images.githubusercontent.com/10294014/70647295-98519b80-1c83-11ea-9c6b-563c2baa0330.png)

**Comment by rhdelima** [comment]
@oanamangiurea How about this as well? are you good with this?See screenshots.

![image](https://user-images.githubusercontent.com/10294014/72408213-1a5e4400-379d-11ea-9359-cf8d52233818.png)

![image](https://user-images.githubusercontent.com/10294014/72408342-85a81600-379d-11ea-8922-418ff987298d.png)

**Comment by oanamangiurea** [comment]
@rhdelima no, there are still some issues. But the centring on the screen can be left like that @designhorf please see the following:

![modal-fixes](https://user-images.githubusercontent.com/5183519/72417378-72874d00-3781-11ea-82b1-8f578075357b.png)

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/74658485-656cdc00-51cd-11ea-9e82-23baa6f43201.png)

![image](https://user-images.githubusercontent.com/10294014/74659166-c3e68a00-51ce-11ea-995a-fec36fc6b3e1.png)
