### ISSUE TITLE
No profile attributes on company individual members

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1899]
Missing info like first name, last name, email from

[https://gyazo.com/860c657dce3f95681a8027a8ee905be3](https://gyazo.com/860c657dce3f95681a8027a8ee905be3)

**Comment by sk91** [comment]
<img width="1056" alt="Screenshot 2019-12-09 at 12 03 21" src="https://user-images.githubusercontent.com/1021965/70426599-fad84b00-1a7b-11ea-99f5-18dac0b9e554.png">

**Comment by rhdelima** [comment]
Looks good now. Pass

![image](https://user-images.githubusercontent.com/10294014/70833548-0b4d4480-1e33-11ea-8ffa-67d2e69fb5d3.png)
