### ISSUE TITLE
Min Height of calendar

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1901]
Calendar picker has too much space at the bottom, because the min-height is too big

https://gyazo.com/681a71aba2dafea5d3690086128ed994

**Comment by rhdelima** [comment]
@designhorf Failing this one. There is still a big space below calendar when editing Date of Incorporation

![image](https://user-images.githubusercontent.com/10294014/70611073-97971600-1c3f-11ea-84df-32703340214d.png)

**Comment by andregoncalves** [comment]
@rhdelima I think the fix for this is only available on the latest release deployed this morning.

**Comment by rhdelima** [comment]
oh my bad. I'll move this back to QA

**Comment by rhdelima** [comment]
Looks good now. pass

![image](https://user-images.githubusercontent.com/10294014/70615291-1774ae80-1c47-11ea-8282-d812f485594e.png)
