### ISSUE TITLE
Company Registration Number validation error

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1902]
https://gyazo.com/4481786596d5b95764512c6d4256b389

Integer doesn't say much for a normal user.

And the registration number is not only an integer in real life, but a string. Ex in Romania registrations numbers are like: J40/xxxxx

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/70607754-01142600-1c3a-11ea-9ae4-16c724b12d61.png)
