### ISSUE TITLE
Fix members table scroll

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1903]
https://gyazo.com/dbf1a6bffe9b4b31dd44f6562c85eeb8 

Fix horizontal scroll in manage members tab

Also the first 2 columns are too wide (the one with expand/collapse arrow and the one with icon), they should be smaller, as in the design

![table_scroll](https://user-images.githubusercontent.com/47594955/70131591-da2a8280-1682-11ea-8b21-dea8329beae3.png)

**Comment by designhorf** [comment]
This bug is fixed with https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1679

**Comment by rhdelima** [comment]
Looks good now. Pass

![image](https://user-images.githubusercontent.com/10294014/70639139-ffb41f00-1c74-11ea-88db-dcfaf00e39d5.png)
