### ISSUE TITLE
UI issues add member modal

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1905]
1. Buttons (continue and cancel), on add or edit members modal, should be aligned to the left as in the design
2. Please put the shares amount on a new line, as in the design
3. Remove the horizontal rule from the bottom, before the design 
4. Email should be required - we will need it later on for inviting people to use the wallet, or for Gnosis Safe

**Comment by rhdelima** [comment]
@oanamangiurea This looks good to me except that Continue and Cancel button have different sizes. Let me know if we can close this one.

![image](https://user-images.githubusercontent.com/10294014/70637203-d0e87980-1c71-11ea-955e-fdab84739d0c.png)

**Comment by oanamangiurea** [comment]
@rhdelima good enough for me, closing it
