### ISSUE TITLE
Add members table UI Fixes

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1906]
1. When hovering over the expand/collapse arrows we need to show cursor:pointer
2. Clicking on Edit button - round grey background is not centred 
3. We should add a confirm deletion, like we have in the id profile https://gyazo.com/e5603093f8920b078c73f3e1e59308bb 

![delete_information](https://user-images.githubusercontent.com/47594955/70139663-3eedd900-1693-11ea-8785-1221fc7dc4b2.png)

**Comment by rhdelima** [comment]
@designhorf Issue 3 is NOT working. See recording: http://recordit.co/ou742tHsMq

**Comment by CortecKYC** [comment]
@designhorf Do you think you can fix this before your holiday? We want to release Corporate Wallet next week and it would be great to get this fixed before.

**Comment by designhorf** [comment]
@CortecKYC I'll check it today.

**Comment by rhdelima** [comment]
Looks good. Pass
