### ISSUE TITLE
Member Register attribute

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1907]
When adding a document type "Member Register" under a company, we shouldn't ask for its members. It's just a document, that is tied to the company, and the document already lists the members. 

https://gyazo.com/bbad1acfbb34a5e3904bdf03b067c80e 

![member_register](https://user-images.githubusercontent.com/47594955/70139855-b15eb900-1693-11ea-9f80-d96b97f05144.png)

**Comment by andregoncalves** [comment]
@sk91 can you work on this?
Everything below the label Members* can be removed.

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/70834383-291ba900-1e35-11ea-91ad-d0ef07e50271.png)
