### ISSUE TITLE
Creating a new company don't pre-fill any id attributes

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1908]
1. When creating a new company (1st, 2nd, etc) don't pre-fill any of the id attributes from the current one - aka mail, name, etc, anything. 
In this screen I mean https://gyazo.com/ac36645a4db8bc2561c07c4394ca1766 

![prefill](https://user-images.githubusercontent.com/47594955/70140001-0dc1d880-1694-11ea-88cb-f8a9c5fa5931.png)

2. Also, the Legal entity Type dropdown is missing its placeholder. It should be Choose...

**Comment by rhdelima** [comment]
Failing this one.
1. Fixed. Passed
2. Failed
![image](https://user-images.githubusercontent.com/10294014/71473603-93a7ee00-2812-11ea-91d0-858278063c8f.png)

**Comment by rhdelima** [comment]
Looks good now. Pass
![image](https://user-images.githubusercontent.com/10294014/71897938-fb572500-3192-11ea-834a-5425335f595a.png)
