### ISSUE TITLE
Members type validation

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1909]
This: https://gyazo.com/3c8904c0924d9e983d32000da9f0b579 :(((

![member_type_validation](https://user-images.githubusercontent.com/47594955/70141524-86766400-1697-11ea-8039-39e1f8a9ffb5.png)

**What we need to change overall in terms of validations:**

1. Continue button should never be disabled
2. If the user hasn't filled all information we will display a message above the buttons saying: Please fill all the required pieces of information above
3. For the members is enough to have a message under the boxes saying: Please select one or more roles
4. Get rid of that ugly red rectangle
5. We should fit 4 boxes per row

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/70566037-3edb6500-1bce-11ea-9fc7-28cd526fc391.png)
![image](https://user-images.githubusercontent.com/10294014/70566322-caed8c80-1bce-11ea-8d54-8e7a054be3cc.png)
