### ISSUE TITLE
CORP5: sync corporate inventory with database

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1912]

**Comment by rhdelima** [comment]
@sk91 can you share steps on how to test this?

**Comment by sk91** [comment]
@rhdelima sure,

For QA:

- in airtable, in ventorsDev add a new vendor with entity type "corporate" (there are examples to copy from) make sure to give it unique 'vendor_id'
- in airtable, in inventoryDev add one or several inventory items (make sure to connect to the new vendor_id and give each inventory item unique sku for that vendor)
- start wallet with FORCE_DEV_MODE=1 to load data from dev tables
- see that new inventory is in marketplace
- remove the new inventory and vendors
- see that they are gone on wallet restart

**Comment by rhdelima** [comment]
@sk91 Can you confirm if this is the correct airtable to use on dev? I can't find entity type column in this table. I don't have edit access as well.
https://airtable.com/tblEF1AnXKq6UbwkO/viwU048CIOqdj5BIu?

**Comment by andregoncalves** [comment]
No, that's the old airtable.
Invite was sent to ralph@kyc-chain.com for the new one

**Comment by rhdelima** [comment]
@sk91 I updated the airtable as instructed however I can't view marketplace using corporate profile since we're displaying `Coming Soon`
![image](https://user-images.githubusercontent.com/10294014/73336515-faef0d00-42ac-11ea-842d-c06add0cd091.png)

**Comment by rhdelima** [comment]
QA is currently blocked. Marketplace is not enabled yet on corporate profile.

**Comment by sk91** [comment]
@rhdelima what is the status of this issue?
