### ISSUE TITLE
CORP5: display different categories in marketplace for corporate and individual

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1914]
fixed in #1942

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/71087071-42767980-21d6-11ea-9d3f-d04a4d373f5e.png)
![image](https://user-images.githubusercontent.com/10294014/71087086-4bffe180-21d6-11ea-9e45-62512b5cb8fe.png)
