### ISSUE TITLE
Shape Up: LWS Integration for non-KYCC customers

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#1915]
- [x] 1. Shape up project
- [ ] 2. Create tickets in Github

As per https://confluence.kyc-chain.com/display/DEV/Exchanges+Integration+Strategy, we need to develop a simplified API and client library.

That way we will simplify the flow as much as possible, and provide customers with tools to make the integration and be able to seamlessly upgrade when we make any changes.

**Comment by sk91** [comment]
https://confluence.kyc-chain.com/display/SEL/BET%3A+Selfkey+SDK+-+LWS

**Comment by CortecKYC** [comment]
Shaped up in Confluence.
We still need to create the tickets in Github
