### ISSUE TITLE
CORP5: display corporate requirements in corporate offers page

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1916]

**Comment by rhdelima** [comment]
@sk91 Is this ticket refers to this screen? Please confirm. Also, I think we need to update required attributes since these ones are not for corporate.

![image](https://user-images.githubusercontent.com/10294014/71087564-74d4a680-21d7-11ea-889e-12660901ea58.png)

**Comment by sk91** [comment]
@rhdelima , yes, and it's find for now. We will be building a special template for next bet. 

For now this looks ok

**Comment by rhdelima** [comment]
@sk91 Thanks. Closing this now.
