### ISSUE TITLE
What issue tracker is being used?

### ISSUE THREAD

**Issue by jonrh** [SelfKeyFoundation/Identity-Wallet#193]
From the names of the pull requests (sel-33, sel-32, etc) it seems you are using an external issue tracker. Which one is it and can we get an open access to it so we can better track the context of the work you are performing?

**Comment by altninja** [comment]
we are using JIRA, I don't know if its possible to make it public or not but moving forward commits should be formatted with much more detail following commitizen pattern etc...

**Comment by dfcowell** [comment]
@jonrh we're starting to move our ongoing wallet development to Github now that the wallet beta has been released. Hope you enjoy this increased level of transparency.

Thanks for your interest in the project and hope you're still following along!

**Comment by jonrh** [comment]
Thanks @altninja & @dfcowell for your responses. I am indeed still following along. Moving completely to GitHub is a really good transparency move, thank you!
