### ISSUE TITLE
CORP5: Corporate members attributes

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1959]
When clicking on add attribute for corporate members, the popup is tied to the root component instead of member.

So attributes are created on root company

**Comment by sk91** [comment]
FOR QA:

Please check that when you add new attributes to members (information or documents), they are added to the member, not the parent company

also check that for company attribute addition works

And for personal profile

**Comment by rhdelima** [comment]
@sk91 Failing this one. Can you share what env variable (if any) to enable this functionality?

Build: dev_2019.12.19.11
http://recordit.co/iUAiR6lWFr
