### ISSUE TITLE
CORP: Fix Shares on UI

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1965]
1. Should show % shares (ex. 10%) on the following table:

    - Entity Membership (under Manage Members)
    - Cap Table [https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/b2d021d5-c297-4336-aae1-686d9ed00f07](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/b2d021d5-c297-4336-aae1-686d9ed00f07) [https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/bebd7c3c-6920-4e8f-917e-fa054ce78117](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/bebd7c3c-6920-4e8f-917e-fa054ce78117)
2. Shareholding Graph should only show `Shareholder (% of shares)` [https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/bb0a5d9b-3267-4858-ac03-62d2d1444fe6](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/bb0a5d9b-3267-4858-ac03-62d2d1444fe6)

**Comment by andregoncalves** [comment]
@oanamangiurea can you confirm that shares is always a % value. I might be confused, but I remember a discussion about this.

**Comment by CortecKYC** [comment]
@oanamangiurea Can you answer Andre's question above, please?

**Comment by andregoncalves** [comment]
ping @oanamangiurea

**Comment by oanamangiurea** [comment]
@CortecKYC @andregoncalves actually this is a question for Edmund I think, but we should think maybe to allow both. In KYCC we had customers who needed one or the other, plus for very big companies, it's easier to just say the number of shares rather than a percentage (which can be like 0,1% or 3,999999..9 % etc)

**Comment by sk91** [comment]
@CortecKYC @oanamangiurea I believe for big companies, only the big players are needed for kyc purposes

**Comment by oanamangiurea** [comment]
@sk91 that is true, usually those above 10%, but for now we don't impose that when creating the cap table (or maybe we should, hmm)

**Comment by sk91** [comment]
Let's leave it at % until we have a precedent., no need to overthink it

**Comment by rhdelima** [comment]
Looks good. Pass
