### ISSUE TITLE
When creating individual or corporate profile, Label saves Content value

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#1968]
http://recordit.co/SXIXvU22Ld

**Comment by andregoncalves** [comment]
I think this is the correct behaviour.
@oanamangiurea any input regarding this? Should label be empty?

**Comment by oanamangiurea** [comment]
@andregoncalves it is not the correct behaviour. See personal profile. There when adding the first basic information, the label is the same as the attribute name, not content [![Screenshot from Gyazo](https://gyazo.com/2e0847432f50b5846b03c91b42de01ee/raw)](https://gyazo.com/2e0847432f50b5846b03c91b42de01ee)

**Comment by sk91** [comment]
I changed the label to be equal to content on account creation. Does not
make sense to display the same text twice

**Comment by sk91** [comment]
It is still a label though

**Comment by oanamangiurea** [comment]
@rhdelima @andregoncalves considering Max comment, then it's desired behaviour

**Comment by rhdelima** [comment]
@CortecKYC Based on the discussion above, I think we can close or reject this one.
