### ISSUE TITLE
Marketplace - More informations before clicking CTA button

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1970]
Users have complained that they don't know what they get for different marketplace services. While we had the information available, you would only see it after clicking, incorporate or open bank account, actions that were associated with a price.

Fix: we'll get the information available in that modal and we'll have it displayed as first tab in the listing. That tab text is in uppercase and bold, to be easily spotted. Attention: we'll still display the modal as well

https://projects.invisionapp.com/d/main#/console/15222689/399045026/preview

**Comment by rhdelima** [comment]
Looks good. Pass
