### ISSUE TITLE
Marketplace Flow BUG

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1971]
Compared to the designs, we are displaying not enough KEY modal too soon. If I click on incorporation button or open bank account button I should see the what you get modal, with the cost displayed at the button, meaning these screens: https://projects.invisionapp.com/d/main#/console/15222689/361135235/preview and https://projects.invisionapp.com/d/main#/console/15222689/345775295/preview

Only then we should get the not enough KEY or ETH modal. Users have complained that they don't know what they are getting for the money.

**Comment by CortecKYC** [comment]
@andregoncalves What's the status of this ticket?

**Comment by andregoncalves** [comment]
It's on PR review, I was waiting for @sk91 to return to review it:
https://github.com/SelfKeyFoundation/Identity-Wallet/pull/2017

**Comment by rhdelima** [comment]
Looks good. Pass
