### ISSUE TITLE
Change corporate wizard input label

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1973]
Small change, in the company wizard change the label from "Creation Date" to "Incorporation Date" 

Updated screen https://projects.invisionapp.com/d/main#/console/15222689/316560291/preview

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/71898156-8fc18780-3193-11ea-8815-674af5018dd6.png)
