### ISSUE TITLE
Jurisdictions lists is incomplete

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1974]
List of United States states is incomplete. It shows nothing after New York 

https://gyazo.com/a63ca90f31e744f0cea2fb7c1872488d

**Comment by andregoncalves** [comment]
They are missing from the attribute definition: https://github.com/SelfKeyFoundation/selfkey-platform/blob/master/dev-schema/attribute/legal-jurisdiction.json

@oanamangiurea where do I get the list of missing ones?

**Comment by oanamangiurea** [comment]
@andregoncalves  https://en.wikipedia.org/wiki/U.S._state

**Comment by rhdelima** [comment]
@oanamangiurea Looks good on my end now. Let me know if we can close this one now.

![image](https://user-images.githubusercontent.com/10294014/71883172-ca65f880-3170-11ea-9d0a-2847f89fc0b4.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, all good, you can close it
