### ISSUE TITLE
Get Key modal

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1980]
https://projects.invisionapp.com/d/main#/console/15222689/399057839/preview

This task connects to this one https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1946

**Comment by rhdelima** [comment]
@designhorf Please see issues below:
1. Typo errors (`parners` , `accesing`)
2. Incorrect link. It redirects to `what is did` article

![image](https://user-images.githubusercontent.com/10294014/74636051-2e350580-51a2-11ea-9bb9-a3791455d234.png)

**Comment by rhdelima** [comment]
@designhorf Can you fix this the spacing between the columns to match design?

![image](https://user-images.githubusercontent.com/10294014/75303082-af635b00-587a-11ea-8f14-7955b30181dc.png)

**Comment by oanamangiurea** [comment]
@rhdelima no need for a fix, it's ok like that. Is there any other problem beside it? If not this is passed from my side

**Comment by rhdelima** [comment]
got it @oanamangiurea . Thanks
