### ISSUE TITLE
Selfkey 1.4.4

### ISSUE THREAD

**Issue by SJablonska** [SelfKeyFoundation/Identity-Wallet#1990]
Just downloaded SelfKey-Identity-Wallet-1.4.4.AppImage

It has a wrong md5sum (I get de3c365b1e9b4a68094418b4b993fe2a)

**Comment by andregoncalves** [comment]
@SJablonska thanks for reporting it, i think it's caused by an issue we had with the build process and it's pointing to an old md5sum. We're fixing it rn.

**Comment by SJablonska** [comment]
Thx

**Comment by andregoncalves** [comment]
AppImage md5 file updated.
