### ISSUE TITLE
Miss-alignment of steps

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2001]
For KYC requirements, if we have more steps and we end up having 2 digits in the step numbering, the text is not centred anymore. See Incorporations -> Seychelles

https://gyazo.com/c2ea48c4a6ed7451247bd3c4aded77b5

**Comment by designhorf** [comment]
`dominant-baseline="middle"`
` text-anchor="middle"`

**Comment by rhdelima** [comment]
Looks good on my end. Pass

![image](https://user-images.githubusercontent.com/10294014/77448868-4268c400-6e2c-11ea-9512-1f20989973b3.png)
