### ISSUE TITLE
Clean up marketplace descriptions style

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2002]
Not sure why we have a border bottom for `<strong>` in different tabs descriptions, but it should not be there. 

See for example Incorporations -> Switzerland -> Services tab

https://gyazo.com/69e2627cd01e11225e89a0d58e72c89e

**Comment by rhdelima** [comment]
@oanamangiurea Let me know if you are good with this too.

![image](https://user-images.githubusercontent.com/10294014/80056487-ef7f4b00-8556-11ea-9a44-882b66415f12.png)

**Comment by oanamangiurea** [comment]
@rhdelima looks good, pass
