### ISSUE TITLE
Inconsistent behaviour/looks for Details links in tables

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2004]
See the listing of Exchanges vs listing of Bank Accounts in the marketplace. Both tables have a "Details" links per each row, and they don't have same look on hover.  Seems like one is `<button>` the other just `<span>`

On hover there should be no background, but an underline, and color changes from UI-Primary to UI-Primary-Tint. I updated the UI Guidelines with that, so we have it consistent everywhere.

**Comment by rhdelima** [comment]
Looks good. Pass
