### ISSUE TITLE
Corporate Wallet Dashboard misalignment

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2006]
These 2 boxes (Cap table and Shareholding)don't have the same width 

https://gyazo.com/63944f70ecf536f04b7881eabebc4b39

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/74650126-f89d1600-51bb-11ea-8727-2e007b1c82ed.png)
