### ISSUE TITLE
Desktop App Store -- prepare pkg build for the wallet

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#2015]

**Comment by sk91** [comment]
For QA:

Check out there is a new build for mac ending with '.pkg' extension

- test install package
- do sanity test on the wallet itself

**Comment by CortecKYC** [comment]
@rhdelima What's the status of this ticket? It's been in Progress for 27 days now

**Comment by rhdelima** [comment]
@CortecKYC I am waiting for the ledger and trezor send transaction fix. So far no other issue is encountered.

**Comment by rhdelima** [comment]
Looks good. Pass
