### ISSUE TITLE
Refactor HeaderIcon component

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2032]

**Comment by rhdelima** [comment]
@designhorf Please provide instruction on how to test this. Thanks!

**Comment by designhorf** [comment]
@rhdelima I just simplified the code, nothing changed. But you can check marketplace applications https://projects.invisionapp.com/d/main#/console/15222689/346095675/preview and have a look at the icons in the right hand side of each rows. 
<img width="164" alt="Screenshot 2020-06-23 at 14 47 38" src="https://user-images.githubusercontent.com/7461010/85405312-8325c580-b560-11ea-9f16-2c1b3a921ffe.png">

**Comment by rhdelima** [comment]
@designhorf Please see issues below:
1. Add space between icon and status
![image](https://user-images.githubusercontent.com/10294014/85999690-1a968700-ba3f-11ea-8ef7-bacf7098ca7c.png)
![image](https://user-images.githubusercontent.com/10294014/86001475-84b02b80-ba41-11ea-9643-842e983c3618.png)

2. Incorrect Icon
![image](https://user-images.githubusercontent.com/10294014/86001138-0fdcf180-ba41-11ea-987f-35920172a2c3.png)
3. Status should be `Documents submitted`
![image](https://user-images.githubusercontent.com/10294014/86001263-39961880-ba41-11ea-84a2-81335c576f99.png)

**Comment by designhorf** [comment]
@rhdelima Could you raise a ticket for the wrong status name what you mentioned in the 3rd point (Status should be Documents submitted), please? HeaderIcon component handles only icons.

**Comment by rhdelima** [comment]
Looks good. Pass
