### ISSUE TITLE
Fix Copy button

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2033]
Current style of the button is: [https://user-images.githubusercontent.com/7461010/74011994-7fb2e880-4989-11ea-8897-77a0395acd7b.png](https://user-images.githubusercontent.com/7461010/74011994-7fb2e880-4989-11ea-8897-77a0395acd7b.png)

Need to be convert like this: [https://user-images.githubusercontent.com/7461010/74012029-90635e80-4989-11ea-97f2-71073a56e4bb.png](https://user-images.githubusercontent.com/7461010/74012029-90635e80-4989-11ea-97f2-71073a56e4bb.png)

**Comment by rhdelima** [comment]
@oanamangiurea Please confirm if you're good with this. See screenshot below.

![image](https://user-images.githubusercontent.com/10294014/82310967-a86e6380-99f7-11ea-8134-8971684f80fd.png)

**Comment by oanamangiurea** [comment]
@rhdelima looks fine
