### ISSUE TITLE
Refactor InputTitle 

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2037]
Some of the components use same styled title for inputs. Same `InputTitle` component is created in few different files. eg. 
`Member corporate form`,
`Member individual form`,
`Member shares form`,
`Advanced transactions`, etc.

**Comment by rhdelima** [comment]
@designhorf May I know how to test this?

**Comment by designhorf** [comment]
@rhdelima it's a refactoring task so I just simplified the code, but you can check the following screens (these are affected). Using the same component for Input titles, like (`Legal Jurisdiction`, `Legal Entity Name`, `Legal Entity Type`, etc.)
- https://projects.invisionapp.com/d/main#/console/15222689/316560291/preview
- https://projects.invisionapp.com/d/main#/console/15222689/316560292/preview

**Comment by rhdelima** [comment]
Looks good. Pass
