### ISSUE TITLE
MOB7: IDW - display private key qr code

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#2041]
<img width="1166" alt="Screenshot 2020-02-17 at 19 22 19" src="https://user-images.githubusercontent.com/1021965/74675042-5715c480-51bb-11ea-9158-fe4339661943.png">
<img width="1166" alt="Screenshot 2020-02-17 at 19 22 46" src="https://user-images.githubusercontent.com/1021965/74675047-5aa94b80-51bb-11ea-95d4-4c4c472cfcd1.png">
<img width="1157" alt="Screenshot 2020-02-17 at 19 25 25" src="https://user-images.githubusercontent.com/1021965/74675051-5bda7880-51bb-11ea-9590-3e41a3b9d376.png">

**Comment by sk91** [comment]
FOR QA:

to enable please add feature flag: `FEATURE_WALLET_EXPORT=1`

**Comment by rhdelima** [comment]
@sk91 @maycon-mello I tried to scan qr (WIN) using ios and android, but failed on both.

**Comment by rhdelima** [comment]
Looks good. Pass
