### ISSUE TITLE
UI - Toolbar visibility

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2048]
![Screenshot 2020-02-13 at 17.13.03.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/273c0ced-74a2-4f00-8e11-666b26571603)

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/80056600-2ead9c00-8557-11ea-81da-57e6a7b1bf25.png)
