### ISSUE TITLE
Key Tokens Modal text misalignment

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2053]
Left align all text in Get Key Modal(coming from the new dashboard button) https://gyazo.com/e3b1ecb3ad5615946a0bd2c7b336c7b4

**Comment by rhdelima** [comment]
@oanamangiurea Please confirm if you're good with the fix. Thanks!

![image](https://user-images.githubusercontent.com/10294014/81069492-844d5580-8f14-11ea-9351-a11674cb788f.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, looks good now
