### ISSUE TITLE
Dashboard Transactions

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2055]
If I click on refresh icon in the transactions pannel, the icon should not change to the hourglass https://gyazo.com/a108f6974c1a6f1136deeef8c2e0ffd4 which doesn't look like the rest, but the refresh one should just become disabled.

**Comment by rhdelima** [comment]
Looks good on my end. @oanamangiurea Let me know if you agree.

![image](https://user-images.githubusercontent.com/10294014/79853817-1fb1d700-83fb-11ea-84f7-0406943c4e25.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, all good
