### ISSUE TITLE
Send/Receive Token Modal

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2056]
- [ ] Token dropdown is missing a placeholder. It should be "Select"

- [ ] "Amount:" is displayed in wrong color. Please see design https://projects.invisionapp.com/d/main#/console/15222689/316491963/preview  

- [ ] Also amount should display 0 if there are no funds available 

- [ ] Use the modal header icon as in the design

**Comment by rhdelima** [comment]
@oanamangiurea Let me know if you're good with the fix. As for the drop down arrow issue, I'll add it on material-ui ticket.
![image](https://user-images.githubusercontent.com/10294014/82773953-08409080-9e76-11ea-957c-138e4007d1a8.png)

![image](https://user-images.githubusercontent.com/10294014/82773969-11c9f880-9e76-11ea-83c5-73ed9fd7fc50.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, it's ok now
