### ISSUE TITLE
Add legal jurisdiction and entity codes

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#2074]

**Comment by rhdelima** [comment]
@sk91 Let me know how to test this.

**Comment by CortecKYC** [comment]
@sk91 Can you provide more info about how to test this ticket, please?

**Comment by andregoncalves** [comment]
On corporate, test if legal jurisdictions available match the ones defined here: https://www.gleif.org/en/about-lei/code-lists/gleif-accepted-legal-jurisdictions-code-list

Also make sure adding/changing company types works because there was some changes in platform schema.

**Comment by rhdelima** [comment]
@andregoncalves Based on the latest jurisdiction list, Canada should have more jurisdictions as well as UK and UAE. Please confirm.

![image](https://user-images.githubusercontent.com/10294014/78767656-77911c80-79bd-11ea-968b-34680ad79769.png)

**Comment by CortecKYC** [comment]
@andregoncalves Please see above

**Comment by andregoncalves** [comment]
@sk91 can you confirm this is the list you based on?

**Comment by CortecKYC** [comment]
@sk91 can you reply to that, please?

**Comment by sk91** [comment]
@andre @ralph i tried to make as few changes as possible to the list we had before. I used this table as reference to jurisdiction codes.

So no, i did not plan on adding new jurisdictions here

**Comment by CortecKYC** [comment]
@rhdelima Max replied already. Please continue testing this ticket

**Comment by rhdelima** [comment]
@sk91 @oanamangiurea Please confirm if we're good with the arrangement of some countries.

![image](https://user-images.githubusercontent.com/10294014/80336413-c7128c00-8889-11ea-82bb-3cf860d509d3.png)
![image](https://user-images.githubusercontent.com/10294014/80336428-d265b780-8889-11ea-8ea8-98053fd5632f.png)

**Comment by oanamangiurea** [comment]
@rhdelima @sk91 the countries need to be alphabetically listed

**Comment by sk91** [comment]
fixed in #2190

**Comment by rhdelima** [comment]
@sk91 Please fix below issues.

![image](https://user-images.githubusercontent.com/10294014/85379426-58426e00-b56e-11ea-92b1-f9351f1bea20.png)
![image](https://user-images.githubusercontent.com/10294014/85379459-609aa900-b56e-11ea-98ad-e0f90aa465c5.png)

**Comment by sk91** [comment]
fixed by #2311

**Comment by rhdelima** [comment]
This is fixed already. Pass
