### ISSUE TITLE
CORP6: manage application for corporate applications

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#2080]

**Comment by sk91** [comment]
mostly done in #2187, but some small fixes are still needed, reducing estimate to 3

**Comment by rhdelima** [comment]
waiting fixes on https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1546#issuecomment-647191873

**Comment by rhdelima** [comment]
Looks good now. Pass
