### ISSUE TITLE
Corporate Wallet: Incorrect format when using date picker

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#2105]
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/7516bd00-eaa7-425a-b2a3-ee6c5213a1b1)

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/7988fd57-a493-41eb-a83a-f6c49acffa91)

**Comment by andregoncalves** [comment]
@designhorf you changed the date picker date format right? What was the reason for it?
(Maybe the format should be passable as props to the component)

**Comment by andregoncalves** [comment]
Changing the format globally impacts json schema date validation. 
I don't think we should change the default json schema date validation, it's currently based on  ISO 8601 standard.
For this to work we will need to change the selfkey-ui datepicker to display the value in different format to what is stored internally.

Also, this blocks the release, all date validations will fail.

**Comment by CortecKYC** [comment]
For reference: https://mattermost.kyc-chain.com/kyc-chain/pl/tp6ky7esiiye3bb7j4ogygwffo

**Comment by rhdelima** [comment]
This is now fixed. Closing.
