### ISSUE TITLE
Copy final data from Loans research airtable to selfkey Airtable

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2107]
- [x] prod and dev tables
- [x] copy test data from reseearch airtable
- [x] copy final data from research airtable

**Comment by andregoncalves** [comment]
Deepak still working on research airtable.

**Comment by andregoncalves** [comment]
@rhdelima sent you an invite to the research airtable with loans data for the QA.

**Comment by rhdelima** [comment]
@andregoncalves Not sure how to this works but I noticed the following:
1. Interest rate in range (ex. 2-8%), 13% and blank values are NOT showing  on the list
![image](https://user-images.githubusercontent.com/10294014/82410017-96e19600-9aa1-11ea-9211-0114034ae99c.png)
2. Incorrect interest rate (lending) - ex. Money Token and INLOCK  
![image](https://user-images.githubusercontent.com/10294014/82410339-3f8ff580-9aa2-11ea-9c54-959c9d4c74bf.png)
3. `Take a loan` vendors are NOT showing on the list for LENDING
4. Missing Sign Up link (ex. Money Token - it has link on airtable but not on Sign Up button)

**Comment by andregoncalves** [comment]
1. 
We don't support ranges for now and we are selecting the average value. see: https://mattermost.kyc-chain.com/kyc-chain/pl/sg54y36mnfnu3pf75f8shwie8a

Can you clarify the other points, bitbond and smartcredit.io are not part of this initial phase, see: https://confluence.kyc-chain.com/display/SEL/Loan+Providers+-+Affiliate+links

2. See point 1.

3. Can you clarify which ones?

4. Typo in SK airtable (for the record you can check this on SK airtable LoansDev). Should be fixed with next sync.

**Comment by CortecKYC** [comment]
@rhdelima Can you resume QA?

**Comment by rhdelima** [comment]
@andregoncalves Please see some issues below:

1. Update Loan Currencies for Coin Loan
![image](https://user-images.githubusercontent.com/10294014/83624160-dbeae980-a5c4-11ea-9087-650a57836065.png)

2. Incorrect Interest Rate (LEND/BORROW) for Liquid
![image](https://user-images.githubusercontent.com/10294014/83624389-20768500-a5c5-11ea-94b1-f797d7ef382e.png)
![image](https://user-images.githubusercontent.com/10294014/83624436-3126fb00-a5c5-11ea-9caf-34133c7867d0.png)

3. Bank of Hodlers is not showing on Lending and Borrowing (on wallet)
4. Missing 'Max Loan Term" on vendor details for BORROWING vendors only (ex. Gate.io) -https://prnt.sc/soegi0
https://prnt.sc/sswufy
5. Missing data for Nuo on LoansDev table
6. Helio Lending and Power Blockcoin are missing on LoansDev (it is listed on affiliate link)

**Comment by andregoncalves** [comment]
@rhdelima 

1. Fixed loan currencies for CoinLoan
2. Fixed interest rate for Liquid
3. Fixed issue in Airtable that prevented Bank of Hodlers from showing up
4. Fixed Missing max loan term for borrowing vendors only
5. Fixed missing data for Nuo
6. Those are KYCC customers and integration is different, let's not test them at this stage, FYI: #2229 and #2230

**Comment by rhdelima** [comment]
@andregoncalves Please see remaining issues below:
1. SALT Lending - 
     type = Decentralized (LoansDev). Should be Centralized (Research)
2. Money Token -
    interest_rate_lending = 9% (LoansDev). Should be 8.5% (5-12% from Research)
3. Celsius Network -
    interest_rate_borrowing = 5% (LoansDev). Should be 6.2% (3.46%-8.95% from Research)
4. Nuo -
    interest_rate_borrowing = 6.8% (LoansDev). Should be 9.1% (2.3%-15.9% from Research)
    interest_rate_lending = 5.2% (LoansDev). Should be 5.3% (0.1%-10.5% from Research)

**Comment by andregoncalves** [comment]
thanks @rhdelima.
This is now updated.

**Comment by rhdelima** [comment]
Looks good now. Pass
