### ISSUE TITLE
Loan Marketplace details UI

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2110]
https://projects.invisionapp.com/d/main#/console/15222689/403994045/preview

**Comment by rhdelima** [comment]
@andregoncalves Can you confirm if KYC requirement section is NOT needed here for now? Thanks!

**Comment by andregoncalves** [comment]
- Trust score is not included on this first phase.

- KYC requirement should include a descriptive text like screenshot below (no KYCC requirements section)

<img width="1007" alt="Screenshot 2020-05-07 at 11 32 03" src="https://user-images.githubusercontent.com/1074/81289633-a4892b80-905e-11ea-9eba-dbd0348f53fe.png">
