### ISSUE TITLE
Loan Calculator (Loan Marketplace)

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2111]
https://projects.invisionapp.com/d/main#/console/15222689/410372108/preview

**Comment by rhdelima** [comment]
@andregoncalves Failing this one. See issues below:
1. CALCULATE MY LOAN button is NOT working
2. Typo error `LOAN AMONUNT` 
2. No validation for Loan Amount, Loan Period
3. CALCULATE button is NOT working

![image](https://user-images.githubusercontent.com/10294014/81286352-825dd080-9093-11ea-88b0-ba0cf0092d15.png)

**Comment by andregoncalves** [comment]
@rhdelima please wait until the latest fixes that are in PR review are merged to dev.

**Comment by rhdelima** [comment]
@andregoncalves Please see remaining issues below:
1. Missing placeholder (`Choose...`) on token drop down
2. Overlap on Loan Period

![image](https://user-images.githubusercontent.com/10294014/81566201-21a10180-93cd-11ea-80a7-e986ef23a9c6.png)

**Comment by rhdelima** [comment]
@andregoncalves Please see issues below:
1. NULL values are showing
![image](https://user-images.githubusercontent.com/10294014/82411785-00af6f00-9aa5-11ea-8b48-710074f94689.png)
2. No validation on Loan Amount field. It should be required
3. Overlapping texts on Interest Rate
![image](https://user-images.githubusercontent.com/10294014/82412489-50db0100-9aa6-11ea-98aa-11ae8f0c4aea.png)

**Comment by rhdelima** [comment]
@andregoncalves Please see some issues below:
**BORROW**
1. Some of vendors are not showing 
ex: 
**Crypto.com** 
![image](https://user-images.githubusercontent.com/10294014/83397599-749c3080-a430-11ea-9c7d-1fb54efc6f79.png)
![image](https://user-images.githubusercontent.com/10294014/83397621-8087f280-a430-11ea-8cf6-1493cda79178.png)
**LIQUID**
![image](https://user-images.githubusercontent.com/10294014/83401937-74079800-a438-11ea-9b4e-d5f65ecb8ad4.png)
![image](https://user-images.githubusercontent.com/10294014/83401983-84b80e00-a438-11ea-8a23-d66bc1b1f94b.png)
**OTHERS**
![image](https://user-images.githubusercontent.com/10294014/83403105-a0bcaf00-a43a-11ea-9911-2d9ceb673e9d.png)
![image](https://user-images.githubusercontent.com/10294014/83403122-a9ad8080-a43a-11ea-9d81-8e13678af534.png)

*LEND*
2. Some vendors are NOT showing. ex. Liquid
![image](https://user-images.githubusercontent.com/10294014/83627534-a694ca80-a5c9-11ea-9fce-1c15ddf4c5d2.png)
![image](https://user-images.githubusercontent.com/10294014/83627684-e52a8500-a5c9-11ea-91f5-f7f2d3afcba1.png)

3. Incorrect calculations for EUR and GBP

**Comment by andregoncalves** [comment]
@rhdelima fixes for the currency conversion and missing vendors are now reading for testing

**Comment by rhdelima** [comment]
Borrow:
1. Missing vendor (Tokpie)
Loan Amount = USD 100,000
Loan Period = 36 Mo

![image](https://user-images.githubusercontent.com/10294014/84121840-37f0ba80-aa6a-11ea-8366-73bc0ed216fc.png)
![image](https://user-images.githubusercontent.com/10294014/84122026-653d6880-aa6a-11ea-9440-7cf21b61f114.png)

2. Bank of Hodlers is still NOT showing on both lend and borrow
3. Collateral is off for borrow
Ex. 
Loan Amount = 100000 USD
Collateral = (100000 / 9676.36*0.5) = 20.67 BTC
![image](https://user-images.githubusercontent.com/10294014/84135066-139dd980-aa7c-11ea-891d-7742424122c4.png)

**Comment by andregoncalves** [comment]
@rhdelima 

1. I don't think topkie supports BTC, if you change to ETH it should work

2.Can you re-test? there was an error in Airtable

3. Can you retest? I redid the formula

**Comment by rhdelima** [comment]
Looks good now. Pass
