### ISSUE TITLE
Revert date format changes to selfkey-ui date picker

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2116]
Temporarily revert: https://github.com/SelfKeyFoundation/selfkey-ui/commit/6323b8459d1d707eefb1947ab22bcba7c18f0181

To be handled later: https://app.zenhub.com/workspaces/selfkey-development-5a974701436f5f648c6e4801/issues/selfkeyfoundation/identity-wallet/2117

**Comment by rhdelima** [comment]
Looks good. Pass
