### ISSUE TITLE
Ledger table view

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2140]
![Screenshot 2020-03-25 at 18.37.20.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/b49049c6-18a4-4b53-b0a2-a27948325acf)

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/79851770-563a2280-83f8-11ea-998f-62f3513503e8.png)
