### ISSUE TITLE
Range Component

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2143]
[https://images.zenhubusercontent.com/5be15edea977220c77bd265d/c41350f7-64b4-4e0b-b7b3-ea12c3d410de](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/c41350f7-64b4-4e0b-b7b3-ea12c3d410de)

**Comment by designhorf** [comment]
@andregoncalves we need to upgrade material ui version, because `3.9.2` doesn't contain range slider component.
https://v3.material-ui.com/lab/slider/

**Comment by CortecKYC** [comment]
@andregoncalves Is this ticket still blocked?

**Comment by andregoncalves** [comment]
Unblocked now.
