### ISSUE TITLE
Ugly scrolling bar on dashboard token list

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2145]
[https://gyazo.com/36f181b3849e39c7b12160fe8696f0de](https://gyazo.com/36f181b3849e39c7b12160fe8696f0de)

**Comment by rhdelima** [comment]
@oanamangiurea Let me know if this looks good on your end.

![image](https://user-images.githubusercontent.com/10294014/79850974-4241f100-83f7-11ea-9560-f646df779e62.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, all good
