### ISSUE TITLE
Upgrade material-ui

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2151]
You can find updates and error fixing on this branch -> `feat/upgrade-material-ui`

- [x] upgrade dependencies
- [x] fix tests
- [x] Review wallet UI issues (#2177)

**Comment by andregoncalves** [comment]
@rhdelima we updated the main UI library and we need a full visual/layout QA as comprehensive as possible.

**Comment by oanamangiurea** [comment]
Did a fast test, issues I encountered so far

1. Hover close button of any modal - now it has a square background, this shouldn’t happen https://gyazo.com/1f716a05fb808eb8d9c9b79093f9d3d1
2. Step 3 modal of backup wallet address on creation - wrong spacing of input vs buttons, copy button and input look disabled https://gyazo.com/31cabe82dd0619aa7b1b0e2d18c0ac71 same with next modal, print private key, the input spacing vs buttons is too small https://gyazo.com/dde846f818846608aeec44d987bf38c0
3. Hovering tooltips - the arrow part of the tooltip moves as I hoover over it, it’s a bit annoying
4. Spacing for uploaded documents in add documents modal is too big https://gyazo.com/bcb940b6e59aa7d34cca72718724244d see design
5. Corp Wallet - Left gray column font is too big https://gyazo.com/0bae953f0f8c46c2b99a07e85018bf20
6. !! Exchange description - button is not right aligned if the text is too short, and it’s width is smaller compared to other details pages. Also missing the affiliate disclosure text under it  https://gyazo.com/b6e8f21ee03c4cce7bcbddada7bc02da

**Comment by oanamangiurea** [comment]
Extra issues just found:

1. When opening a modal to incorporate or open bank account, the modal is not centred on the screen https://gyazo.com/80c6f49244272240181fba9957d8251a 
2. Cost spacing between USD and  Key is off, in the bank accounts and incorporations listing https://gyazo.com/a578fe34bc2e8319fb2a035be9b17a76 
3. Missing top/bottom cell padding from listing large tables https://gyazo.com/e88d8bd017e1082826c63b59c0ab7439

**Comment by oanamangiurea** [comment]
Looks good, pass
