### ISSUE TITLE
Fix dropdown inputs style

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2165]
EX: https://gyazo.com/2ba648ba5dee083b58e1110b68802e15 vs https://projects.invisionapp.com/d/main#/console/15222689/397678445/preview 

1. "Choose" is a placeholder, not a value, so that text should be displayed in gray 
2. Dropdown arrow - please use the one from the design, and make sure it's 15px away from the right border of the input. Padding left/right should be 15px.

**Comment by rhdelima** [comment]
@designhorf Failing this one. I think this ticket should also cover other dropdown fields.

![image](https://user-images.githubusercontent.com/10294014/81893110-6d2af980-95df-11ea-9e43-ba88a7681831.png)
![image](https://user-images.githubusercontent.com/10294014/81893126-77e58e80-95df-11ea-8ccd-995f97fc94aa.png)

**Comment by oanamangiurea** [comment]
Please also have a look at the dropdown from the lending calculator https://gyazo.com/2ed1c287c59f6f180258fdf27ae264dd

**Comment by rhdelima** [comment]
Looks good now. Pass
