### ISSUE TITLE
Small UI Fixes

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2166]
1. Table tags -> https://gyazo.com/229c10375820300e7196ef9ae2e73127 margin should be: 2px 4px 2px 0 
2. Swap token box in dashboard https://gyazo.com/73a02daebcee150310856b631dc07caf has the coins background over the buttons 
3. Incorporation details stats - reduce lines spacing, and fix box width vs the button (like the one in bank accounts, this one I think it's missing a display:flex) - see design https://gyazo.com/31a92f2494d8b92981eb8950ebea83a5 
4. In user profile, the icon from additional informations has the old gradient https://gyazo.com/7fcd95faa97283c246ca30f9ca334651

**Comment by rhdelima** [comment]
@oanamangiurea Let me know if you're good with the fix. Please see sample screenshots

![image](https://user-images.githubusercontent.com/10294014/83111140-b9555e00-a0f6-11ea-9b01-0ee2ec0b06a8.png)
![image](https://user-images.githubusercontent.com/10294014/83111234-e1dd5800-a0f6-11ea-9f25-709914c65c8f.png)
![image](https://user-images.githubusercontent.com/10294014/83111706-96777980-a0f7-11ea-93b3-309eb8f77d25.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, all good now
