### ISSUE TITLE
Swap token UI changes

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2171]
- https://projects.invisionapp.com/d/main#/console/15222689/393424599/preview
- https://projects.invisionapp.com/d/main#/console/15222689/413340456/preview

**Comment by rhdelima** [comment]
@andregoncalves Please see issues below:
1. Fix CALCULATE FEES and EXCHANGE buttons. Buttons are too close
2. Remove extra lines on Amount Total
@oanamangiurea , anything you can add here?

![image](https://user-images.githubusercontent.com/10294014/80460592-a409da00-8966-11ea-9841-1a09217c34fe.png)

**Comment by andregoncalves** [comment]
Those two lines on the amount total are the swap value and fees, they have to be separated because fees are always in ETH.

**Comment by andregoncalves** [comment]
@rhdelima Button spacing is part of material-ui change, so I expect this issue to surface on other pages, please see #2151

**Comment by CortecKYC** [comment]
@rhdelima What's the status of this ticket? QA-failed? Waiting for something?

**Comment by rhdelima** [comment]
@CortecKYC I suggest to put this on-hold for now until issue is fixed on material-ui change. What do you think?

**Comment by rhdelima** [comment]
@CortecKYC My bad. Andre has a fix for it on https://github.com/SelfKeyFoundation/Identity-Wallet/pull/2189 but I don't think it's already merged. Will check.

**Comment by CortecKYC** [comment]
Ok, thanks!

**Comment by rhdelima** [comment]
Looks good now. Pass
