### ISSUE TITLE
Fix issues related to new material-ui 

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2177]
Regarding issue #2151, the `feat/update-selfkey-ui-material-ui` branch includes the new selfkey-ui and new material-ui libraries.
However, this upgrade introduced a bunch of new UI issues (mostly related to default margins/padding which seem to have changed).

I want you take a look and see if it's something it can be tackled short term, or if we should revert back to old version for the loans marketplace (use an alternative library for the range component), and make this migration a more medium term goal (I still think it's important and that we should do it anyway). /cc @oanamangiurea 

Example screenshots:
![Screenshot 2020-04-15 at 15.21.07.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/59def5fa-12a3-4ddd-85d5-429ecec8905a)
![Screenshot 2020-04-15 at 15.21.11.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/27141301-f84d-4d64-8264-a5428fc87925)
![Screenshot 2020-04-15 at 15.21.22.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/77d82500-2e65-4130-8977-f46e3428fd45)

**Comment by designhorf** [comment]
@andregoncalves I had a look at this branch and fixed easily `Grid` issues (branch is updated) however I found many other issues (eg. modal background is changed, adding documents to Selfkey Profile is not working, etc). It means I need more time to fix all of the bugs. Btw, I agree with you, we need to make this upgrade.
Can I prioritise this task? 
@oanamangiurea @andregoncalves  What do you think?

**Comment by CortecKYC** [comment]
@designhorf Please prioritize this task (unless @oanamangiurea  thinks otherwise)

**Comment by oanamangiurea** [comment]
@designhorf yes you can prioritize this, and let me know if I can help test it more, or maybe after you made more fixes

**Comment by designhorf** [comment]
@CortecKYC @oanamangiurea thanks!

**Comment by andregoncalves** [comment]
@designhorf can you roughly estimate?

**Comment by designhorf** [comment]
@andregoncalves I think I can fix all of the issues for Monday. Is it ok?

**Comment by andregoncalves** [comment]
@designhorf I will take a look, can you please commit the latest fixes you did?

**Comment by designhorf** [comment]
@andregoncalves updated the branch
