### ISSUE TITLE
Trezor address issue

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2183]
When using trezor:
"i'm sending tokens to an address, but it keeps asking if i'm sending a message to a contract"
This error might be related:
http://sentry.kyc-chain.com/kyc-chain/electron-s1/issues/2105/?environment=production

**Comment by andregoncalves** [comment]
@sk91 this is probably related to @2355

**Comment by sk91** [comment]
@andregoncalves 

> http://sentry.kyc-chain.com/kyc-chain/electron-s1/issues/2105/?environment=production

Wallet version is 1.5.0. The error looks similar to gas issue that was fixed in 1.6.4

**Comment by sk91** [comment]
> "i'm sending tokens to an address, but it keeps asking if i'm sending a message to a contract"

Sending tokens to address is the same as sending message to a contract.

Only Eth transfer is not considered as contract call
