### ISSUE TITLE
Update Terms of Service

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#2185]
Updated terms of service (as of April 23, 2020):
https://confluence.kyc-chain.com/display/SEL/Terms+of+Service

**Comment by oanamangiurea** [comment]
+ While updating, please remove the following from the analytics checkbox: "[Default opt-in]", so the checkbox text will begin straight with  "I voluntarily agree...."

**Comment by rhdelima** [comment]
@andregoncalves See some issues on the screenshots below:

https://prnt.sc/sgnl3f
https://prnt.sc/sgnr7c
https://prnt.sc/sgnxam
https://prnt.sc/sgob0t
https://prnt.sc/sgog8h

**Comment by rhdelima** [comment]
@andregoncalves There are still remaining minor issues.

https://prnt.sc/skgrmu
https://prnt.sc/skgzsv
https://prnt.sc/skh37n

**Comment by andregoncalves** [comment]
Please test again with latest build

**Comment by rhdelima** [comment]
@andregoncalves See remaining issues:
1. Remove extra `s` https://prnt.sc/snib9t
2. Should be on the next paragraph https://prnt.sc/snicxk
3. Missing `and` https://prnt.sc/sni83v

**Comment by andregoncalves** [comment]
@rhdelima can you please check latest build
