### ISSUE TITLE
Replace Bank Accounts text

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2194]
Under Bank Accounts, we use the texts from incorporations:  https://gyazo.com/ed9ce3f29f05bc7a1396c9c7bb8d993f 

This needs changing to: 

> Bank Account opening requirements are subject to change at the discretion of the bank. There might be additional fees charged by the bank itself. Bank account opening is not guaranteed and is subject to the bank policies and compliance department. There might be restrictions on UBO nationalities, business activities and/or jurisdictions. A refund is guaranteed if the account is not successfully opened, but a 15% administrative fee applies.

The change should apply both under the What you get tab, and in the modal for opening the account

**Comment by rhdelima** [comment]
Looks good. Pass
![image](https://user-images.githubusercontent.com/10294014/81166696-807a0b80-8fc6-11ea-9900-e339e1f6898b.png)

![image](https://user-images.githubusercontent.com/10294014/81166733-94257200-8fc6-11ea-8143-83d273408fea.png)
