### ISSUE TITLE
update terms of service on the wallet

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#2200]
[https://app.zenhub.com/files/105664964/26c6375a-91eb-4181-81fc-7e51255d623e/download](https://app.zenhub.com/files/105664964/26c6375a-91eb-4181-81fc-7e51255d623e/download)

remove ""[Default Opt-in]"

**Comment by CortecKYC** [comment]
@andregoncalves did you this in already?

**Comment by andregoncalves** [comment]
I did yes on #2185. 
Ferenc reviewed, it's already on QA
