### ISSUE TITLE
unlock wallet screen should have padding at the buttom

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#2201]
![Screenshot 2020-04-29 at 20.41.34.png](https://images.zenhubusercontent.com/5b7d75daa851440301948ac1/3d6ed862-e8d5-41a2-b982-605a67c82ea5)

**Comment by designhorf** [comment]
@max As I see, this ticket is already fixed. Could you approve it?

**Comment by andregoncalves** [comment]
@designhorf, Max is @sk91 on github, I think he missed your message.
This looks to me fixed on dev, closing.
