### ISSUE TITLE
SHAPE UP: RaidoFinance Integration

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#2203]

**Comment by sk91** [comment]
It is premature to shape it up.

This feature will require many discussions and will probably depend on other features like:
- Selfkey API
- Deep links

I have investigated the integration details, and proposed a "Selfkey Exchange" feature design, as well as an example flow with Raido Finance

https://confluence.kyc-chain.com/display/SEL/PROPOSAL%3A+Selfkey+Exchange+Design

This Feature is also related to the payments bet from RND, so @cbruguera and @altninja need to participate in further shaping up of this feature

**Comment by sk91** [comment]
@CortecKYC @andregoncalves @Horizon88 @cbruguera @altninja please review

**Comment by CortecKYC** [comment]
@rhdelima , skip this one. It's for the people tagged above to review.
