### ISSUE TITLE
Spacing for uploaded documents

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2208]
Spacing for uploaded documents in add documents modal is too big https://gyazo.com/bcb940b6e59aa7d34cca72718724244d see design

**Comment by rhdelima** [comment]
@designhorf Still NOT fixed on my end.

build: dev/2020.05.05.13
![image](https://user-images.githubusercontent.com/10294014/81168327-6130ad80-8fc9-11ea-9d4e-40e40ac69aab.png)

**Comment by designhorf** [comment]
@rhdelima sorry it was a mistake by me, material ui json schema wasn't updated. I'll fix it.

**Comment by rhdelima** [comment]
@oanamangiurea Please confirm if you're good with this as well.

![image](https://user-images.githubusercontent.com/10294014/81639767-78e7b600-944f-11ea-950d-3213c7b395a4.png)

**Comment by oanamangiurea** [comment]
@rhdelima looks good, pass
