### ISSUE TITLE
Fix table text

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2215]
In Exchanges marketplace, the column of countries should be wider, it just looks bad to see a huge row like that because of a big list. 
- [x] Plus the text doesn't wrap, it gets cut. https://gyazo.com/c76c66fe2cee811581512c64be7e2ab1 So that column should have a max-width of 300px or so and we could even remove the Fees column as we don't have any data. Please make sure the table doesn't get too wide (if you just change the max-widh)

- [x] Plus the entire table text should be 15px, not 1rem (which is 16px) - please have a look at all marketplaces listings and make sure they look ok.

- [x] Tags should have a 4px spacing between, now they have margin top/bottom of 4px = 8px between them

- [x] Line-height of the text inside tables for 15px is 22px, see for ex 1st column in Bank Accounts.

**Comment by rhdelima** [comment]
@oanamangiurea Can you confirm if you're good with this? I think Excluded Countries should have a wider column than FIAT.

![image](https://user-images.githubusercontent.com/10294014/82204279-320a2c80-9937-11ea-9ca3-550f0df464ab.png)

**Comment by oanamangiurea** [comment]
@rhdelima correct, that was the first issue raised 

> In Exchanges marketplace, the column of countries should be wider, it just looks bad to see a huge row like that because of a big list.

**Comment by rhdelima** [comment]
@oanamangiurea Please confirm if you're good with this now. See sample screenshot
![image](https://user-images.githubusercontent.com/10294014/82774472-8d787500-9e77-11ea-9812-2d048891bde0.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, all good now
