### ISSUE TITLE
Exchange details page is misisng back button 

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2216]
No back button to return to list of exchanges on any of the pages https://gyazo.com/5ed45cf2d84a5fc92f152ba8d487e7d4

**Comment by rhdelima** [comment]
@oanamangiurea Please confirm if you're good with the fix. Thanks!

![image](https://user-images.githubusercontent.com/10294014/81638527-0b865600-944c-11ea-88e7-883a632316e0.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, thank you
