### ISSUE TITLE
Transaction Notice Modal UI

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2217]
The modal with not enough ETH https://gyazo.com/0bfe155e325202d50c4b5aa287169860, that the user gets for example when we wants to set up his DID, but doesn't have the funds needs fixing the following:

1. Paragraph should not be justified, but left aligned. 
2. Missing vertical spacing between elements, see https://projects.invisionapp.com/d/main#/console/15222689/318457086/preview
3. Your address text should have the font size like in the above design

**Comment by rhdelima** [comment]
@oanamangiurea Please confirm if this looks good to you. Thanks!

![image](https://user-images.githubusercontent.com/10294014/81920506-dde80b00-960b-11ea-9dfa-e94f7a3cc04e.png)

**Comment by oanamangiurea** [comment]
@rhdelima looks good now, pass
