### ISSUE TITLE
Button group

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2277]
issue with border-radius that is applied on all buttons. And the padding for it should be 0px 24px

**Comment by oanamangiurea** [comment]
Failing this one. Should be fixed for the button groups that are on the Lending and Borrowing tabs as well https://gyazo.com/a0bee317d4888a99008f35a238b493f3 

+ Selected button style doesn't match the style guide- see background color and border color

**Comment by rhdelima** [comment]
@oanamangiurea Let me know if you are good with the fix. See sample screenshots

![image](https://user-images.githubusercontent.com/10294014/85378489-34caf380-b56d-11ea-8546-926ef5500ed9.png)
![image](https://user-images.githubusercontent.com/10294014/85378513-3ac0d480-b56d-11ea-8523-ceee19991cc0.png)
![image](https://user-images.githubusercontent.com/10294014/85378538-444a3c80-b56d-11ea-90ea-edba01cb6760.png)

**Comment by oanamangiurea** [comment]
@ralph yes they look good now, pass
