### ISSUE TITLE
Loans calculator table scroll

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2288]
The table I see after I calculate a loan has a horizontal scrollbar 

https://gyazo.com/4a45625ed4c124dd19f5e2f1cf9d3ec3

**Comment by rhdelima** [comment]
Looks good now. Pass

![image](https://user-images.githubusercontent.com/10294014/83972365-52178500-a912-11ea-9a85-861f744f302b.png)
