### ISSUE TITLE
Loans description text padding

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#2289]
New bug with the description area for a loan provider, now the text is too close for the button. That area should have a padding https://gyazo.com/a4f2f0fe900e314063a37e7e58c7aa1d 

Please make sure you check more than one provider for both loans and exchanges. We keep having issues with this area

**Comment by rhdelima** [comment]
Looks good now. Pass

![image](https://user-images.githubusercontent.com/10294014/83972734-707e8000-a914-11ea-9799-bc8685640e0d.png)

![image](https://user-images.githubusercontent.com/10294014/83972824-f0a4e580-a914-11ea-8a49-10dee156a248.png)
