### ISSUE TITLE
Update selfkey-ui: remove react-jss

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2297]

**Comment by andregoncalves** [comment]
@designhorf I need to you take a look at the  2297-remove-react-jss branch of selfkey-ui.
To streamline selfkey-ui for web use, I removed react-jss and migrated to only using material-ui 4 css-in-js solution.

Can you test it out and make sure nothing is breaking? (you probably need to remove node_modules and do a fresh install)

Thanks.

**Comment by designhorf** [comment]
@andregoncalves sure, I'll test it today
