### ISSUE TITLE
Fix Alert component

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2328]
Border-radius is missing around Alert component

**Comment by rhdelima** [comment]
@designhorf Can you point out where to and what to test here? Thanks!

**Comment by designhorf** [comment]
@rhdelima sure, there is a small styling change. Alert components got rounded border.
<img width="104" alt="Screenshot 2020-07-27 at 08 10 26" src="https://user-images.githubusercontent.com/7461010/88509170-cd2b1c80-cfe0-11ea-9555-cc6cbf38de1e.png">
like here https://projects.invisionapp.com/d/main#/console/15222689/361161606/preview

**Comment by rhdelima** [comment]
@designhorf Failing this one. See screenshot below:
![image](https://user-images.githubusercontent.com/10294014/88626128-aa7e2e00-d0dc-11ea-8e66-b66613b1380b.png)

**Comment by rhdelima** [comment]
Looks good now. Pass
