### ISSUE TITLE
Fix checkboxes

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2330]
Checked checkboxes hasn't got border.

**Comment by rhdelima** [comment]
@designhorf Failing this one. Please screenshot below.

![image](https://user-images.githubusercontent.com/10294014/88628299-4bbab380-d0e0-11ea-8983-e690126254b8.png)

**Comment by designhorf** [comment]
@rhdelima nice catch! But if you don't mind I'd like to open a separate ticket for it. It is a functional (checkbox probably didn't get error status) and not styling issue. This ticket fixes checkbox styling (borders are missed).

**Comment by designhorf** [comment]
Ticket (https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2341) and PR with fixes (https://github.com/SelfKeyFoundation/Identity-Wallet/pull/2342) are created
