### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2336]
Need to change style of Back button (padding, border and font style).

Current one:
![Screenshot 2020-07-27 at 17.11.01.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/683b3862-1f9f-44be-b20d-3310bb942e47)

New one:
![Screenshot 2020-07-27 at 17.11.19.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/3c9d5feb-d845-4cec-a7c9-12d7276c6d27)

**Comment by rhdelima** [comment]
Looks good. Pass
