### ISSUE TITLE
Error: nonce too low is encountered when sending eth/tokens using wallet unlocked by a private key without 0x

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#2343]
https://mattermost.kyc-chain.com/kyc-chain/pl/9efbcckwr7noxgtmizifdrszoa

**Comment by andregoncalves** [comment]
@sk91 https://mattermost.kyc-chain.com/kyc-chain/pl/9efbcckwr7noxgtmizifdrszoa
Related: https://github.com/MetaMask/metamask-extension/issues/687

**Comment by sk91** [comment]
to recover the correct private key in this case do the following:
example:
for original private key:
0xf5de10128a8661b78f0e79070547de53389f9b491999cb464eeae154c8f16fae

when used with the wallet without 0x prefix
f5de10128a8661b78f0e79070547de53389f9b491999cb464eeae154c8f16fae

replace first 2 characters with 0 and prefix with 0x
0x00de10128a8661b78f0e79070547de53389f9b491999cb464eeae154c8f16fae

this private key can be used to controll the newly created account

NOTE, after recovering this private key, use it to transfer funds to a different account, and don't keep it, this is not a secure private key.

**Comment by sk91** [comment]
#2356 is fixing the private key validation to avoid it in future

**Comment by andregoncalves** [comment]
@rhdelima please test #2356

**Comment by rhdelima** [comment]
Looks good. A validation error "The private key you entered is incorrect. Please try again!" is displayed when private key has no 0x prefix.
![image](https://user-images.githubusercontent.com/10294014/90588273-d0937b80-e20d-11ea-877a-429858be5637.png)
