### ISSUE TITLE
Marketplace - new Exchanges without partnership

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2348]
https://projects.invisionapp.com/d/main#/console/15222689/422589199/preview

**Comment by andregoncalves** [comment]
@designhorf can this be moved to QA?

**Comment by designhorf** [comment]
@andregoncalves sure, I'll do it

**Comment by designhorf** [comment]
@rhdelima yes it is, the related feature flag is `FEATURE_EXCHANGES_MARKETPLACE`.

**Comment by rhdelima** [comment]
Looks good. Pass
