### ISSUE TITLE
Download and Relaunch new update not working

### ISSUE THREAD

**Issue by sashatanase** [SelfKeyFoundation/Identity-Wallet#2351]
When prompted with the " Download & Relaunch " Update dialogue - after hitting download and relaunch nothing happens. The app freezes with the download being completed and the only thing that still functions is the [ Cancel ] button. 
The CPU goes to 137% usage from the desktop wallet and no matter how long I wait doesn't work. 

https://drive.google.com/file/d/1LcgQmZfqOy5mREZCEs-ZnzR7SnIvrhL-/view?usp=sharing

**Comment by andregoncalves** [comment]
@sk91 this is the update issue we solved, right?

**Comment by sk91** [comment]
This is a different issue I think, related to notarization after download. 

If for some reason it takes to long or fails, the update flow fails.
To fix it we need to seriously work on bundle size, and find a way to enable asar compilation without issues with our binaries
