### ISSUE TITLE
Error sending ERC-20 Tokens via trezor

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2355]
https://mattermost.kyc-chain.com/kyc-chain/pl/464q5b3i6fgyxq1qokdcyikz1a

Possibly related: http://sentry.kyc-chain.com/kyc-chain/electron-s1/issues/2714/?environment=production

**Comment by sk91** [comment]
@rhdelima tested the production wallet and could reproduce.

There is evidence (unconfirmed) that in the original issue the address was invalid

closing
