### ISSUE TITLE
Wallet balance doesn't update after receiving funds

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2359]

**Comment by andregoncalves** [comment]
@sk91 want to take a look at this?

**Comment by sk91** [comment]
@andregoncalves sure

**Comment by andregoncalves** [comment]
@rhdelima can you QA this?
The wallet balance on the header bar didn't update after receiving funds when the wallet is open.

**Comment by rhdelima** [comment]
Looks good on my end. Tested using KI (on testnet) since gas on mainnet is currently too HIGH.

![image](https://user-images.githubusercontent.com/10294014/91715115-a94e8e00-ebbf-11ea-8fc0-bda3068563dd.png)
