### ISSUE TITLE
KYCC status is not being correctly updated

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2360]
Additional requirements are ignored (application in progress).
Additionally in the marketplace offer page, the status bar is not shown

**Comment by andregoncalves** [comment]
After a few tests, it seems everything is working correctly.

If a wallet is open, we have a RP_UPDATE_INTERVAL that defaults to 3h. RP application changes will not be immediately visible in the wallet unless forced with a refresh on the manage applications tab of the profile or by restarting the wallet.

@sk91 this behavior has bitten us in several demos already (like the one you did on staking), should this behavior be changed or somehow more documented?

**Comment by sk91** [comment]
@andregoncalves I don't think it should be changed.

We can expose an ENV var to help us in the demo

**Comment by sk91** [comment]
also we can load automatically when navigating to a page
