### ISSUE TITLE
Notarization Terms of service

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2364]

**Comment by rhdelima** [comment]
@andregoncalves Terms and privacy links are currently missing.

![image](https://user-images.githubusercontent.com/10294014/94129388-e12eb580-fe8d-11ea-83bc-6f4e199a2cf6.png)

**Comment by andregoncalves** [comment]
A fix will be deployed, so that the link is not rendered (only text) when airtable doesn't provide links to terms and privacy.
https://github.com/SelfKeyFoundation/Identity-Wallet/pull/2402

**Comment by andregoncalves** [comment]
@rhdelima  Please also check wallet general terms of service, they have changed.

**Comment by rhdelima** [comment]
@andregoncalves , Please see some issues below.
1. Incorrect text —https://prnt.sc/uu9e5w
2. Section 11 and 12 header were been interchanged —https://prnt.sc/uu9xpv
3. Redundant  text—https://prnt.sc/uua2r9
4. Missing sub section—https://prnt.sc/uuagfg
5. Missing section 14—https://prnt.sc/uuao5c
6. Missing section intro on Section 2: Please add space in between ‘an’ and ‘ Account’—https://prnt.sc/uub30p
7. Please make ’to’ into ’To’—https://prnt.sc/uub72b
