### ISSUE TITLE
Fix Material UI warnings/errors

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2371]

**Comment by rhdelima** [comment]
@designhorf Can you provide some instructions on how to test this? thanks!

**Comment by designhorf** [comment]
@rhdelima sure, there were many Material UI related (mostly) warnings in console. 
You can find here a small description about fixed issues.
https://github.com/SelfKeyFoundation/Identity-Wallet/pull/2386
So, I think you should see console messages and check warnings/errors.
If you need more instruction or any help, ping me.
