### ISSUE TITLE
Notarization Testing

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2373]
Notarization KYCC template is at https://dev.instance.kyc-chain.com

**Comment by rhdelima** [comment]
@andregoncalves Please see issues below:
1. Message for Notary is marked as required but still can submit with blank message
2. TX fee on Upload documents modal is different from TX fee on Payment Required modal
Recording - http://recordit.co/WSxuf9S4o5

3. Documents were NOT uploaded on KYC
![image](https://user-images.githubusercontent.com/10294014/94132355-c2322280-fe91-11ea-8626-065c0c783bbe.png)

4. When closing Notarization checklist, unwanted modal (KYC checklist) is displayed. http://recordit.co/rdmlgOiCWi
5. When user tries to submit other documents, can we mark documents already submitted?

**Comment by andregoncalves** [comment]
@rhdelima 

1. A fix is in PR review should be deployed soon to build channel.
2. A fix is in PR review should be deployed soon to build channel.
3. Couldn't reproduce this, it seems to work fine for me, can you test again?
4. A fix is in PR review should be deployed soon to build channel.
5. That's a good suggestion, but for now not possible, I will open an improvement ticket.
