### ISSUE TITLE
DID transaction timeout on network lag

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#2380]
On socket based connections contract calls have a timeout of 50 blocks

https://web3js.readthedocs.io/en/v1.2.6/web3-eth-contract.html#transactionblocktimeout

We need to increase it to avoid DID transaction timeouts on loaded network

**Comment by rhdelima** [comment]
@sk91 I'm still getting tx failed but tx was still in pending. It took 30 mins before tx was successful. Maybe we need to catch the timeout and show appropriate message with the tx link on the etherscan.

**Comment by andregoncalves** [comment]
We can ignore it. 30min for transaction is too much to wait.
Closing this
