### ISSUE TITLE
feature flag for DID

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#2398]

**Comment by sk91** [comment]
for QA:

please use: `FEATURE_DID=0` feature flag and test:
- that all mentions of DID are gone.
- did is not reuired for marketplace applications

**Comment by rhdelima** [comment]
Looks good. Pass

**Comment by rhdelima** [comment]
sorry @sk91 . I'm reopening this one. I forgot to test kyc submission when DID is off. After clicking submit, it shows blank screen.

![image](https://user-images.githubusercontent.com/10294014/95187519-d6651080-07fd-11eb-8587-92e028798a77.png)
![image](https://user-images.githubusercontent.com/10294014/95187486-cbaa7b80-07fd-11eb-9d63-ba50d7c98cff.png)

**Comment by andregoncalves** [comment]
@sk91 is this fixed?

**Comment by sk91** [comment]
@andregoncalves missed the issue

@rhdelima can you test again? From the log it seems the issue was in kycc side (temporary)

Please test both cases (with and without did) to be sure the issue is with the did flag

**Comment by rhdelima** [comment]
@sk91 I tried on both cases (with and without DID). Payment Required modal is not showing when DID is disabled.
