### ISSUE TITLE
 Sidebar scrolling bar

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2401]
Reduce big space among sidebar elements in default window.
![Screenshot 2020-09-23 at 15.18.37.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/33413e2e-5e04-4b33-a3f2-ee002d1ff08f)

**Comment by rhdelima** [comment]
Looks good. Pass 
![image](https://user-images.githubusercontent.com/10294014/103501872-7fb5b400-4e8a-11eb-82a5-5ad486c7ebcb.png)
