### ISSUE TITLE
Broken images on Loans Marketplace

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#2425]
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/5b562b47-9509-44d0-be5f-70a832ddfcd6)

**Comment by andregoncalves** [comment]
Icon URLs required an update. 
Airtable is now updated. /cc @rhdelima

**Comment by rhdelima** [comment]
@andregoncalves Bank of Hodlers still has broken image.

![image](https://user-images.githubusercontent.com/10294014/96710475-b5401a80-13ce-11eb-926c-66aff3332fa3.png)

**Comment by andregoncalves** [comment]
@rhdelima can you recheck? it seems to be working for me (without changing anything).

**Comment by andregoncalves** [comment]
@rhdelima can you please re-check (FYI: Bank of Hodlers has been removed)

**Comment by rhdelima** [comment]
Looks good. Pass
