### ISSUE TITLE
Bank Accounts are NOT showing on release build 1.7.2

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#2426]
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/d3986038-99c0-4ff1-a4ed-067bb7243445)

**Comment by andregoncalves** [comment]
airtable issue, can you recheck @rhdelima ?

**Comment by rhdelima** [comment]
Looks good. Pass
