### ISSUE TITLE
KeyFI: Eligibility Marketplace

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2428]
- [x] Airtable data

- [x] Dashboard widget

- [x] KYCC dev instance test template

**Comment by rhdelima** [comment]
@andregoncalves See some issues below:
1. When clicking Get Certified without SK ID created yet, it should trigger the create SK ID modal https://recordit.co/LLei2H4dvQ
2. Missing Contact Us email https://prnt.sc/vl9rbu
3. Shows `Waiting for re-upload` though already uploaded . https://prnt.sc/vl9u1d
4. A newly submitted application has status = `Additional Items Requested` https://prnt.sc/vl9zt1

**Comment by andregoncalves** [comment]
Hi,
I will work on fixes for #1
2. Is missing airtable data, it will get fixed automatically
3 and 4 are part of the new KYCC workflow, I think that's normal
