### ISSUE TITLE
Back button position issue

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2433]
Back button is wrongly aligned (center).

![Screenshot 2020-11-09 at 10.37.45.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/83417de2-c181-4d8f-9659-cdfadd5025e3)

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/99058343-0a3f0d00-25d8-11eb-86e6-368f500cb683.png)
