### ISSUE TITLE
Position issue

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2434]
Back button is wrongly aligned in create Selfkey ID form

![Screenshot 2020-11-09 at 10.37.07.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/7c543cb0-c69f-43eb-aad0-842070b6fc5d)

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/99057656-137baa00-25d7-11eb-8564-16125b5a69f3.png)
