### ISSUE TITLE
Back button position of Manage My Crypto

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2438]
![Screenshot 2020-11-11 at 09.43.04.png](https://images.zenhubusercontent.com/5bf289869d595b459ec9162e/b0bc8fd7-34d1-478a-80c7-3dba86d985b0)

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/99058113-b2a0a180-25d7-11eb-84b0-8a006d19b925.png)
