### ISSUE TITLE
Improved send transaction

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2466]
Deduct fees when clicking MAX on eth transactions
Incorporate a calculation to automatically deduct the transaction fee from the amount to send if the user clicks on the MAX button on ETH transactions.

Refactor fee box

**Comment by andregoncalves** [comment]
@rhdelima please test carefully the new send transaction UI and logic. This change also affects the Manage Contract Allowance feature, so please test that as well.

**Comment by rhdelima** [comment]
@andregoncalves Can you confirm what the Manage Contract Allowance feature is?

**Comment by andregoncalves** [comment]
It's feature to authorize a contract to spend tokens on behalf of the user.
It's available in manage my crypto screen.

<img width="1068" alt="Screenshot 2021-01-04 at 08 30 21" src="https://user-images.githubusercontent.com/1074/103515708-20927800-4e67-11eb-9dee-ecd89e0dde26.png">

**Comment by rhdelima** [comment]
@andregoncalves Can we close this one and create another ticket for Manage Allowance?

**Comment by andregoncalves** [comment]
@rhdelima yes, please do.
