### ISSUE TITLE
Error: getaddrinfo ENOTFOUND kyc.keyfi.com when trying to get credentials for KeyFi.com

### ISSUE THREAD

**Issue by danielleng** [SelfKeyFoundation/Identity-Wallet#2473]
Getting the following error message after entering all required information to create KeyFi.com credentials:

Error: getaddrinfo ENOTFOUND kyc.keyfi.com when trying to get credentials for KeyFi.com

This error is shown after pressing "Submit".

**Comment by sk91** [comment]
@danielleng checking it out, thanks for reporting

**Comment by sk91** [comment]
Hi @danielleng, we had a dns issue with that domain. It should be resolved now.

**Comment by danielleng** [comment]
Thanks for the quick resolution @sk91 , verified resolved!
