### ISSUE TITLE
Restriced Jurisdictions 

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2479]

**Comment by rhdelima** [comment]
@andregoncalves Can you provide the list of restricted jurisdictions?

**Comment by andregoncalves** [comment]
US only for now (for both residency and nationality)

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/102451800-2ec55380-4074-11eb-975d-18954f0ed453.png)
![image](https://user-images.githubusercontent.com/10294014/102451867-4b618b80-4074-11eb-9431-22405f8a9129.png)
