### ISSUE TITLE
KeyFi: When depositing KEY, SK wallet is NOT shown automatically

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#2488]
http://recordit.co/5o5wcOl3Dz

**Comment by sk91** [comment]
For QA:

- if minimized -- will maximize
- will rise the window to the top
- if it can -- will focus
- will flash the icon to get attention

it will not retain focus and rise abow chrome in most cases, since chrome uses sophisticated focus stealing technicues
