### ISSUE TITLE
KeyFi: Layout issue on WalletConnect send transaction request

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#2489]
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/5f14fe06-e4b9-41ef-aec3-78367f6d6522)

**Comment by sk91** [comment]
fixed in https://github.com/SelfKeyFoundation/Identity-Wallet/pull/2492
