### ISSUE TITLE
MOONP: UI - Terms of service 

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#2500]
<img width="1001" alt="Screenshot 2020-12-15 at 16 56 40" src="https://user-images.githubusercontent.com/1021965/102233326-d3228b00-3ef8-11eb-9444-2ddbee8b746c.png">

**Comment by sk91** [comment]
For QA:

This is not connected to wallet yet, you can see it in storybook

https://selfkeyfoundation.github.io/Identity-Wallet/?path=/story/buy-key-moonpay--agreementmodal

**Comment by rhdelima** [comment]
@sk91 Can you provide instruction on how to test this if it's not connected to wallet yet? I'm getting error when clicking on Connect with Moonpay

**Comment by rhdelima** [comment]
Looks good. Pass
