### ISSUE TITLE
MOONP: UI - buy Key widget

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#2523]
<img width="1158" alt="Screenshot 2020-12-14 at 20 18 09" src="https://user-images.githubusercontent.com/1021965/102119850-6c469880-3e4a-11eb-9f07-b34077ff24a6.png">

**Comment by sk91** [comment]
feature flag:

`FEATURE_MOONPAY=1`

**Comment by rhdelima** [comment]
@sk91 Can you confirm if this is just a widget, right? Currently, clicking the button does nothing so I assume the whole functionality is not yet done.

**Comment by sk91** [comment]
@rhdelima yes

**Comment by sk91** [comment]
@rhdelima https://selfkeyfoundation.github.io/Identity-Wallet/?path=/story/buy-key-buy-key-popup--moonpay-enabled

**Comment by rhdelima** [comment]
Looks good. Pass
