### ISSUE TITLE
HD wallet save unlocked wallet

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#2530]
if the wallet is a pk or an HD wallet, after unlock, if this is a new wallet, an options should apper to store it for future use and secure with password

**Comment by rhdelima** [comment]
Looks good. Pass.
Verified that save wallet prompt is showing when creating new wallet via PK or seed phrase. After confirming, the wallet is saved locally and only need password to unlock it.

![image](https://user-images.githubusercontent.com/10294014/103502902-b6d99480-4e8d-11eb-9bbd-3b9007d596b8.png)
