### ISSUE TITLE
QR code does not load, when exporting wallet

### ISSUE THREAD

**Issue by admrid** [SelfKeyFoundation/Identity-Wallet#2608]
App stuck in loading state, see img:
<img width="1289" alt="Image Pasted at 2021-7-5 13-48" src="https://user-images.githubusercontent.com/32713470/124473558-c6d02380-dd9f-11eb-96b5-f03a6100dc17.png">

**Comment by andregoncalves** [comment]
Thanks @admrid , I think I was able to reproduce it, it seems it only happens the first time you create a wallet keystore. 
Subsequent restarts should work fine. To make sure I'm right, can you check again?

**Comment by admrid** [comment]
@andregoncalves you're right!
