### ISSUE TITLE
Trezor: Hardware Wallet Support Inside SelfKey Identity Wallet

### ISSUE THREAD

**Issue by dfcowell** [SelfKeyFoundation/Identity-Wallet#264]
Overview:
As a user, I can integrate and connect my Trezor hardware wallet to use with the SelfKey Identity Wallet.

Video-Walkthrough: https://www.useloom.com/share/4886cfdf0f1a433da996d243d37d75e2

**Part 1: Signing In With TREZOR:**
117 - Trezor: https://balsamiq.cloud/sv8gyk0/piks2o2/rE9B1
117 - Trezor - Connecting: https://balsamiq.cloud/sv8gyk0/piks2o2/r066D
117 - Trezor + Unable To Connect: https://balsamiq.cloud/sv8gyk0/piks2o2/rF3E2
117 - Trezor - Export Public Keys Confirmation: https://balsamiq.cloud/sv8gyk0/piks2o2/rDCDA
118 - Trezor - Enter PIN: https://balsamiq.cloud/sv8gyk0/piks2o2/rA1CE
118 - Trezor - Enter PIN + Fail: https://balsamiq.cloud/sv8gyk0/piks2o2/r0900
118 - Trezor - Enter PIN + Success and Loading: https://balsamiq.cloud/sv8gyk0/piks2o2/rBDA3
119 - Trezor - Select Address: https://balsamiq.cloud/sv8gyk0/piks2o2/rD9D2

**Part 2: Sending Transactions With TREZOR:**
352 - Send KEY/ETH/ERC-20 + Trezor Messages: https://balsamiq.cloud/sv8gyk0/piks2o2/rF51C

**Comment by rhdelima** [comment]
Passed QA

**Comment by itsmeterrylin** [comment]
Closing issue as passed QA.
