### ISSUE TITLE
“Not Enough Gas": Update Transaction Message Display & UX

### ISSUE THREAD

**Issue by dfcowell** [SelfKeyFoundation/Identity-Wallet#265]
The error message that appears when the wallet user does not have enough gas to send tokens is incorrect and unhelpful. The phrasing of the message may also cause distress to a user unfamiliar with how ERC-20 tokens work.

Wireframe: https://balsamiq.cloud/sv8gyk0/piks2o2/r0329

Key Functionality:
1) User can get notified in a friendly way that they don't have enough gas (ETH) to pay for this transaction. 
2) Display this message across ETH, KEY, and ERC-20 sending transaction workflows.

Dependency:
Please prioritize Issue #312 first as the displayed network transaction fee will be pulled from ETH Gas Station. We can then compare this to the current wallet balance and trigger this message earlier in the workflow for a better UX.

**Comment by itsmeterrylin** [comment]
@rodrigopavezi @rhdelima  For URL to 'here' below:

https://help.selfkey.org/article/87-how-does-gas-impact-transaction-speed

**Comment by sk91** [comment]
@itsmeterrylin @rodrigopavezi  fixed in #379 awaiting review

**Comment by rhdelima** [comment]
Passed on MAC. Waiting for a WIN build

**Comment by rhdelima** [comment]
Passed QA on WIN
