### ISSUE TITLE
USD Pricing Display: Incorrect & Inconsistent USD Values of ETH, KEY, & Tokens

### ISSUE THREAD

**Issue by dfcowell** [SelfKeyFoundation/Identity-Wallet#266]
Frequently the value of tokens or ETH on the dashboard or header will show an incorrect value. Occasionally the correct value and incorrect value will both be shown in different parts of the UI.

- [ ] integrate redux

**Comment by rhdelima** [comment]
Passed QA

**Comment by itsmeterrylin** [comment]
Closing issue as passed QA.
