### ISSUE TITLE
Audit: Dependency list and upgrade out-of-date dependencies

### ISSUE THREAD

**Issue by dfcowell** [SelfKeyFoundation/Identity-Wallet#267]
I believe we've already dealt with the dependency mentioned in #195 but we should review our project dependencies, remove any which we don't need and upgrade any which are out-of-date.

- [x] integrate https://www.npmjs.com/package/npm-check #285 
- [x] upgrade out of date deps #285
- [x] add https://david-dm.org badge to repo #282 
- [x] clean up

**Comment by rodrigopavezi** [comment]
@dfcowell good call. I also think we need to update the custom keythereum module which is out of date. Cheers

**Comment by sk91** [comment]
keythereum upgrade is tracket by #286

**Comment by sk91** [comment]
done
