### ISSUE TITLE
"Resend" Function: Enable For ETH, KEY, & ERC-20 Tokens

### ISSUE THREAD

**Issue by itsmeterrylin** [SelfKeyFoundation/Identity-Wallet#272]
**Issue:** 
If user has a transaction stuck in pending and does not get a final pass/fail from the Ethereum network, they cannot generate a new transaction to replace the old one with a higher gas price. The wallet is essentially locked from sending new transactions.

**Goals:**
Turn on 'resend' function inside the SelfKey Identity Wallet. Previously discussed with Tato in DMs.

**Comment by rhdelima** [comment]
Passed QA

**Comment by itsmeterrylin** [comment]
Closing issue as passed QA.
