### ISSUE TITLE
Switch ETH Address: UX Improvement

### ISSUE THREAD

**Issue by itsmeterrylin** [SelfKeyFoundation/Identity-Wallet#274]
**Enhancement:** 
As a user, I would like to switch ETH addresses between wallets without closing and re-opening the application. 

**Workflow:**
"Switch Accounts" function from the sidebar menu will sign me out of my current ETH address and take me back to the opening screen.

**Mockups:**
_Switch Account Warning:_ 
96 - Warnings & Messages: https://projects.invisionapp.com/d/main#/console/15222689/318229620/preview

"Sign Out" should prompt user to confirm. If user clicks "Yes, Sign Out" they will be signed out of current ETH address and taken back to welcome screen. If they click "no" then they will stay on current screen inside the application.

Sidebar: 
- Remove "About SelfKey" link
- Remove "Submit An Idea" link

**Comment by itsmeterrylin** [comment]
Updated URLs to Invision prototypes and removed Balsamiq URLs

**Comment by Horizon88** [comment]
@oanamangiurea may be useful to reference.
