### ISSUE TITLE
Auto-Import: ERC-20 Tokens on an ETH Address

### ISSUE THREAD

**Issue by itsmeterrylin** [SelfKeyFoundation/Identity-Wallet#275]
**Enhancement:**
As a user, I would like the SelfKey Identity Wallet to automatically scan my ETH address and populate the ERC-20 tokens inside the dashboard by verifying the token contract addresses against the Ethereum blockchain. This will save me time from finding contract addresses and manually adding them into the dashboard.

**Mockups:**
TBD by Terry

Aha! Link: https://kycc.aha.io/features/SKEY-184

**Comment by oanamangiurea** [comment]
Obsolete. Closing
