### ISSUE TITLE
Allow lookup of tokens on "add token" screen by trading symbol

### ISSUE THREAD

**Issue by dfcowell** [SelfKeyFoundation/Identity-Wallet#287]
We bundle the wallet with a long list of token definitions for common tokens which we use to populate the decimal and symbol fields when a user enters a smart contract address, however this feature would be more usable if a user could enter the three-letter ticker symbol (e.g. KEY) which we try to match against our list.

If we can't find the token in our list, or it's not the token the user is trying to add (there are some cases where more than one token has the same ticker symbol) we can then show them the "advanced" UI that lets them specify all three fields.

- [ ] Design a two-step UI & flow for adding custom tokens with search/autocomplete input
- [ ] Update list of token contracts shipped with wallet to include token names (in order to distinguish between tokens that share a trading symbol)
- [ ] Implement updated UI
- [ ] Database migration to persist token names in wallet file

@itsmeterrylin provisionally adding this to 0.0.9, but it can be pushed back if necessary.

**Comment by oanamangiurea** [comment]
Obsolete, and has been addressed by another issue. Closing
