### ISSUE TITLE
(1/3) Staking Functionality: SelfKey Marketplace (Before)

### ISSUE THREAD

**Issue by itsmeterrylin** [SelfKeyFoundation/Identity-Wallet#302]
**Overview:**
Staking KEY tokens is a critical aspect of the SelfKey Marketplace. We are building this first iteration of staking with Crypto Exchanges.

**Functional Requirements:**
User can view the SelfKey Marketplace and details of a listing.
Application will check if a user has enough KEY in current wallet to stake.
If user does not have enough, it will trigger a message if user tries to stake.

**Mockups:**

501 - Exchange Marketplace: 
https://projects.invisionapp.com/d/main#/console/15222689/316492324/preview

502 - Exchange Details + Open Account + Inactive https://projects.invisionapp.com/d/main#/console/15222689/316492325/preview

503 - Exchange Details + Stake Inactive + No KEY: 
https://projects.invisionapp.com/d/main#/console/15222689/317270545/preview

Aha! Link: https://kycc.aha.io/features/SKEY-151

**Comment by rodrigopavezi** [comment]
@itsmeterrylin I have reviewed the screen and I have a couple of questions.

1. is there a error flow for 505 when transaction of staking fails for some reason?
2. Why 508 is different from 505? Can't we reuse it somehow?

Cheers

**Comment by itsmeterrylin** [comment]
**Q: Is there a error flow for 505 when transaction of staking fails for some reason?**
A: Yes. Most common reason will be not enough ETH to pay for gas price to interact with the smart contract. https://balsamiq.cloud/sv8gyk0/piks2o2/r5319

**Q: Why 508 is different from 505? Can't we reuse it somehow?**
A: Sending the KEY deposit and reclaiming it are two different actions so the explainer text is slightly different, best to customize a bit to clarify. But happy to hear thoughts on keeping it DRY if that can be achieved.

**Comment by rhdelima** [comment]
@sk91 @rodrigopavezi 

Need to change how exchanges are listed.

![image](https://user-images.githubusercontent.com/10294014/45586055-a995e600-b922-11e8-949e-4cb722d7c4e0.png)

**Comment by rodrigopavezi** [comment]
@rhdelima please review new version with the fix https://console.cloud.google.com/storage/browser/selfkey-builds/staging/stacking/2018.09.17.08/?project=kycchain-master 

Cheers

**Comment by rhdelima** [comment]
@sk91 @rodrigopavezi 

1. Update icon
2. Add space after "You need at least 25 KEY tokens" to unlick this listing

![image](https://user-images.githubusercontent.com/10294014/45618886-e7714680-baa9-11e8-8fde-fde3e43e6d5c.png)

**Comment by rodrigopavezi** [comment]
@rhdelima you can review changes here https://console.cloud.google.com/storage/browser/selfkey-builds/staging/stacking/2018.09.19.19/. Cheers
