### ISSUE TITLE
(2/3) Staking Functionality: SelfKey Marketplace (During)

### ISSUE THREAD

**Issue by itsmeterrylin** [SelfKeyFoundation/Identity-Wallet#318]
**Overview:**
Staking KEY tokens is a critical aspect of the SelfKey Marketplace.
We are building this first iteration of staking with Crypto Exchanges.

**Functional Requirements:**
User can stake KEY for current marketplace as they have enough balance in public address.
User can select send KEY stake with a default gas price (Issue #312).
User can select advanced options to stake KEY stake by toggling panel.
If transaction is pending, marketplace listing will display appropriate messaging.

**Mockups:**
Send Stake:
https://projects.invisionapp.com/d/main#/console/15222689/317270546/preview

Send Stake + Error:
https://projects.invisionapp.com/d/main#/console/15222689/317302846/preview

Send Stake + Confirm: https://projects.invisionapp.com/d/main#/console/15222689/317302847/preview

Send Stake + Transaction Error: https://projects.invisionapp.com/d/main#/console/15222689/317302848/preview

Transaction Processing:
https://projects.invisionapp.com/d/main#/console/15222689/317302849/preview

Pending Deposit:
https://projects.invisionapp.com/d/main#/console/15222689/317302850/preview

**StakeManager Contract Usage:**
https://github.com/SelfKeyFoundation/selfkey-staking
Please view the README.md on how to interact with the StakingManager contract.

**StakingManager Contract Overview** (From Carlos)
- Any address can stake tokens given a serviceID and a "service owner" address (that can be zero (0x0) for public/global stakes).
- By default there's no stake minimum or lock period.
- Any address can set "minimum stake" and/or "lock period" parameters for serviceIDs under that same caller address (which would be the "service owner" of all those serviceIDs).
- If a minimum is set for a certain service, no one can stake less than that.
- Stakes can be added incrementally to a given service.
- Withdrawing the stake for a given service necessarily withdraws all the stakes for that service, no partial withdraw is allowed.
- Only the stake sender can make a withdraw.
- Only the service owner can change parameters (minimum stake and lock period) for a given serviceID under its address.
- Changing "minimum" and "lock period" parameters for a service does not affect the previously made stakes on it, but verifiers can decide to check against the current minimum if desired.

Aha! Link: https://kycc.aha.io/features/SKEY-185

**Comment by itsmeterrylin** [comment]
Updated URLs from Balsamiq to Invision prototypes.

**Comment by cbruguera** [comment]
@rodrigopavezi @itsmeterrylin 
As @sk91 pointed out in mattermost #ID-Wallet-integrations, now it's no longer possible (nor considered necessary) to set a minimum stake parameter per service, since that requirement is always up to the relying party, or the one interested to check the status for a user stake on a certain serviceID. Probably it'd be good to update the issue.
