### ISSUE TITLE
Cannot add custom token

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#320]
When attempting to add a custom token. It won't go back to the Manage My Crypto screen and instead show a read popup error box in the top right corner without any error details. See image below.

<img width="1282" alt="screen shot 2018-07-26 at 07 34 59" src="https://user-images.githubusercontent.com/1659305/43257530-6e9260e6-90a6-11e8-828f-fd2169eb63cb.png">

**Comment by sk91** [comment]
fixed in #322

**Comment by rhdelima** [comment]
Passed QA
