### ISSUE TITLE
Update Outbound URLs to HTTPS

### ISSUE THREAD

**Issue by Horizon88** [SelfKeyFoundation/Identity-Wallet#321]
**Overview:** 
Update all outbound URLs to websites such as Help Desk and SelfKey.org with HTTPS.
http:// -> https://

**Locations:**
Terms of Service
Navigation Sidebar
SelfKey Marketplace
SelfKey ID

**Comment by rhdelima** [comment]
Passed QA. Links on the marketplace need updating on airtable.
https://cl.ly/0A083K1c3y1j

**Comment by itsmeterrylin** [comment]
Closing issue as passed QA.
