### ISSUE TITLE
Integrate selfkey-ui my crypto detail table with wallet

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#328]
@sk91 as discussed today I am adding this card so you can help on getting this price react refactoring done for next release. 

I have created a react table component and it is on this branch feat/my-crypto-details on this PR https://github.com/SelfKeyFoundation/selfkey-ui/pull/7

You can follow what I have done with my crypto as this component requires the tokens list. Let's have a chat tomorrow about it.

Thanks for helping out with this.

Cheers

**Comment by sk91** [comment]
fixed in #336
