### ISSUE TITLE
Open Bugs: Version 0.0.9

### ISSUE THREAD

**Issue by itsmeterrylin** [SelfKeyFoundation/Identity-Wallet#376]
- [x] SelfKey ID: Profile pic is not saved >> https://cl.ly/310t2u0j0c3T
- [ ] Remove: "Your Staking Status" text in all Marketplace pages
- [x] ToS: Update support@selfkey.org email to help@selfkey.org

**Comment by tmchedlishvili** [comment]
@itsmeterrylin 
`SelfKey ID: Profile pic is not saved`: I'm not able to replicate it on dev branch

**Comment by rhdelima** [comment]
@tmchedlishvili  Confirmed with @itsmeterrylin . Tooltip should be removed also.

<img width="982" alt="screen shot 2018-09-14 at 4 03 01 am" src="https://user-images.githubusercontent.com/10294014/45512827-84469200-b7d3-11e8-96cc-8e51aa152815.png">

**Comment by rhdelima** [comment]
Passed QA. The profile pic issue was already fixed during 0.1.0 beta release
