### ISSUE TITLE
Staking & KEY Token Deposit

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#386]

**Comment by rhdelima** [comment]
@sk91 / @rodrigopavezi 

1. Some crypto exchanges are showing blank screen when viewing
2. Update Coming Soon button to Unlock Marketplace
3. Update layout to match design

https://www.useloom.com/share/35f009126415426abd4cf45ebe91ce44
<img width="1680" alt="screen shot 2018-09-14 at 7 50 12 am" src="https://user-images.githubusercontent.com/10294014/45521935-dcd95780-b7f2-11e8-9c18-7259168cfffb.png">
