### ISSUE TITLE
Bug when uploading documents on selfkey id setup 

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#407]
It should tick that National ID has been been uploaded

<img width="1648" alt="screen shot 2018-08-31 at 12 18 35 am" src="https://user-images.githubusercontent.com/1659305/44900667-7984fb00-ad05-11e8-8227-90f827ca58ad.png">

**Comment by rhdelima** [comment]
@tmchedlishvili / @rodrigopavezi 
Passed QA on MAC. waiting for WIN build

**Comment by rodrigopavezi** [comment]
@rhdelima win builds sometimes takes longer than the mac so it will be in another folder on GCS. You can always look into the folders with the latest date and take the latest win build. Here is the latest https://console.cloud.google.com/storage/browser/selfkey-builds/dev/2018.09.13.20/?project=kycchain-master now. Cheers

**Comment by rhdelima** [comment]
Passed QA
