### ISSUE TITLE
Bug when making transaction, balance is not updating

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#408]
Given a user is sending coins to another wallet 
When wallet finishes to send
And checking for new balance returns it
Then balance should be updated

Given a user is sending coins to another wallet
When wallet finishes to send
And checking for new balance fails
Then it should retry to get new balance

**Comment by rodrigopavezi** [comment]
@tmchedlishvili could you work on this issue? Cheers

**Comment by rhdelima** [comment]
@tmchedlishvili 
Balance is not updating https://cl.ly/34985c95ab35
