### ISSUE TITLE
Update: Transaction History UI Dashboard

### ISSUE THREAD

**Issue by itsmeterrylin** [SelfKeyFoundation/Identity-Wallet#410]
Overview:
Update UI elements in Transaction History Dashboard

Invision Link:
https://projects.invisionapp.com/d/main#/console/15222689/316491951/preview

**Comment by rhdelima** [comment]
@tmchedlishvili 
Transaction history is not loading on my end. See screenshot and log. Waited for 30 minutes and also did one transaction but still not showing.
[log.log](https://github.com/SelfKeyFoundation/Identity-Wallet/files/2381158/log.log)

<img width="1653" alt="screen shot 2018-09-14 at 5 57 54 am" src="https://user-images.githubusercontent.com/10294014/45518220-5a956700-b7e3-11e8-9be6-339c3d4ae9c4.png">

**Comment by rhdelima** [comment]
Passed QA
