### ISSUE TITLE
URL Updates: 404 Errors

### ISSUE THREAD

**Issue by itsmeterrylin** [SelfKeyFoundation/Identity-Wallet#444]
1) Terms Of Service: "How It Works" should link to: https://help.selfkey.org/
![404 url - how it works](https://user-images.githubusercontent.com/30673971/45560697-dc9d8400-b813-11e8-979a-92f6e017cf52.png)

2) Add Custom Tokens: Hover on "Token Address" should link to:  https://help.selfkey.org/

![404 url - add token](https://user-images.githubusercontent.com/30673971/45560701-df987480-b813-11e8-8d30-8ad561508aba.png)

**Comment by rodrigopavezi** [comment]
@rhdelima please review this. Fix has been deployed. cheers

**Comment by rhdelima** [comment]
Passed QA
