### ISSUE TITLE
Email input validation

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#463]
In the SelfKey ID, I'm able to add my email address. Right now that has a validation to allow save, the validation being the address should have at least the @ sign and one character after that. That is not enough, since abc@a is not valid in real life.

**We need a better validation rule**, found this regex that could help https://emailregex.com and more on the matter here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email

**Comment by sk91** [comment]
@oanamangiurea Adding this to json schema epic. Json schema supports regexp validations

**Comment by oanamangiurea** [comment]
@rodrigopavezi reopening this as I can still save my email as xxx@x

**Comment by eduardosmoura** [comment]
DEV test evidence: http://recordit.co/8IotNhUpsd

**Comment by rhdelima** [comment]
@oanamangiurea @eduardosmoura ,

Can you confirm if this is ONLY implemented on Create SelfKey ID form? Adding / Edit email not included on the fix?

**Comment by eduardosmoura** [comment]
@rhdelima This fix was implemented on Create Selfkey ID form, but we already changed the email validation (removed html5 chrome validation) on Add/Edit Information forms (issue #920).
