### ISSUE TITLE
Not enough gas error message

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#472]
@oanamangiurea commented on [Thu Oct 04 2018](https://github.com/SelfKeyFoundation/selfkey-staking/issues/44)

When I want to perform a transaction, yet I don't have any ETH in my wallet to pay for, I get the following error - [screenshot](https://gyazo.com/917a64438cb169e426a42d7043d580b2)

Correct should be -see [InVision](https://projects.invisionapp.com/d/main#/console/15222689/318457086/preview)

You don't have enough Ethereum (ETH) to pay for the network transaction fee. Please transfer some ETH to this address and try again. Your ETH address of this wallet is listed below.

---

@cbruguera commented on [Fri Oct 05 2018](https://github.com/SelfKeyFoundation/selfkey-staking/issues/44#issuecomment-427248030)

@oanamangiurea perhaps this issue should be raised in the ID-Wallet repository. This one holds the backend (smart contract) aspect of staking, and what is being described looks like a UI bug, not an unexpected response from the contract. Right?

**Comment by rodrigopavezi** [comment]
@oanamangiurea @itsmeterrylin for this one we need a different message because it is an error when making the transaction which there is nothing todo with the eth balance in the wallet. Cheers
