### ISSUE TITLE
Some ledger modals are not working

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#546]
1. Confirm Transaction modal only shows up less than 1 sec and closes
2. Timeout modal is not showing
3. Reject modal is also not showing

https://www.useloom.com/share/3504bdc17b9b4a69a76c8156311b7cd9

**Comment by Horizon88** [comment]
is this still current @rhdelima ?

**Comment by rhdelima** [comment]
@Horizon88 Yes. This issue still exists with the latest version of SelfKey wallet.
