### ISSUE TITLE
Design KYC confirmation popup

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#564]
In Identity Wallet, when user is in marketplace section in exchanges and clicks on create account button. A popup should appear requesting for KYC confirmation. It should serve the same purpose as this screen in LWS popup https://projects.invisionapp.com/d/main#/console/15164754/315303923/preview

**Comment by oanamangiurea** [comment]
Done. Example for incorporations, works the same for exchanges https://projects.invisionapp.com/d/main#/console/15222689/345775784/preview
