### ISSUE TITLE
UI Update: Add real-time dashboard updates

### ISSUE THREAD

**Issue by vitalikda** [SelfKeyFoundation/Identity-Wallet#585]
If you receive tokens, while the Wallet is running, the balance amount is not udpated.

**Workarounds:**
- You have to quit the Wallet and sign in again to update the balance.

**New Feature:**
- Add a refresh button
- Add a functionlity, which will check transactions regularly and update the balance automatically

**Comment by CortecKYC** [comment]
@oanamangiurea Is this ticket still relevant?

**Comment by oanamangiurea** [comment]
@CortecKYC no, issue has been fixed. Closing it
