### ISSUE TITLE
Create Selfkey Id

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#604]
As IDW user I want to save my identity attributes and documents in the wallet so that it will help me to control my identity digitally when applying for services 

- overview
  - [x] render all attributes
  - [x] display basic info
  - [x] fix react-json-form-theme to be importable as a library
  - [x] fix react-json-form and react-json-form-theme to have FileObject widget
  - [x]  edit attribute * WIP
  - [x]  add information * WIP
  - [x] add document --same as add information for now
  - [x] delete attribute
  - [x] delete document  --same as add information for now
  - [x] edit document --same as add information for now
  - [x] add avatar upload
  - [x] add a utility function that determines if schema contrains documents or not
  - [x] use uiSchema in forms

**Comment by rhdelima** [comment]
@sk91 @rodrigopavezi I believe this is not ready for QA yet. Please see recording: http://recordit.co/aVG5pzMVch
