### ISSUE TITLE
Unlock Wallet

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#609]
Feature: As company admin I want to unlock my wallet so that I use it to hold my Corporate Identity

	Scenario: Unlock Wallet
		Given a user has opened the wallet
		When user clicks on Unlock Wallet
		Then user should see different options to unlock a wallet

	Scenario: Unlock existing wallet option
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		When user selects the option 'Existing Address'
		Then user should be allowed to select a wallet
		And user should be able to enter a passowrd for the selected wallet

	Scenario: Unlock existing wallet using right password
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		And user selected the option 'Existing Address'
		When user clicks on Unlock
		Then user should see the wallet dashboard
	
	Scenario: Unlock existing wallet using worng password
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		And user selected the option 'Existing Address'
		When user clicks on Unlock
		Then user should see an error message saying password is worng

	Scenario: Unlock new wallet option
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		When user selects the option 'New Address'
		Then user should be allowed to select a keystore file from the file system
		And user should be able to enter a passowrd for the selected keystore file

	Scenario: Unlock new wallet using right password
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		And user selected the option 'New Address'
		When user clicks on Unlock
		Then user should see the wallet dashboard

	Scenario: Unlock new wallet using worng password
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		And user selected the option 'New Address'
		When user clicks on Unlock
		Then user should see an error message saying password is worng

	Scenario: Unlock Wallet, private key option
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		When user selects the option 'Private Key'
		Then user should be able to enter a private key to unlock the wallet

	Scenario: Unlock Wallet using valid private key
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		And user selected the option 'Private Key'
		When user clicks on Unlock
		Then user should see the wallet dashboard
	
	Scenario: Unlock Wallet using invalid private key
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		And user selected the option 'Private Key'
		When user clicks on Unlock
		Then user should see an error message saying private key is invalid

	Scenario: Unlock Wallet ledger option
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		When user selects the option 'Ledger'
		Then user should be able to connect to the ledger
		And user should be ablet to select a wallet

	Scenario: Unlock Wallet using unlocked ledger
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		And user selected the option 'Ledger'
		When user clicks on Connect to Ledger
		And user selects a wallet
		Then user should see the wallet dashboard

	Scenario: Unlock Wallet using locked ledger
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		And user selected the option 'Ledger'
		When user clicks on Connect to Ledger
		Then user should see an error message saying it cannot connect to Ledger

	Scenario: Unlock Wallet trezor option
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		When user selects the option 'Trezor'
		Then user should be able to connect to the trezor
		And user should be ablet to select a wallet

	Scenario: Unlock Wallet using unlocked trezor with right pin
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		And user selected the option 'Trezor'
		When user clicks on Connect to Trezor
		And user enter the right pin
		And user selects the wallet
		Then user should see the wallet dashboard

	Scenario: Unlock Wallet using unlocked trezor with worng pin
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		And user selected the option 'Trezor'
		When user clicks on Connect to Trezor
		And user enter the worng pin
		Then user should see an error message saying the pin entered is incorrect

	Scenario: Unlock Wallet using locked trezor
		Given a user has opened the wallet
		And user clicked on Unlock Wallet
		And user selected the option 'Trezor'
		When user clicks on Connect to Trezor
		Then user should see an error message saying it cannot connect to Trezor

**Comment by rhdelima** [comment]
Hi @rodrigopavezi ,

Please see issues below:

Existing Address:
- Incorrect error message
- Password field extends
![image](https://user-images.githubusercontent.com/10294014/52315042-37688f80-29f0-11e9-9d06-6d59ba0c6cec.png)

New Address:
- Update error message
![image](https://user-images.githubusercontent.com/10294014/52315167-cd9cb580-29f0-11e9-9953-675ecfeb9b93.png)

Private Key:
- Update error message
![image](https://user-images.githubusercontent.com/10294014/52315212-00df4480-29f1-11e9-9da3-1a5bc8a0b51e.png)

Ledger:
- Unable to login
![image](https://user-images.githubusercontent.com/10294014/52314257-d7bcb500-29ec-11e9-9ca5-e27af9ec4869.png)


Thanks!

**Comment by rodrigopavezi** [comment]
@rhdelima awesome, thanks for that. I think it would good if you could create a separated issue on github for each one of this writing the steps in Gherkin language. Something like this

```
Given User want to unlock with ledger
when user clicks on connect button 
Then it should show a list of wallet addresses
```

Let me know if you need any help with that.

Cheers
