### ISSUE TITLE
Create Wallet UI Issues

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#625]
- [ ] Unlock Screen needs to use the proper logo, including the writing https://gyazo.com/29ea41f87308be6609bbec9890a2c653 -> https://projects.invisionapp.com/d/main#/console/15222689/316491407/preview 
- [ ] All modals need to have a 70px padding bottom https://gyazo.com/d12876298b00de9bb71c26f32d4ef4ae 
- [ ] Create wallet pages should have the proper Selfkey Logo, as in the design https://projects.invisionapp.com/d/main#/console/15222689/316491409/preview 
- [ ] Create wallet wizard buttons needs to be 44px height 
- [ ] The password strenght line makes no sense https://gyazo.com/2a4673883e63b4c9f503e78d65c2cce3 it looks like a loader. Please use the old version that we have in the design as well with 4 different boxes https://projects.invisionapp.com/d/main#/console/15222689/316491409/preview
- [ ] Modal headers font size should be 18px not 15px
- [ ] Use the proper copy button like in the design https://gyazo.com/c500173e1ba7c107e2aa71f76119fdea - this one looks disabled, and we don't use this style anymore 
- [ ] Input Labels should be in Uppercase (see above image) 
- [ ] Use corect big icon in the print private keys step https://gyazo.com/8ed1bc1db3992e552ecd1086b6fe3564 . Please see design

**Comment by rodrigopavezi** [comment]
@oanamangiurea I need the logo in SVG. Every image we have is in svg so it would be cumbersome to use a PNG and it would require it to be in the wallet and not in the selfkey-ui as it won't import selfkey-ui if it has an asset like a png image. Let me know if you need further about the issue but trust me. Having it svg will save us from a lot of complications. Cheers

**Comment by oanamangiurea** [comment]
@rodrigopavezi solved that with Ferenc, he'll update with the svg logo, including the font part (the Selfkey name that is), so we don't have to load one more font

**Comment by rodrigopavezi** [comment]
This looks to be out of date. closing for now
