### ISSUE TITLE
Manage Applications

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#637]
As a user who applied to Incorporation I want to see the application status so that I know when it is finished

**Comment by rodrigopavezi** [comment]
This is a low priority issue and should not be considered for this next release. It is just in case we are out of work so we can continue with this. Cheers

**Comment by rodrigopavezi** [comment]
https://projects.invisionapp.com/d/#/console/15222689/346095675/preview

https://projects.invisionapp.com/d/#/console/15222689/346095676/preview

**Comment by CortecKYC** [comment]
**Note:** this task had not been properly assessed. It was way more complex than expected.
We're scoping it out until we really need to get back to it.  But, to avoid running into blockers again, @andregoncalves will re-assess it, cut down into pieces and prepare it so when we get back to it in a few weeks, we don't find ourselves overwhelmed again.

**Comment by CortecKYC** [comment]
https://confluence.kyc-chain.com/display/~andre/Manage+Applications+Spec

**Comment by eduardosmoura** [comment]
https://projects.invisionapp.com/d/main/default/#/console/15222689/358880547/preview
