### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#641]
<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

#### Opening screen
- [x] Divider between HELP and QUIT icons
#### Create Wallet setup
  - [x] Password Warning modal - change color of button
  - [x] Step 1 - password strong checker
  - [x] Step 3 - change color of continue button
  - [x] Step 4 - change color of continue button

#### Menu
- [x]  Add missing menu items (Quit, Help & Support)
- [x]  Add hover state to menu items
- [x] Aligment of menu items
- [x] Version number
- [x] Menu drawer - remove horizontal scroll (appears on 2nd opening)

#### Use existing Wallet
- [x]  Position of close icon
- [x] Steps Next button size

#### Modals
- [x] Close modal - smaller window, show logo and centre aligned texts
- [x] All Modals bottom padding

#### Dashboard box styles
- [x] Remove box shadow
- [x] Change bg
- [x] Alignment of 3 ones
- [x] Transactions box
- [x] Dashboard horizontal scroll
- [x] Manage My Tokens screen - typography, missing icon

#### Send ETH
- [x] Remove shadows from boxes
- [x] Send to Address (reduce width of modal box)

#### Manage crypto (whole screen and popups)
- [x] Add Custom Token - Inputs
- [x] Add Custom Token - Alignment of screen

#### Header
- [ ] Fix header at the top when scrolling
- [ ] Header (navbar) height - decrease by 10px

#### Marketplace
- [x] Listing boxes (padding and Transactions text is not the same as in Invision file)
- [x] Style of Coming soon button

#### Crypto Exchanges
- [x] Style of View button
- [x] Style of Back button

#### Exchange Details
- [x] Status in header
- [x] Need more space (paddings)

#### Incorporation
- [x] Detailed view - Status (Offshore Tax, Dividends Received, etc.) , and changed Button name (Incorporate Now) + icon
- [x] Detailed view - Add extra infos under the Button - Price in USD and KEY below with info button
- [x] Incorporate Pay Fee page
- [x] Incorporation Checklist modals

#### Identity Summary
- [x] Default avatar image
- [x] Style of Access Marketplace box
- [x] Add information Modals
- [ ] Delete information and history modal
- [ ] Add documents Modals

#### Address Book
- [x] "Create and assign labels..." text is not the same like in the Invision
- [ ] Table of Addresses (Need a modal window for delete icon)
- [x] Alignment of Add/Edit Address modals and Font size of buttons

#### Popups
- [ ] Transparency for popups (show the app with opacity instead of hiding it)

- [x]  Add Custom Token screen - input fields with labels, buttons, alignment

<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

**Comment by andregoncalves** [comment]
@designhorf can you also take a look at the incorporations header title and icon?
