### ISSUE TITLE
White screen is displayed when clicking Legal tab on some incorporations 

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#655]
Steps to recreate:
1. Open and unlock Wallet
2. Go to Menu > Marketplace > Incorporations
3. Click Details on British Virgin Islands VISTA
4. Click Legal Tab

Expected Result:
Legal tab id displayed with details

Actual Result:
White screen is displayed

Recording: http://recordit.co/2d3cjfmewm

**Comment by rodrigopavezi** [comment]
@andregoncalves can you fix this one when you have a chance?

**Comment by andregoncalves** [comment]
Yes, I already planned to looked at it.

**Comment by rhdelima** [comment]
Passed QA.
