### ISSUE TITLE
Welcome screen layout issues

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#665]
1. Right Margin is too wide
2. Left Margin is missing
3. Remove horizontal and vertical scrollbars

Screenshot:
![Welcome Screen.jpg](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/e271cf8d-8b5b-4165-9be7-7e9f15b31aaf)

Design: https://projects.invisionapp.com/d/main#/console/15222689/316491407/preview

**Comment by rodrigopavezi** [comment]
@designhorf  I could replicate this when maximising the screen. Could you please take a look at it when you have a chance? Cheers

**Comment by designhorf** [comment]
@rodrigopavezi sure!

**Comment by rhdelima** [comment]
Passed QA
