### ISSUE TITLE
Missing Terms of Service Warning and How it works screen

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#666]
1. If user doesn't agree with the Terms of Service, app should display the Terms of Service Warning or Need to Accept Terms modal.
https://projects.invisionapp.com/d/main#/console/15222689/316491405/preview

2. After agreeing to terms of service, How it works screen should be displayed.
https://projects.invisionapp.com/d/main#/console/15222689/316491406/preview

**Comment by rodrigopavezi** [comment]
we don't need the How it works screen anymore.

**Comment by rhdelima** [comment]
Failed QA on mac. Need to Accept Terms modal is not shown on mac. See recording - http://recordit.co/1EXFlKFanp

**Comment by rhdelima** [comment]
Passed QA
