### ISSUE TITLE
Create SelfKey ID workflow is not triggered

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#669]
Steps to replicate:
1. Open and unlock wallet
2. Go to Menu > SelfKey ID
3. Check screen

Expected Result:
- Setup Your SelfKey ID screen is displayed.
- When Create SelfKey ID button is clicked, it should trigger the Create SelfKey ID workflow

Actual Result:
Goes directly to SelfKey Identity Wallet dashboard

http://recordit.co/sOSQCGGkQ1

**Comment by rodrigopavezi** [comment]
https://projects.invisionapp.com/d/main#/console/15222689/316491813/preview

**Comment by rhdelima** [comment]
Passed QA.
