### ISSUE TITLE
SelfKey ID Wallet issues

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#670]
Add Information

1. Fix Add Information drop down UI
   ![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/2b676cc8-4ed0-4a30-8c61-6a6331ef375a)
2. Remove Documents on Add Information drop down
3. Field Names should be displayed outside input field
4. Hide Label on Add Information screen 1
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/d5dfe97d-8f88-434d-9770-2f3954072ab6)
5. Missing placeholder on Label field
6. Should not display error message by default upon selecting an option on Information field
    http://recordit.co/8SPC8LcJDF
7. When deleting information, should display popover instead of a modal
   https://projects.invisionapp.com/d/#/console/15222689/317026847/preview

Add Documents

1. Fix Add Documents drop down UI
2. Update modal label from Add Information to Add Documents
3. Remove Informations on drop down
4. Hide Label on Add Document screen 1
5. Missing placeholder on Label field
6. Should not display error message by default
7. Incorrect UI for upload
    ![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/fb46ff55-d44f-4b84-809a-a4f1d6d443c1)
8. When deleting document, should display popover instead of a modal
   https://projects.invisionapp.com/d/#/console/15222689/317026847/preview

**Comment by rhdelima** [comment]
@rodrigopavezi I won't pass this ticket since some items are not yet fixed. But we can close this now since I logged those issues on separate ticket.

**Comment by rodrigopavezi** [comment]
@rhdelima sounds good, just few items of this ticked was fixed. cheers

**Comment by rodrigopavezi** [comment]
other issues are here: https://github.com/SelfKeyFoundation/Identity-Wallet/issues/733
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/742
