### ISSUE TITLE
Missing scroll on download public key and print private key screens

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#695]
![Screenshot 2019-02-20 at 13.06.25.png](https://images.zenhubusercontent.com/5b7bd3b852bce06c3c5c53c0/d5be52dd-ec9a-4281-b3dc-ff4a166d4f52)

![Screenshot 2019-02-20 at 13.06.34.png](https://images.zenhubusercontent.com/5b7bd3b852bce06c3c5c53c0/a632a297-6f60-4ab7-aadd-3732c253369e)

![Screenshot 2019-02-20 at 13.06.46.png](https://images.zenhubusercontent.com/5b7bd3b852bce06c3c5c53c0/857d37d9-31ec-4c98-948f-dd0447d67b4f)

**Comment by rhdelima** [comment]
@rodrigopavezi I still don't see the scroll on these screens. Can you please clarify? Based on the design, these screens don't have scroll.

**Comment by rodrigopavezi** [comment]
@rhdelima I didn't add scroll but I fixed the sizes so it won't go bellow the screen size. Are you seeing it like the images above?
