### ISSUE TITLE
Icon and back button incorporations visual tweaks

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#700]
@designhorf can you please take a look at this two issues:
![Screen Shot 2019-02-21 at 12.34.53.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/963c0574-c97e-4f3f-a306-ee4ff3af4d79)
The icon doesn't look right somehow...

![Screen Shot 2019-02-21 at 12.35.02.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/3e7efb52-1196-4f1e-85b4-730917705cfa)
The back button seems out of place.
To get to this screen, just click the details link on the last column of incorporations table.

**Comment by designhorf** [comment]
@andregoncalves sure! And as I've seen, Back button is missing from the 1st screen, right?

**Comment by andregoncalves** [comment]
I don't think it was on the invision prototype.

**Comment by rhdelima** [comment]
Passed QA

![image](https://user-images.githubusercontent.com/10294014/53290516-fe962c00-37df-11e9-93c5-c989b6403fdb.png)

![image](https://user-images.githubusercontent.com/10294014/53290520-048c0d00-37e0-11e9-8176-153427762d54.png)
