### ISSUE TITLE
SelfKey ID - Missing default profile avatar

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#714]
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/2f6ff3d7-91ca-4208-96f9-7dd587d1d414)

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/869bb2b7-4b78-4e53-8540-8e9d96deb310)

**Comment by designhorf** [comment]
This bug is fixed in the following PR https://github.com/SelfKeyFoundation/Identity-Wallet/pull/731 (Work in progress). Assigned myself to this issue.
