### ISSUE TITLE
Update Activity section on KEY and ETH modals

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#716]
1. Unable to scroll down
2. Add pagination
3. Sent tx should display Sent instead of Received
4. Sent tx should display '- amount'
5. For eth tx, wallet should display the actual amount

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/52bb23f9-9db5-4c9f-bbc0-f207c32dac89)

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/6125ac11-c1d4-4071-9b7f-fdfcf82e0000)

**Comment by rhdelima** [comment]
@rodrigopavezi Should we follow design on link below or copy the transaction history on dashboard just like the previous release

https://projects.invisionapp.com/d/main#/console/15222689/316491967/preview

**Comment by rodrigopavezi** [comment]
@oanamangiurea can you help us with this issue. We were wondering if we could reuse the table from the dashboard to show history on the send transaction as the design is missing pagination. Thoughts?

Cheers

**Comment by oanamangiurea** [comment]
@rhdelima @rodrigopavezi yes, you can use that one. Does it have pagination or scroll to fix the issue?

**Comment by rodrigopavezi** [comment]
@oanamangiurea that is how it is looking like now 
<img width="2032" alt="screenshot 2019-02-27 at 10 32 32" src="https://user-images.githubusercontent.com/1659305/53493828-13422080-3a7b-11e9-899c-92071dcaad98.png">
