### ISSUE TITLE
Data added using previous beta builds are lost

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#717]
Data added using previous beta builds should be retained. These data refers to:
1. Tokens added on My Crypto 
2. Labels and addresses on Address Book
3. SelfKey ID Wallet attributes and documents

Also, if attributes and/or documents where already added using the previous builds, don't trigger Create SelfKey ID workflow.

**Comment by rodrigopavezi** [comment]
@rhdelima are you using a different Ethereum wallet or the same wallet?

**Comment by rhdelima** [comment]
@rodrigopavezi I'm using 0.3.0 beta and then the latest build on dev.

**Comment by rhdelima** [comment]
Passed QA on WIN

**Comment by rhdelima** [comment]
National ID and National ID Selfie are saved on National ID document on the new wallet version. Passing this for now since Max is still working on the fix of the document.
