### ISSUE TITLE
Fix UX of selfkey id document upload

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#733]
Current: ![Image Pasted at 2019-2-26 10-37.png](https://images.zenhubusercontent.com/5b7bd3b852bce06c3c5c53c0/36517a6d-4f71-42f6-9633-fd116454d347)

Expected: https://projects.invisionapp.com/d/main#/console/15222689/342315357/preview

**Comment by sk91** [comment]
Also in scope:

- fix field ordering for attributes
- fix date widget

**Comment by rhdelima** [comment]
@rodrigopavezi , Can we close this one now? Won't pass this one since I logged bugs related to documents.
