### ISSUE TITLE
SelfKey ID - Attribute issues

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#742]
--Add Information modal
1. After adding an information, remove it from the drop down on Add Information modal 
**_Oana edit:_** actually this is a special case, some attributes can be doubled, like email, nationality, workplace Anything that a person can have multiple should still be there
2. Drop down box is too small. User will have difficulty in selecting an option
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/9e630002-cc52-4f7c-82cc-301770316a51)
Design: https://projects.invisionapp.com/d/main#/console/15222689/341711745/preview
3. Everywhere: remove horizontal scroll from dropown box
4. Should display 'This field is required' instead of 'should be string'
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/be5917c5-eada-49c6-a6e2-24d05248bc40)
5. No text placeholder on Label field
6. All inputs should style as in our style-guide, not using material standard UI
7. The form it's broken in what we display. Ex: Select First name -> An individual first (given) name , which is the **description from JSON Schema, should be input placeholder, not input label**
8. Email validation message: should match format "email" - please use an actual email validation message, I think we had one in previous version. 
9. **Label is auto-populated from the actual value, no label I add is saved.** 

--Delete Attribute
1. Incorrect design. Should display on a popover instead of a modal
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/1e5fa065-c07a-4be1-b043-0a7ffb3b269c)
https://projects.invisionapp.com/d/main#/console/15222689/317026847/preview

--Country of Residence
1. Country selected during Create SelfKey ID workflow is not saved
2. Remove COUNTRY* label
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/1537c93f-9bb9-4e3a-ba57-2355a0727bea)
3. Country dropdown: Expected behaviour: type first letter from a country and the box should be scrolled to that area, with first alphabetical result selected. 

--Nationality
1. Error is displayed
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/20bac6cd-7dc5-4da2-9658-99ee2014455d)
2. Same comment as per country dropdown above

--Address
1. Incorrect design - all inputs should have placeholders, as provided in the design, with description of what address line 2 or 2 might mean 
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/ecf140c2-a659-4801-997a-b430b99f50ca)
https://projects.invisionapp.com/d/main#/console/15222689/341711746/preview

-- BTC Address/ ETH Address / Dash Address
1. Should display error message if value is incorrect
2. There should be a normal input, not textarea

**Comment by sk91** [comment]
WONTFIX:
- Duplicate attributes - all attributes can be duplicated
- all inputs should be styles -- need concreat inputs
- remove country label -- standard json schema rendering, hard to fix
- dropdown - focus on type -- not supported by material-ui, won't fix unless absolutely necessery for current release

**Comment by sk91** [comment]
@rodrigopavezi @oanamangiurea @rhdelima please comment on the WANTFIXES

**Comment by sk91** [comment]
<img width="848" alt="screen shot 2019-03-04 at 23 18 18" src="https://user-images.githubusercontent.com/1021965/53763612-e2774680-3ed3-11e9-90a0-18092ad9d4df.png">
