### ISSUE TITLE
Missing list style in marketplace

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#749]
Marketplace descriptions are misisng list styles (ul/ol, li)

Ex: https://gyazo.com/2bcb8095c388b204d03c7f8e011c3bee - see Belize description in the incorporations marketplace. 

Correct style should display indented list with bullets or numbers.

Reason is this line of css: `ol, ul {list-style: none}` + ad padding left + add line height, same as per paragraph. Desired outcome https://gyazo.com/92c233c4e87edf50d222c7202703456d

**Comment by andregoncalves** [comment]
@designhorf I pushed some changes, but feel free to take a look as well  `/marketplace/incorporation/details/index.jsx`

**Comment by designhorf** [comment]
@andregoncalves thanks, I will have a look at it later today
