### ISSUE TITLE
Incorporations - KYC Requirements and Forms section is no longer displaying

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#750]
It keeps displaying the loading icon.

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/3d8de835-d4ff-4a19-942d-aa122ba8eacb)

**Comment by rodrigopavezi** [comment]
@rhdelima @andregoncalves I have fixed the migration script but that previous version of the wallet could have corrupted the db so I suggest clearing wallet data before retesting this. Cheers

**Comment by rhdelima** [comment]
Failed QA. Requirement still not displaying

**Comment by andregoncalves** [comment]
@rhdelima the production data on airtable was not ready yet, which cause this.
It should be ready to be tested again.
Thanks.

**Comment by rhdelima** [comment]
Passed QA
