### ISSUE TITLE
selfkey wallet LLC sending to far horizon text should be reworded

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#781]

**Comment by andregoncalves** [comment]
where is this?

**Comment by Horizon88** [comment]
Here's the text:

By clicking this button, I consent to share my information with Far Horizon Capital Inc [company], for the purposes of [purpose] conducting KYC and that they may further share this information with partners and affiliates in accordance with their privacy policy {https://flagtheory.com/privacy-policy/} and terms and conditions {https://flagtheory.com/terms/}.


I consent to share my information with [company], for the purposes of [purpose] in accordance with their privacy policy {link} and terms and conditions {link}.

**Comment by Horizon88** [comment]
http://flagtheory.com/terms-and-conditions/ is blank now but marc will add more details there

**Comment by itsmeterrylin** [comment]
Currently displayed as attached, not sure what is final text FYI:

![screen shot 2019-03-06 at 11 50 38 am](https://user-images.githubusercontent.com/30673971/53898454-15b9f280-4006-11e9-8dd4-8b26eb56f424.png)

**Comment by rhdelima** [comment]
@andregoncalves , please add below
![image](https://user-images.githubusercontent.com/10294014/53938480-622b2e00-40eb-11e9-949d-253712a9bb5a.png)

**Comment by rhdelima** [comment]
@andregoncalves 

Please remove link on '**, and by clicking the box. hereby agree to**'.

![image](https://user-images.githubusercontent.com/10294014/54008587-2ef7a600-41a2-11e9-8866-f456e3410780.png)

**Comment by rhdelima** [comment]
Looks good.

![image](https://user-images.githubusercontent.com/10294014/54025973-39806280-41d7-11e9-9e72-8da30a2197bb.png)
