### ISSUE TITLE
SelfKey ID - Add Documents issues

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#789]
Add Documents
- Remove horizontal scroll
- Drop down is too short.
- Remove External Document in the drop down
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/e2a5f242-1948-4522-9ac9-32b24adb7587)

- Incorrect modal label. Should be Add Documents
- Incorrect field label. Should be Document Type
- Label - Missing text placeholder
- Disable Save button if not all required fields are populated or add validation
- Remove Multiples Images

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/9b09675d-1afc-44a2-90fb-65e285aa85fe)

--Bank Statement
- Incorrect error message.
- Should not display error message after upload
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/95bc22c0-eb36-449e-8707-e4bff79c12a8)
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/92254e61-3aad-4ed7-baa8-87bdf8710de8)

--Driver's License
- Should be Driver's License
- Expiry date should NOT be required
- Expiry date value not shown on SK ID Wallet dashboard

--Fingerprint
- Remove Multiples Images

--Voice ID
- Unable to save document. Won't accept pdf, image as well
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/35552abe-2a14-4e72-82aa-3fb31680a391)

--Registration Certificate
- Incorrect spelling COMPNAY NAME*
- After uploading file, should not display error message
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/e4673798-c2fc-41f8-8a4a-f3074e9f235f)

--Utility Bill
- Incorrect error message.
- Should not display error message after upload

--Certificates of Incoporation
- Incorrect error message.
- Should not display error message after upload
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/2f6ad8c0-1751-4c3f-8392-81814d78f113)
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/8aaa16b6-dd42-4fa1-8c98-dfe77500320d)

--Birth Certificate
- Error is displayed
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/a945febf-2fde-4610-b2d5-0b738cb7bbae)

-- Member Register
- Member Register or Member Registry?
- Remove Multiple Images

**Comment by oanamangiurea** [comment]
@sk91 if you are working on these issues, not sure what happened but in the latest buodl the required fields are marked like https://gyazo.com/3fcc983235826d8d91b76ddf0f33365a (with required word in parentheses. I shouldn't be displayed like that, but with an asterisk sign, like before

**Comment by sk91** [comment]
@oanamangiurea Oh... I made it on purpose, will change
In the design it was without asterisk, but optional fiels would be marked as optional instead.
It was hard to change the logic for marking required instead of optional, so I made it like this to much the design as closely as I could

Will change

**Comment by rodrigopavezi** [comment]
@oanamangiurea @sk91 added an issue for this change https://github.com/SelfKeyFoundation/Identity-Wallet/issues/853. cheers

**Comment by rhdelima** [comment]
@sk91 ,

Are we not updating 'is a required property' to 'This field is required'?

![image](https://user-images.githubusercontent.com/10294014/54037852-14e9b200-41fa-11e9-99aa-b77b07c88d57.png)


![image](https://user-images.githubusercontent.com/10294014/54039095-03ee7000-41fd-11e9-8909-affe78a8bb99.png)

![image](https://user-images.githubusercontent.com/10294014/54039107-0f419b80-41fd-11e9-98f8-212514c06003.png)

**Comment by sk91** [comment]
@rhdelima fixed in #915
