### ISSUE TITLE
Incorporations - Update wordings on some screens

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#792]
- Update button label from 'Start Incorporation' to 'Incorporate Now'. Add icon too per design  https://projects.invisionapp.com/d/#/console/15222689/319762012/preview

![image](https://user-images.githubusercontent.com/10294014/53736044-9d4b1880-3ec3-11e9-82f5-a1925774c45c.png)

- Should be 'through' ?
- Update Get final documents wordings. See design here https://projects.invisionapp.com/d/main#/console/15222689/345775295/preview

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/83becc1f-8d62-4798-836e-359ffa869880)

- Should be 'begin' ?
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/932dbf78-0d10-4a3c-806c-4d216e853b28)

- Since marketplace applications tab is not available, maybe we can hide the statement 'The application is available to you at any point under the marketplace applications tab, in your SelfKey ID Profile'

- Update email from 'support@flagtheory.com' to 'support@incorporations.io'?

- Missing Header 'Incorporation Process Started'. Design: https://projects.invisionapp.com/d/main#/console/15222689/348710320/preview
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/56434f22-00d8-4c45-bc2f-e6fd8316dd71)

**Comment by andregoncalves** [comment]
regarding email, the correct one is support@flagtheory.com

**Comment by rhdelima** [comment]
Failed QA.
1. Should be 'begin'. See screenshot
2. Remove second statement of consent
3. Add 'privacy policy' and 'terms and conditions' links

![image](https://user-images.githubusercontent.com/10294014/53796062-464e4d80-3f6e-11e9-968d-d1390cd2dec9.png)

**Comment by rodrigopavezi** [comment]
@rhdelima can you retest this one as the changes came after you set it to fail. Cheers

**Comment by itsmeterrylin** [comment]
Being -> Being: Changed and working on MAC.

![screen shot 2019-03-06 at 11 20 07 am](https://user-images.githubusercontent.com/30673971/53896368-e0130a80-4001-11e9-8feb-81292d427285.png)

Links to Privacy Policy & Terms and Conditions displaying correctly on MAC:

![screen shot 2019-03-06 at 11 21 14 am](https://user-images.githubusercontent.com/30673971/53896404-f8832500-4001-11e9-994f-e4bbada7ff28.png)

Hide 2nd Statement of Consent: Displaying correctly on MAC

![screen shot 2019-03-06 at 11 21 33 am](https://user-images.githubusercontent.com/30673971/53896461-13ee3000-4002-11e9-9d96-28e4dd70812d.png)

**Comment by rhdelima** [comment]
Looks good on WIN too.

As for Terms and Conditions, please see comment from Edmund - https://github.com/SelfKeyFoundation/Identity-Wallet/issues/781#issuecomment-468901524
