### ISSUE TITLE
Authentication error using Keystore file & Existing address

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#800]
When using a keystore file or an existing address If I input the wrong password no error message is shown. https://gyazo.com/e46cf6d723427e9bfc3ffb8d037d30a3 

But I do get quite a few messages in console.

**Comment by rhdelima** [comment]
Passed QA.

![image](https://user-images.githubusercontent.com/10294014/53797782-dc37a780-3f71-11e9-8ba2-859deb8210b4.png)

![image](https://user-images.githubusercontent.com/10294014/53797819-f3769500-3f71-11e9-89fa-b3841e50b149.png)
