### ISSUE TITLE
Table layout break on too much text

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#803]
The profile tables will break layout if the text on the label is too long. This also creates the issue of not being able to delete the record or edit, as the buttons are pushed out of the screen 

https://gyazo.com/4a27d2fe7cd81369575ad556b94d5a98

**Fix**: set white-space to normal

**Comment by rhdelima** [comment]
Failed QA. Fix the issue to documents on SelfKey ID dashboard

![image](https://user-images.githubusercontent.com/10294014/53799456-5d446e00-3f75-11e9-9fb0-686c490ebcd5.png)

**Comment by CortecKYC** [comment]
@rhdelima @rodrigopavezi Is this QA-Ready or not?

**Comment by itsmeterrylin** [comment]
Table layout no longer breaks on MAC. @rhdelima please confirm on Windows too, thanks!

![screen shot 2019-03-06 at 11 14 44 am](https://user-images.githubusercontent.com/30673971/53895964-2025bd80-4001-11e9-8447-5dbae824f5b3.png)

**Comment by rhdelima** [comment]
Looks good on WIN too.

![image](https://user-images.githubusercontent.com/10294014/53931118-d3101d00-40ce-11e9-8382-e957d73af605.png)
