### ISSUE TITLE
Wallet impossible to use on smaller vertical resolutions resolutions

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#804]
1. Can't unlock wallet using keystore file on smaller resolutions like (1366x768 - which is our 2nd used resolution by our users) - because there's no scroll, and the button is pushed put of the window https://gyazo.com/1452cd8daa366180a7a4b7082ab19b1b

Same for using Ledger

Fix: Make it scrollable in the unlock wallet/use existing wallet screens

2. Dashboard doesn't look good, layout breaks https://gyazo.com/14b2abceff544809d1f2dc312959105e

3. About Selfkey ID modal (after you create a profile id for the first time) - make it scrollable

4. Menu breaks into 2 parts and has horizontal scroll - https://gyazo.com/f285df6447e514a5dd66c4cc4413f1dc

**Comment by rodrigopavezi** [comment]
I have added scroll to modal screen with this https://github.com/SelfKeyFoundation/Identity-Wallet/blob/dev/src/renderer/selfkey-id/main/components/selfkey-id-create-form.jsx#L58

So we might be able to add it to the Selfkey-ui theme MuiModal so all the modals in the wallet will scroll. Cheers

**Comment by rodrigopavezi** [comment]
@designhorf would you mind taking this one? cheers

**Comment by designhorf** [comment]
@rodrigopavezi sure!

**Comment by designhorf** [comment]
@oanamangiurea How can I test it on macbook pro with 1366x768 resolution? 
Opened dev tool and set this resolution but couldn't reproduce the menu breaking.

**Comment by oanamangiurea** [comment]
@designhorf for the menu alone, you don't even need to change resolution. Just open the dev tools, so the window of the wallet becomes small in height, the menu will break then anyway - here is how it looks if I don't go full screen with the app https://gyazo.com/9de66c9a3ffaed855b540e1c324b8588

**Comment by rodrigopavezi** [comment]
Menu Issue will be fixed later

**Comment by designhorf** [comment]
Menu issue is fixed here -> https://github.com/SelfKeyFoundation/Identity-Wallet/pull/878

**Comment by oanamangiurea** [comment]
Tested, all good
