### ISSUE TITLE
Improvements to incorporations table UI

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#805]
- [ ] Make Flag smaller - 28px width
- [ ] In order to increase understanding of information available in columns, remove ` table-layout: fixed;` from `<table>` styling 
- [ ] In the Cost column, all the prices should show the denomination, in incorporations case that is USD. 0.25 doesn't make sense without saying what fiat that is

**Comment by rhdelima** [comment]
Failed QA. Some tags under Good For column are not displaying properly. 


![image](https://user-images.githubusercontent.com/10294014/53851176-c3bea000-3ff8-11e9-9836-e65c5d3ec252.png)

**Comment by itsmeterrylin** [comment]
Tags under "Good For" column are now displaying correctly on MAC.

![screen shot 2019-03-06 at 10 59 12 am](https://user-images.githubusercontent.com/30673971/53894886-e5bb2100-3ffe-11e9-8504-34d7c0ab9552.png)

**Comment by rhdelima** [comment]
Looks good on WIN too

![image](https://user-images.githubusercontent.com/10294014/53933352-f3dd7000-40d8-11e9-93fa-a1561a5f4d93.png)
