### ISSUE TITLE
Incorporations checklist modal layout break

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#806]
On long text in the label field, the checklist modal layout breaks https://gyazo.com/8416a1cb7d165a3aa21090f768b2312c 

Fix: remove `white-space: nowrap` from .MuiTableCell classes

**Comment by rhdelima** [comment]
Failed QA. Fix the issue to documents and attributes on SelfKey ID dashboard

![image](https://user-images.githubusercontent.com/10294014/53799093-a0521180-3f74-11e9-96c2-dc5c6c30632b.png)

**Comment by rhdelima** [comment]
Issue still exists.

**Comment by rodrigopavezi** [comment]
@rhdelima can you check it on this build https://console.cloud.google.com/storage/browser/selfkey-builds/dev/2019.03.06.01/?project=kycchain-master? cheers

**Comment by rodrigopavezi** [comment]
![image pasted at 2019-3-6 18-25](https://user-images.githubusercontent.com/1659305/53877903-290a9500-3fe9-11e9-837b-11eac5c524e7.png)

**Comment by itsmeterrylin** [comment]
Modal no longer breaks on MAC. @rhdelima please confirm Windows?

![screen shot 2019-03-06 at 11 03 57 am](https://user-images.githubusercontent.com/30673971/53895239-90cbda80-3fff-11e9-92b9-459923e8180f.png)

**Comment by rhdelima** [comment]
Looks good on WIN too.

![image](https://user-images.githubusercontent.com/10294014/53935035-e7a8e100-40df-11e9-89d3-5e37549b5dff.png)
