### ISSUE TITLE
Incorporations - 'You have an existing unpaid application' is displayed even if checklist is not submitted yet (TREZOR)

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#816]
Steps to replicate:
1. Unlock wallet via Trezor
2. Go to Menu > Incorporations
3. Select an incorporation
4. Start Incorporation
5. On the checklist screen, close the modal or click Cancel

Expected Result:
User is redirected back to incorporation page with no warning message

Actual Result:
'You have an existing unpaid application' is displayed

Recording: http://recordit.co/UtvsDy4BdR

**Comment by rodrigopavezi** [comment]
It is not only trezor. I saw it with private key and existing wallets.
