### ISSUE TITLE
Get version from electron main process for showing on the sidebar menu. Now it is hardcoded to 0.2.0

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#827]

**Comment by itsmeterrylin** [comment]
Don’t see “hardcoded to 0.2.0” as written in issue, but displays “V 0.3.0-beta” as screen-shotted

![screen shot 2019-03-06 at 11 53 30 am](https://user-images.githubusercontent.com/30673971/53898716-9e389300-4006-11e9-8777-6f24cd358233.png)

**Comment by rhdelima** [comment]
@rodrigopavezi Should version be V 0.4.0-beta?

**Comment by rodrigopavezi** [comment]
@rhdelima that is the right version for now. It will be changed to 0.4.0. Cheers
