### ISSUE TITLE
Incorporations - Transaction automatically failed after paying (TREZOR)

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#829]
http://recordit.co/Q1jsYqdPpN

**Comment by rodrigopavezi** [comment]
@rhdelima could you provide the logs? Not the dev_tools one. That from the application menu. Cheers

**Comment by rhdelima** [comment]
@rodrigopavezi The issue is also encountered on sending keys and eth. See log attached 
[log.log](https://github.com/SelfKeyFoundation/Identity-Wallet/files/2933944/log.log)

**Comment by rhdelima** [comment]
@rodrigopavezi We can close this one now. Looks good on the new build

**Comment by rodrigopavezi** [comment]
This should be a duplication of this https://github.com/SelfKeyFoundation/Identity-Wallet/issues/835

**Comment by rhdelima** [comment]
@rodrigopavezi Failing this one. Should display not enough gas modal instead of failing it automatically.

**Comment by rhdelima** [comment]
@oanamangiurea @rodrigopavezi 
Can we display this screen if wallet does not have enough gas? https://projects.invisionapp.com/d/main#/console/15222689/318457086/preview

We also need a screen for not having enough KEYS to pay for incorporation application.

**Comment by oanamangiurea** [comment]
@rhdelima @rodrigopavezi yes, that is what should be displayed if not enough gas. And similar for not enough KEY, with following text:

**You don't have enough KEY tokens to pay for the incorporation. Please transfer some KEY to this address and try again. Your KEY address of this wallet is listed below.**

**Comment by rodrigopavezi** [comment]
@rhdelima added the screen for not enough key but could not replicate the issue with the not enough gas screen. Cheers

**Comment by rhdelima** [comment]
@rodrigopavezi 
- Not enough KEY modal is working
- Not enough gas still doesn't work on my end. 

http://recordit.co/P2jG6zlezM

Can we discuss this on a call?

**Comment by rodrigopavezi** [comment]
@rhdelima I need the logs here can you run the wallet on console and send me a print of the error. It should say something regarding gas. Cheers

**Comment by andregoncalves** [comment]
@rodrigopavezi is this logged to sentry?

**Comment by rodrigopavezi** [comment]
@andregoncalves it wasn't because it was using console.error instead of our log.error. I am fixing it now. cheers
