### ISSUE TITLE
Incorporations - Editing a requirement shows a blank screen

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#831]
http://recordit.co/jX1bNyWjfj

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/8ba0de8f-ca36-4d08-baaf-4f0d3ca14591)

**Comment by rodrigopavezi** [comment]
@rhdelima have you tried with this build https://console.cloud.google.com/storage/browser/selfkey-builds/dev/2019.03.06.01/?project=kycchain-master? Cheers

**Comment by rodrigopavezi** [comment]
@rhdelima I can replicate it anymore. could you create a video with the steps?

**Comment by rhdelima** [comment]
Looks good now..closing this one.
