### ISSUE TITLE
It should clear Relying party session after a payment or application failure

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#836]

**Comment by andregoncalves** [comment]
After payment to refetch the applications array?

**Comment by eduardosmoura** [comment]
@andregoncalves, as @rodrigopavezi mentioned we need to check for an existing application, and he suggested to do a check right after the user clicks on the "Incorporate Now" button. Do you think that's the right thing to do?

**Comment by rodrigopavezi** [comment]
@andregoncalves I think it is better to check every time as @eduardosmoura described above because there are a couple of things that can happen after the creation of the application that would require we show that the application has been already created.
