### ISSUE TITLE
Document layout break on long text

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#840]
https://gyazo.com/9eb0d0213d6c2b40e089d89d049d26a1

1. Long text as label and the table itself gets pushed outside container
    *Fix:* `word-break: break-all;` added to h6 from any table cell
2. Big spacing between file icon and the label itself appear
    *Fix:* problem here is the layout itself, the icon should not be part of a grid. Icon should be in same div as the <h6> with following css:
```
    float: left;
    margin-right: 15px;

```

**Comment by itsmeterrylin** [comment]
Looks like spacing is fixed and table is no longer pushed out on MAC. 

Also similarly related to: https://github.com/SelfKeyFoundation/Identity-Wallet/issues/803

![screen shot 2019-03-06 at 11 44 59 am](https://user-images.githubusercontent.com/30673971/53898080-6c72fc80-4005-11e9-9cf8-0e5d2a45a311.png)

**Comment by rhdelima** [comment]
Looks good on WIN too.

![image](https://user-images.githubusercontent.com/10294014/53932648-9136a500-40d5-11e9-9861-5a8d9af47687.png)
