### ISSUE TITLE
Fix inputs display

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#841]
Some label inputs aren't displayed with our own styling but with material UI one. 

**Wrong style**: https://gyazo.com/c3424b61bf7fbcb9212edc0a75e51061

**Correct style**: https://gyazo.com/47fecc68e9bfddf5a03d4c209cfef29a - Also, please make sure they contain the text placeholder, as in the design: _Internal naming for the information you are adding_

---

**List of Label inputs and fixes for them**

### Add Information modal:

1. First Name:  Label input missing placeholder | Given Name  input missing label
2. Last Name: Label input missing placeholder | Family Name input missing label
3. Middle Name: Label input missing placeholder | Middle Name input missing label
4. Country of Residency: Label input missing placeholder | Country dropdown required should be asterisk not text | Country dropdown _Please specify the country.._ text should be placeholder on the input
5. Email: Label input missing placeholder | Email input missing label
6. Public Key: Label input missing placeholder | Key input missing label, placeholder and it should be input not textarea
7. Address: Label input missing placeholder
8. Tax ID: Label input missing placeholder | Tax input missing label
9. Nationality: Label input missing placeholder | Country dropdown required should be asterisk not text | Country dropdown _Please specify your current.._ text should be placeholder on the input
10. Phone Number: Label input missing placeholder | Phone input missing label
11. Date of Birth: Label input missing placeholder | date input missing label
12. Workplace: Label input missing placeholder | Workplace input missing label

### Edit Information modal:

Same as above + All modals in edit mode - Label input has incorrect style (see above screenshots)

**Comment by sk91** [comment]
Oana, most of thous are fixed in
https://github.com/SelfKeyFoundation/Identity-Wallet/pull/798
hope to merge soon

ср, 6 мар. 2019 г. в 15:06, Oana Mangiurea <notifications@github.com>:

**Comment by rodrigopavezi** [comment]
@sk91 can you list here what is not included on fix for #798? cheers

**Comment by sk91** [comment]
after going trough all of them, all should be included @rodrigopavezi

**Comment by rodrigopavezi** [comment]
Closing based on above
