### ISSUE TITLE
Edit/Add Information/Documents Modals style

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#842]
To fix:

1. Separator `<hr>` is shorter than the inputs, and it's missing vertcial spacing. Fix: `margin: 30px 0;`

2. Buttons need more vertical spacing. Fix: change their container margin from -12px to `margin: 40px -12px 0;`

3. Modal titles are inconsistent in use of upper/lowercase letters. Fix: use `text-transform: capitalize;`

4. All input labels are too close to the actual inputs. They need more vertical spacing. Fix: change margin-bottom from 0.35em to `margin-bottom: 10px`

**Comment by rhdelima** [comment]
@oanamangiurea , 1-3 fixed, 4 - NOT. Please confirm if we can close this and log a separate ticket for 4?

**Comment by oanamangiurea** [comment]
@rhdelima  confirmed we can close this one, and open a different ticket for 4. Thank you!
