### ISSUE TITLE
Incorporations detailed view UI fixes

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#845]
Incorporations detailed view (pick any country from the list)

1. The flag in detailed view should be 44px width. When chancging this, please make sure you don't affect the table listing, there the size is correct
2. Pricing area: 
    - Missing text *Pricing:* correct is Pricing: USD 0.25
    - Font size is too big. Correct is 16px for the USD price 
3. Text area from tabs - text should be 100% width, if we don't use inline scroll  
4. KYC Requirements area - list font should be bold (weight: 600)

**Comment by andregoncalves** [comment]
@oanamangiurea the flag is already at 44px, can you please confirm?

**Comment by oanamangiurea** [comment]
@andregoncalves confirmed for latest build
