### ISSUE TITLE
Exchanges marketplace not loading

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#846]
Exchanges marketplace listing is not working anymore, only the title is loading. Not sure if it's related, but the network console shows failed to load service-worker.js

https://gyazo.com/db35279c4b15d710728c9ff6c91acd4e

**Comment by rodrigopavezi** [comment]
@oanamangiurea still see the issue so we need to try to replicate and fix it. cheers

**Comment by sk91** [comment]
@oanamangiurea @rodrigopavezi, any pointers on how to replicate? works for me both for dist and dev

**Comment by sk91** [comment]
Cannot reproduce, closing.

Will implement better exchanges loading as part of https://github.com/SelfKeyFoundation/Identity-Wallet/issues/571
