### ISSUE TITLE
Incorporations Checklist modal UI issues

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#849]
Vertical table spacing is too bi, when I have more than one attribute of the same type. Fix: the Div `MuiFormGroup-root- Component-radioGroup` should have padding-top: 10px and margin-bottom: 0;

**Comment by rhdelima** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/10294014/54010065-3b7efd00-41a8-11e9-8689-1bb0073df0c9.png)
