### ISSUE TITLE
Error when saving Voice ID - can't incorporate

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#850]
Steps to reproduce: 

1. Trying to go trough incorporations in Belize
2. I'm adding all required information. Including Voice ID
3. For Voice ID I added a label but with no file, as file was not required
4. I get an empty screen, no way to get out of it, because the following error (console) https://gyazo.com/ed6f529352a4070fc3a31f5cf07168a8 

LE: Same happens if I try to add it from SelfKey ID - add documents area

And if i try to upload a file like an .mp4 or any other extension then the save button is disabled

**Comment by sk91** [comment]
<img width="865" alt="screen shot 2019-03-06 at 21 19 47" src="https://user-images.githubusercontent.com/1021965/53908520-2eeb8f00-4058-11e9-875e-672639be8714.png">
<img width="896" alt="screen shot 2019-03-06 at 21 42 25" src="https://user-images.githubusercontent.com/1021965/53908783-cd77f000-4058-11e9-95bc-7b121d0dc095.png">

<img width="934" alt="screen shot 2019-03-06 at 21 20 21" src="https://user-images.githubusercontent.com/1021965/53908513-298e4480-4058-11e9-88d8-92981c5fad0e.png">

**Comment by rhdelima** [comment]
@sk91 
Failed QA. See issues below:
1. Update 'Alowed' to 'Allowed'
2. Update [object Object] with actual value
![image](https://user-images.githubusercontent.com/10294014/53931933-3d768c80-40d2-11e9-8be2-c2351a585241.png)

3. When editing Voice ID and uploaded a big file, the error also displayed on the first uploaded file
![image](https://user-images.githubusercontent.com/10294014/53932137-3dc35780-40d3-11e9-9c05-7911bdd6b2a1.png)

Recording:
http://recordit.co/MYTwEN4zEA

**Comment by oanamangiurea** [comment]
Also please change the message on the allowed types, to the following, which is more non-technical people friendly:

**Allowed audio file extensions:  .mp3, .mp4, .ogg, .x-wav**

And the error message for it: 

**Incorrect file extension. Allowed audio: .mp3, .mp4, .ogg, .x-wav**

**Comment by sk91** [comment]
"Allowed audio" is too specific, this code cannot distinguish between image
an audio

чт, 7 мар. 2019 г. в 10:42, Oana Mangiurea <notifications@github.com>:

**Comment by oanamangiurea** [comment]
@sk91 our messages are addressed to regular people, who are not that technical, they will understand what an audio file is but not what mime is. How about:

Allowed file extensions: audio .mp3, audio .mp4, audio .ogg, audio .x-wav

**Comment by sk91** [comment]
That's better, can do that :+1:

чт, 7 мар. 2019 г. в 11:44, Oana Mangiurea <notifications@github.com>:
