### ISSUE TITLE
Add documents modal issues

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#851]
1.  The order of the inputs makes no sense. Let's take for example National ID. We are asking for back image, then expiry date then extra images, front images, etc ...
*Correct order: *
     1.  Front Image
     2. Back Image
     3. Selfie
     4. Get rid of extra images (we agreed on this 2 days ago)
     5.  Expiry Date
     6. Issue Date

2. When I upload a file, there should not be any underline for it's name. Fix: text-decoration: none; on that link

3. If the file name is too long the layout breaks. https://gyazo.com/2a3d09c74666bb101529bb95ff56e09f  Fix: use `word-break: break-all;` Also try to fix the file icon and delete button be on the same line with the file name, even when the text is too long

4. As soon as I upload a file, I get validation message on Issue Date, even if I didn't get the chance to write anything in it yet. It's annoying, and even so, the validation is not complete, as correct from UI would be the input to be red as well. https://gyazo.com/0059d15a4ae5bdcf7bc1084432c994a0

**Comment by designhorf** [comment]
2. fixed in this PR https://github.com/SelfKeyFoundation/Identity-Wallet/pull/862

**Comment by rhdelima** [comment]
@oanamangiurea , Everything is fix except for the order of fields. Should we reopen this one? or we pass it for now and log a minor ticket for the next sprint?

![image](https://user-images.githubusercontent.com/10294014/54119422-4055e200-4430-11e9-9f91-3a7b553cfd48.png)

**Comment by oanamangiurea** [comment]
@rhdelima let's pass it for now and open a different ticket for next sprint. Thank you!

**Comment by sk91** [comment]
@oanamangiurea @rhdelima 
its an easy fix, does not require code change, lets add to sprint backlog
