### ISSUE TITLE
create selfkey id on incorporations

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#861]
we need design for a new screen.
When user clicks on start incorporation but did not create sekfkey-id, he will be shown a popup saying something along the lines:
"Before starting incorporation process, please create your selfkey id"
With a button that will redirect to selfkey-id creation

we also want to add 'email' as required field on selfkey-id creation

related to https://github.com/SelfKeyFoundation/Identity-Wallet/issues/826

**Comment by oanamangiurea** [comment]
Modal: https://projects.invisionapp.com/d/main#/console/15222689/350829741/preview

And ID Registration also updated https://projects.invisionapp.com/d/main#/console/15222689/316491814/preview
