### ISSUE TITLE
File Upload Widget and Datepicker style

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#864]
Need to change background colors and border style of File Upload Widget

From:
<img width="743" alt="screenshot 2019-03-07 at 09 56 44" src="https://user-images.githubusercontent.com/7461010/53944479-c2a47600-40bf-11e9-8ade-196d97a0ef4b.png">

To:
<img width="1376" alt="screenshot 2019-03-07 at 09 35 24" src="https://user-images.githubusercontent.com/7461010/53944485-c801c080-40bf-11e9-8e24-5d6954cd7cf8.png">

**Comment by itsmeterrylin** [comment]
Border for file upload widget looks good on MAC. @rhdelima please confirm on WIN.

![screen shot 2019-03-07 at 8 31 58 am](https://user-images.githubusercontent.com/30673971/53960146-7d7a4700-40b3-11e9-85b8-864cf50bb32c.png)

**Comment by rhdelima** [comment]
Looks good on WIN as well

![image](https://user-images.githubusercontent.com/10294014/54009393-9531f800-41a5-11e9-9859-8a5b17d13a72.png)
