### ISSUE TITLE
Incorrect Edit Information modal

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#883]
Edit Information:
Actual:
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/db205789-dbc1-4a07-bd56-4e37a9776801)

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/d1c0fe4e-7c33-448e-ac14-582803e3211d)

Expected:
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/1a21e714-c32f-4080-bef6-264f6b11311c)

Edit Documents:
- Document Type should be visible but disabled.
![image](https://user-images.githubusercontent.com/10294014/54019585-827beb00-41c6-11e9-94fb-3650053bd9c6.png)

**Comment by sk91** [comment]
Label fixed in https://github.com/SelfKeyFoundation/Identity-Wallet/pull/887/

Placeholder is not seen because the value of the label is 'First Name'

so only document type in edit screen should be relevant for this issue
