### ISSUE TITLE
Create a file preview modal

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#884]
Issue: If I click on the name of a file I have uploaded in my SelfKey ID (from edit mode https://gyazo.com/ab70174ce7650eed0eda6d2b5209bb18), the file will open from my computer in a new window (https://gyazo.com/0c01e754d8c22adfa3048bdeae95c763). There is no way of going back to the app, or closing that without closing the wallet app.

**Suggestion:** open the file in either a modal or new page with back button, which ever is simpler.

**Comment by designhorf** [comment]
fixed this issue in #896
