### ISSUE TITLE
External document gets saved for multiple attributes

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#885]
Steps to reproduce

1. Try to incorporate, on incorporations checklist edit the CV/Resume
2. Give it a label and save it
3. Now the Professional Reference Letter has been auto saved with the same information https://gyazo.com/94e6b917c42ace9d17b95e2cfc4eb1ae

When I started I didn't have any of these documents uploaded yet, I did it from the incorporations checklist

**Comment by sk91** [comment]
Both of thous are external attributes with different title.

So when you save a document it get's suggested to both. That is expected.

If you add another one, you will have a choice for both of them, and you
could choose a different one  for each

@oana@kyc-chain.com <oana@kyc-chain.com>

пт, 8 мар. 2019 г. в 11:37, Oana Mangiurea <notifications@github.com>:

**Comment by oanamangiurea** [comment]
@sk91 just added another. I can't choose a different one to each. They both see it just as multiple document upload, with same Label name. - https://gyazo.com/551beec00b25dbe474d990e2f50a00a9

**Comment by sk91** [comment]
Not another document inside the same attribute, but another external document attribute @oanamangiurea

**Comment by sk91** [comment]
ok, so what we need to do here is add a "create attribute" button in kyc checklist, edit only will not do it

**Comment by sk91** [comment]
short term fix: add 2 new attribute types cv and reference latter
long term solution tracked here: https://github.com/SelfKeyFoundation/Identity-Wallet/issues/951

**Comment by sk91** [comment]
blocked by kyc instances update

**Comment by sk91** [comment]
this is now fixed on dev
<img width="953" alt="Screen Shot 2019-03-13 at 19 41 11" src="https://user-images.githubusercontent.com/1021965/54302147-ff450580-45c8-11e9-9e6d-efb74c58857c.png">

<img width="963" alt="Screen Shot 2019-03-13 at 19 41 35" src="https://user-images.githubusercontent.com/1021965/54302145-feac6f00-45c8-11e9-9762-803b900ff8fe.png">
<img width="999" alt="Screen Shot 2019-03-13 at 19 42 08" src="https://user-images.githubusercontent.com/1021965/54302146-feac6f00-45c8-11e9-89d2-f9578af9c61f.png">


@andregoncalves you need to update templates on production kyc

**Comment by andregoncalves** [comment]
Templates updated.
