### ISSUE TITLE
Loop in creating SelfKey ID

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#894]
Steps to replicate:
1. Open and unlock wallet
2. Go to Menu > SelfKey ID > Create SelfKey ID
3. Populate all fields using details below:
    SK ID Nickname: SK0001
    First Name: Peter
    Last Name: Parker
    Email: rhdelima@gmail.com
4. Click Create SelfKey ID
5. Click Continue
6. Click Continue

Expected Result:
SelfKey ID dashboard is shown

Actual Result:
Setup your SelfKey Identity screen is displayed

Recording: 
http://recordit.co/2PaNFQKZqn

**Comment by sk91** [comment]
@rhdelima cannot reproduce, please check again with latest build
