### ISSUE TITLE
Create Selfkey ID - hidden button

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#895]
Create Selfkey ID - action button is hidden. 
- If you focus any of input fields, the button appears and suddenly hide.
- If you start typing, button keeps visible.

http://recordit.co/z7obVM8Do3

**Comment by rhdelima** [comment]
Please also fix the following Add Document screens:

Birth Certificate
![image](https://user-images.githubusercontent.com/10294014/54077366-2f9f5200-42f2-11e9-9302-0fe5bed9adb9.png)

Member Register
![image](https://user-images.githubusercontent.com/10294014/54077384-6b3a1c00-42f2-11e9-8195-942c07fe7f58.png)

National ID
![image](https://user-images.githubusercontent.com/10294014/54077395-8573fa00-42f2-11e9-970b-859d1a576111.png)

Utility Bill
![image](https://user-images.githubusercontent.com/10294014/54077405-a76d7c80-42f2-11e9-8cd8-ce625dc8c49d.png)

**Comment by eduardosmoura** [comment]
@designhorf and @rhdelima I tried to reproduce all errors, but I couldn't find any issue. I think those issues were related to Electron version upgrade which is reverted by now. 

Please check my tests evidence:

Create Selfkey ID: http://recordit.co/sLymPjRhfj

Birth Certificate: http://recordit.co/NVahrXbUL1

Member Register: http://recordit.co/B4UDNr3FWe

National ID: http://recordit.co/MJaWUxFUwB

Utility Bill: http://recordit.co/MkKD2xpBfx

**Comment by designhorf** [comment]
@eduardosmoura I also think it was related to upgraded Electron version. I already tested as well and didn't reproduce the issue.

**Comment by rodrigopavezi** [comment]
Not happening anymore after electron downgrade
