### ISSUE TITLE
images in upload edit attribute are opened in place

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#896]
when clicking on an image link, the image will open to full view without the ability to return

**Comment by oanamangiurea** [comment]
Also reported here: https://github.com/SelfKeyFoundation/Identity-Wallet/issues/884

**Comment by rhdelima** [comment]
Failed QA. 

- For pdf, has to save it first before user can view it. http://recordit.co/cJo1UCRUFz
- For image, still opened on the wallet. http://recordit.co/ef3VVaq9vq

Expected: 
Should open on machine's default viewer. See recording as example: http://recordit.co/2WXiuYcWBA

**Comment by designhorf** [comment]
@rhdelima Couldn't reproduce image issue. Tried jpeg, jpg and png formats as well and all of them worked well, opened in a modal with Back button.

**Comment by oanamangiurea** [comment]
@rhdelima @designhorf maybe you can both point the build version you are testing?

**Comment by sk91** [comment]
- pdf issue will be tracked separately https://github.com/SelfKeyFoundation/Identity-Wallet/issues/953

- image issue cannot reproduce, please @rhdelima  check out on newer build

**Comment by oanamangiurea** [comment]
Image issue is fixed
