### ISSUE TITLE
Unlocking via Trezor not working

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#897]
**With Passphrase Enabled:**
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/a774f41f-cf46-40f9-8708-20783df67410)

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/d7278cf2-cf40-4232-a498-4a4e31344e82)

With No Passphrase:
![image](https://user-images.githubusercontent.com/10294014/54082361-6e172a00-434f-11e9-95a3-78bd3e6ee6ff.png)

**Comment by rodrigopavezi** [comment]
@rhdelima is this happening after we downgraded electron?
