### ISSUE TITLE
Input style issue

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#898]
https://gyazo.com/2afd6f312810bb0681b1ac3aac35adf9 

All inputs should have a different style as I have information in them (when they are filled) -> the text should be white. 
Updated the UI to show how it looks - see filled style https://projects.invisionapp.com/d/main#/console/15222689/317955444/preview 
The text is gray only for placeholders.

**Comment by rhdelima** [comment]
![image](https://user-images.githubusercontent.com/10294014/54325543-ceeb7e80-463d-11e9-90c5-9b9116cc2d70.png)
