### ISSUE TITLE
Add information modals fixes

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#899]
Tested on build from 9 March, on Mac, without dev tools open. 

When adding the following information under selfkey ID. 

1. Birth Certificate is asking for Selfie. It shouldn't
2. In ID Selfie: Wrong description - use the one from suggested column here https://confluence.kyc-chain.com/display/SEL/JSON+Schema+Descriprions+-+WIP  
3. In Edit Mode **I’m missing the delete button icon,  and the upload button**, the links are there, only the icon/button is missing https://gyazo.com/2807252cb71620b4c7b74c6d4618e48d  - same rendering issue that we have with the modal buttons. Everything is delayed 
4. **Modal Buttons (save, cancel) don’t show from the start**. They appear only as I move with the mouse over that region.

**Comment by oanamangiurea** [comment]
Buttons issue are not reproducing anymore after electron version rollback. The others still stand

**Comment by sk91** [comment]
Birth certificate - fixed.

Delete button - cannot reproduce. Tested on https://console.cloud.google.com/storage/browser/selfkey-builds/dev/2019.03.11.15/
<img width="957" alt="Screen Shot 2019-03-11 at 19 11 15" src="https://user-images.githubusercontent.com/1021965/54143002-8b242980-4431-11e9-809a-29c5100be459.png">
<img width="919" alt="Screen Shot 2019-03-11 at 19 09 46" src="https://user-images.githubusercontent.com/1021965/54143003-8b242980-4431-11e9-9bf2-7a2f70132e28.png">
