### ISSUE TITLE
Delete attribute modal issues

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#900]
1. Typo: “you cannot” should be “you can not”. 
2. Title should be: Delete Information and History

**Comment by eduardosmoura** [comment]
DEV Test Evidence: http://recordit.co/7VWT6NlSMy

**Comment by rhdelima** [comment]
Looking good.
![image](https://user-images.githubusercontent.com/10294014/54324902-98f8cb00-463a-11e9-81c9-503cff0b8a6e.png)
