### ISSUE TITLE
When adding a valid token address, wallet shows an error message first before populating the fields

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#902]
Recording: http://recordit.co/LUzdrAy8i0

Expected Result:
Should show message that wallet is searching for the token address on the ethereum.
https://projects.invisionapp.com/d/main#/console/15222689/316491958/preview

**Comment by eduardosmoura** [comment]
@rhdelima we are not using the "dots" loading anymore. Please consider the "circle" loading as the standard now: http://recordit.co/NE38UdhBAq

**Comment by rhdelima** [comment]
@eduardosmoura 
Failed QA. The message + loading icon should only displayed when address is added and be hidden after search is completed. Currently, it is always displayed even if no address is added yet or search is already completed.

http://recordit.co/81AYEHXfVI

**Comment by eduardosmoura** [comment]
Sorry @rhdelima, I forgot to update the loading control flag. I just did an update.

**Comment by rhdelima** [comment]
@eduardosmoura Failing this one again. If wallet doesn't recognise the token, it keeps displaying. Please see recording:
http://recordit.co/V7qjF39oyj
Token Address: 0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2

**Comment by rodrigopavezi** [comment]
@eduardosmoura I think you can wrap this line https://github.com/SelfKeyFoundation/Identity-Wallet/blob/release/src/common/tokens/operations.js#L14 into a try/catch and set a redux store flag when there is an error so you can retrieve it on the maps to props and show the error on the UI. Let me know if that is not clear and we can go over it on a call. Cheers

**Comment by eduardosmoura** [comment]
I will do that @rodrigopavezi. Thank you. @rhdelima I let you know when it's fixed.

**Comment by eduardosmoura** [comment]
@rhdelima It's fixed now. DEV test evidence: http://recordit.co/W0rmkkJu8X

**Comment by rhdelima** [comment]
@eduardosmoura Looks good but can we change the error message following the design?
Actual:
![image](https://user-images.githubusercontent.com/10294014/54524045-dac3a180-49ab-11e9-876c-460d51874e12.png)

Expected: https://projects.invisionapp.com/d/#/console/15222689/316491957/preview

@oanamangiurea Let me know if you agree. Also, token address below exists on ethereum but currently not supported by the wallet. So maybe we can update the error message to 'Token contract does not exist or not supported. Please double check and try again.' 

0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2

**Comment by eduardosmoura** [comment]
I will do that @rhdelima.

**Comment by oanamangiurea** [comment]
@rhdelima @eduardosmoura I agree with your message suggestion. So it should be  'Token contract does not exist or not supported. Please double check and try again.'
