### ISSUE TITLE
As a User I want to stake some key so that I can access the exchange marketplace

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#903]

**Comment by rhdelima** [comment]
Blocking this one. Sign Up button is no longer available.

**Comment by rhdelima** [comment]
Closing this one. A separate ticket is opened for issues found.

**Comment by CortecKYC** [comment]
@rhdelima Why is this ticket "Done" instead of "Closed"?
