### ISSUE TITLE
As wallet I want to track when user has unlocked the wallet

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#907]
- User ID (Hashed Public Key)

Custom Variable on the `visit` scope:

- Machine ID (Hashed Mac Address)
- Wallet type(Trezor, Ledger, Private Key, Keystore)
- Wallet version

References:
 -  https://matomo.org/docs/custom-variables/
 - https://developer.matomo.org/guides/tracking-javascript-guide#custom-variables

**Comment by rodrigopavezi** [comment]
- Set UserId as unique ID from machine which comes each installation
- Create a separated attribute for hashed public key.

**Comment by rhdelima** [comment]
Pass
