### ISSUE TITLE
As wallet I want to track when user has opened SelfKey Marketplace

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#908]

**Comment by rodrigopavezi** [comment]
- Set UserId as unique ID from machine which comes each installation
- Change and create a separated attribute for hashed public key.

**Comment by rodrigopavezi** [comment]
Added a goal on matomo to be trigger when user visits the marketplace screen

**Comment by rhdelima** [comment]
Pass
