### ISSUE TITLE
As wallet I want to track when user completes SelfKey ID Setup

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#909]

**Comment by Chaviland7** [comment]
@rodrigopavezi I created a goal for this on Matomo and set the app to track the goal accordingly. If you wanted to track these events differently let me know, otherwise I'll write a test and continue this way with other Matomo tickets!

**Comment by rhdelima** [comment]
Failed QA. After completed the SelfKey ID setup, 'Marketplace Visited' goal is triggered.

http://recordit.co/L8UTIUefFk

**Comment by rodrigopavezi** [comment]
@rhdelima That was due to a missing goal setup on the QA website. No code required. Please review again. Cheers
