### ISSUE TITLE
Horizontal menu scroll on full screen

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#918]
Even if I have my wallet in full screen mode (Full HD, retina), I still get a horizontal scroll inside the menu
https://gyazo.com/ce62fac2cfd021cb755edc5b164dd10b

**Comment by eduardosmoura** [comment]
DEV test evidence: http://recordit.co/GvoVWkDaze

**Comment by rhdelima** [comment]
![image](https://user-images.githubusercontent.com/10294014/54329705-bd11d780-464d-11e9-9ae8-fab678297ffe.png)
