### ISSUE TITLE
Hide Chrome input validation

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#920]
When setting proper input type, Chrome (electron) will show this validation message, that does not work with our wallet style  https://gyazo.com/be1d07920f45355eff59dd08d860b9f9 

Suggestion is to hide it.

HTML Solution: use `novalidate` in the form https://www.wufoo.com/html5/novalidate-attribute/ 
JS Solution: https://www.telerik.com/blogs/building-html5-form-validation-bubble-replacements

**Comment by rhdelima** [comment]
Failed QA. I'm still seeing the issue on 2019.03.12.19 build.
![image](https://user-images.githubusercontent.com/10294014/54251420-288e7300-4582-11e9-88e3-e30337051ba7.png)

![image](https://user-images.githubusercontent.com/10294014/54251600-b4a09a80-4582-11e9-8cb7-e44fe0497792.png)

**Comment by eduardosmoura** [comment]
@rhdelima as discussed on the meeting, ignore this change on the Create Selfkey ID form. Which OS are you using (Mac, Windows, Linux)? Because I tested on Windows and looks like it's working for the Edit Attribute Modal. I will update the Add Attribute Modal.

**Comment by rhdelima** [comment]
Looks good now. :)
