### ISSUE TITLE
Document Expiry date doesn't show in table

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#921]
When adding a new document, the expiry date that I set, doesn't get displayed in the documents table:

1. The table is showing "-" https://gyazo.com/7188c2fad22a729be5cd1c6bf7b84913 
2. Here is the date when I edit https://gyazo.com/8c7d382a1704c249e8d60f693770c37b

**Comment by sk91** [comment]
@oanamangiurea it's issue date, not expiry date in your screenshot

**Comment by oanamangiurea** [comment]
You are right @sk91 Didn't notice it. Closing it then as not a bug
