### ISSUE TITLE
Login - display nickname for address

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#922]
On wallet login - use existing ETH Address screen we want the dropdown to display the nickname(s) that a user is setting when creating a Selfkey ID. This will help users with multiple wallet addresses. 

It should be displayed as [nickname] - [wallet address] in the dropdown, as shown here: https://gyazo.com/78c08c689ca4fa087ff4283ad7d08612 (where John Doe is the nickname I have chosen)

**Comment by eduardosmoura** [comment]
DEV Test evidence: http://recordit.co/r6ehmaz50T
