### ISSUE TITLE
when application to kyc chain fails, wallet does not show error message

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#923]

**Comment by sk91** [comment]
QA: to test you can create 2 applications from different adressess with the same email attribute and see an error on application checklist screen

**Comment by rhdelima** [comment]
Looks good.

![image](https://user-images.githubusercontent.com/10294014/54354013-8610e580-4690-11e9-9853-4bff8ee23eb0.png)
