### ISSUE TITLE
Default window size too small on Linux

### ISSUE THREAD

**Issue by TwoAbove** [SelfKeyFoundation/Identity-Wallet#925]
Ubuntu 18.10, 1920*1080, selfkey-identity-wallet-0.3.0-beta-x86_64

![image](https://user-images.githubusercontent.com/9610438/54138977-9a0adc00-4431-11e9-8847-3bdd44a83de4.png)

The issue is the menu bar on the top

**Comment by TwoAbove** [comment]
https://github.com/SelfKeyFoundation/Identity-Wallet/blob/master/src/main/main.js#L138
Just need to add
```
mainWindow.setMenu(null)
```
Or change the css.

This issue resolves on the login screen

**Comment by eduardosmoura** [comment]
DEV Test evidence: http://recordit.co/fUlp1tzOXA
