### ISSUE TITLE
Add basic matomo tracking to new react wallet

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#929]
Lib for helping doing this https://www.npmjs.com/package/react-piwik

url: https://analytics.selfkey.org/
siteId: 1

We need to set the userId which is currently the MD5 Hash of the public key. See here: https://github.com/SelfKeyFoundation/Identity-Wallet/blob/a239bc70adc9b7b1074c994c7a5935702efefd7a/src/renderer/angular/classes/wallet.js

So, this userId is set once a wallet is unlocked or created.

**Comment by CortecKYC** [comment]
@Chaviland7 How is this card going? Anything you need help with?

**Comment by Chaviland7** [comment]
@CortecKYC Rodrigo helped move this to QA today so that the other Matomo cards can proceed. Sorry this took longer than expected.

**Comment by rhdelima** [comment]
Looks good.
