### ISSUE TITLE
"You have an existing unpaid application" message displayed after switching accounts

### ISSUE THREAD

**Issue by Kuraturpa** [SelfKeyFoundation/Identity-Wallet#941]
Tested with the latest dev version on Linux.
Steps to replicate:
1. Create a new selfkey ID or use an existing one.
2. Create incorporation application
3. Click Switch Account and create a new one
4. Go to Marketplace and incorporation
5. Click any incorporation marketplace item
![img-2019-03-13-115622](https://user-images.githubusercontent.com/603669/54255099-30054a80-4589-11e9-8605-dff58ca56595.png)

**Comment by andregoncalves** [comment]
@eduardosmoura are we clearing RP on switch account? 
(I remember you worked on the clear RP feature)
/cc @rodrigopavezi
