### ISSUE TITLE
Display message when no internet connection upon opening the app

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#943]
https://projects.invisionapp.com/d/main#/console/15222689/319048193/preview

**Comment by sk91** [comment]
<img width="1631" alt="Screen Shot 2019-03-13 at 19 25 36" src="https://user-images.githubusercontent.com/1021965/54300629-ea1aa780-45c5-11e9-9d4d-35f47bae3e54.png">
