### ISSUE TITLE
If application is rejected and unpaid, the wallet still shows it as active

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#944]

**Comment by sk91** [comment]
<img width="1665" alt="Screen Shot 2019-03-13 at 11 09 15" src="https://user-images.githubusercontent.com/1021965/54266981-14964180-4581-11e9-9fb2-d740b64012c9.png">

**Comment by andregoncalves** [comment]
@rodrigopavezi I can take a look at this.

**Comment by sk91** [comment]
@andregoncalves: show both button and notification

**Comment by sk91** [comment]
@andregoncalves @rodrigopavezi should this go to QA?

**Comment by rodrigopavezi** [comment]
@sk91 I will wait @andregoncalves on this.

**Comment by andregoncalves** [comment]
It was not opened as an issue, but it should yes.
