### ISSUE TITLE
KYC checklist duplicate attribute type ui

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#951]
- [x] implement "add" button https://projects.invisionapp.com/d/main#/console/15222689/348711612/preview (
- [x] select box for duplicate attribute type https://projects.invisionapp.com/d/main#/console/15222689/317955444/preview 

related to https://github.com/SelfKeyFoundation/Identity-Wallet/issues/885

**Comment by rhdelima** [comment]
Looks good. Pass
