### ISSUE TITLE
in file upload form, pdf file should be opened at once instead of saved

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#953]
related to https://github.com/SelfKeyFoundation/Identity-Wallet/issues/896

http://recordit.co/cJo1UCRUFz

**Comment by designhorf** [comment]
_target=blank https://stackoverflow.com/questions/32402327/how-can-i-force-external-links-from-browser-window-to-open-in-a-default-browser

**Comment by rodrigopavezi** [comment]
Blocked waiting for this fix https://github.com/electron/electron/issues/12337

**Comment by rhdelima** [comment]
@sk91 , A 2.5MB pdf shows blank screen on preview.

![image](https://user-images.githubusercontent.com/10294014/56628211-7ca96e80-667b-11e9-8933-a134daf36556.png)

**Comment by rhdelima** [comment]
Looks good. Pass
