### ISSUE TITLE
Exchanges import does not delete obsolate exchanges

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#963]

**Comment by sk91** [comment]
QA:

When in exchanges marketplace
As a user 
I don't see Gatecoin anymore

**Comment by rhdelima** [comment]
@sk91 ,
Can we move TagCash next to Kyber? Is it also possible to hide View All Details if description is short?

![image](https://user-images.githubusercontent.com/10294014/54416902-af3a8000-473b-11e9-87bf-2645c43e9580.png)

![image](https://user-images.githubusercontent.com/10294014/54417039-05a7be80-473c-11e9-8772-79f191e2deaf.png)

**Comment by rhdelima** [comment]
Closing this one. Already logged a ticket for UI issue
