### ISSUE TITLE
Dashboard - Transactions history style

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#970]
https://projects.invisionapp.com/d/#/console/15222689/316491951/preview

**Comment by rhdelima** [comment]
This ticket is blocked due to the following reasons:
1. Transaction is only displayed when it is completed. So Sending/Receiving status won't be shown.
2. https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1055

**Comment by CortecKYC** [comment]
@rodrigopavezi This card is blocked. What should we do about it?

**Comment by CortecKYC** [comment]
@rodrigopavezi ^^

**Comment by rodrigopavezi** [comment]
@rhdelima added an issue for 1. https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1102

so closing this one for now. Cheers
