### ISSUE TITLE
My Crypto graph issue for first time users

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#972]
![image](https://user-images.githubusercontent.com/10294014/54469179-bf03a400-47cf-11e9-8d52-67de2cc9ad87.png)

**Comment by oanamangiurea** [comment]
@rhdelima I think your screenshot hasn't been saved

**Comment by rhdelima** [comment]
@oanamangiurea My bad. It's uploaded now.

**Comment by rodrigopavezi** [comment]
@rhdelima that is because the value of key in usd is too little compared with eth. Please check with a custom token that has more value. Cheers

**Comment by rhdelima** [comment]
@rodrigopavezi 
Please see differences below. 

**First Time user:**
![image](https://user-images.githubusercontent.com/10294014/54529460-ec607580-49ba-11e9-95de-777c86802815.png)

**Not first time user:**
![image](https://user-images.githubusercontent.com/10294014/54529355-a3102600-49ba-11e9-9103-cdf04b174f38.png)

**Comment by rodrigopavezi** [comment]
@rhdelima I see, thanks for getting back to it with more details. Let's leave this for next release. I will target it to v 1.0.1-beta which should go out in 2, 3 weeks.

**Comment by eduardosmoura** [comment]
@rhdelima I could not reproduce the issue on Windows: http://recordit.co/2q9f3FHMN4

Could you send me your test wallets info?

**Comment by rhdelima** [comment]
@eduardosmoura Have you deleted your SelfKey folder? Issue is only encountered for first time users.

**Comment by CortecKYC** [comment]
@rodrigopavezi @eduardosmoura @rhdelima Please do something about this issue. 
Try to reproduce the bug by deleting Selfkey folder as Ralph suggested or close it if the issue has been fixed.

**Comment by rodrigopavezi** [comment]
@rhdelima can you try to reproduce it now with the latest release wallet if you haven't yet? Cheers

**Comment by rhdelima** [comment]
Looks good. Pass
