### ISSUE TITLE
Attributes & Documents drop down menu are displaying white on WIN build

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#975]
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/7da9287c-2e67-4967-bec9-d5aeab8e0f14)

![image](https://user-images.githubusercontent.com/10294014/54477777-f01ebb80-4845-11e9-8de6-d2fba43b0ed1.png)

**Comment by rhdelima** [comment]
@eduardosmoura 

Failing this one. Nationality and Country of Residency drop down are not fixed

![image](https://user-images.githubusercontent.com/10294014/54574611-f4a4c900-4a2b-11e9-927b-14cf37da7f33.png)

![image](https://user-images.githubusercontent.com/10294014/54574641-08502f80-4a2c-11e9-9203-ca826251be99.png)

**Comment by sk91** [comment]
https://stackoverflow.com/questions/54429548/material-ui-native-select-when-using-dark-theme-on-windows-browsers-has-white-t

**Comment by sk91** [comment]
@eduardosmoura, I will take it and propagate your fixes to json-schema-form.
I will need you to test though

**Comment by sk91** [comment]
@eduardosmoura need to test if it is fixed on selfkey-ui first https://github.com/SelfKeyFoundation/selfkey-ui/pull/118

blocked for now
