### ISSUE TITLE
Exchanges Marketplace UI issues

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#978]
1. Move TagCash next to Kyber
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/a726e1af-1ca6-41ee-955e-daabf1efd8c0)

2. As discussed on the call, replace View buttons to Coming Soon (disabled).

**Comment by sk91** [comment]
<img width="1266" alt="Screen Shot 2019-03-18 at 20 39 00" src="https://user-images.githubusercontent.com/1021965/54554930-51699a80-49be-11e9-8832-651f6339aeff.png">
