### ISSUE TITLE
Incorporation data issue

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#983]
![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/b7f359b5-7589-4b94-8029-743eb956fd49)

![image.png](https://images.zenhubusercontent.com/5b9ab85a7dfd064d6bed8869/07f76e8a-9662-451c-a3ad-4e86bbe050ef)

Change font color for links and link should open on a browser
![image](https://user-images.githubusercontent.com/10294014/54553511-4e39d300-49ed-11e9-93e3-be42e600c0c4.png)

**Comment by andregoncalves** [comment]
1. is actually correct. Estonian characters.
2. Should be fixed with latest airtable updated.
3. WIP, requires code change.
