### ISSUE TITLE
Add Context Menu to wallet

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/Identity-Wallet#988]
SK CS reported: It is not possible to right-click on the "Token Address" filed and select "Paste" from the drop-down

![context menu.png](https://images.zenhubusercontent.com/5c6a709f9d62b128eab3a3a5/2b2b8d04-36e2-4a62-838f-6afd80cd8edb)

**Comment by sk91** [comment]
possible solution using this lib: https://github.com/sindresorhus/electron-context-menu
